### ISSUE TITLE
Demo: Dialog buttons all open the same dialog

### ISSUE THREAD

**Issue by TeNNoX** [material-components/material-components-web-components#1000]
**Describe the bug**
On the demo page for Dialog, all of the buttons only open the same dialog "Initial Focus"

**To Reproduce**
1. Go to https://mwc-demos.glitch.me/demos/dialog.html
2. Click on any of the buttons
3. See "Initial Focus" dialog

**Expected behavior**
I think this is obvious. But nevertheless: It should open the respective dialog related to that button.

**Screenshots**
![Peek 2020-03-12 16-32](https://user-images.githubusercontent.com/2084639/76543905-12f6a680-647f-11ea-9305-ae77fb18e79d.gif)

**Browser Version (please complete the following information):**
 - OS: elementary OS 5.1.2 Hera
 - Browser: **Firefox**
 - Version: Dev 74.0 (64-bit)
 - Also reproduced on **Chrome**

**Comment by e111077** [comment]
oops
