### ISSUE TITLE
Allow users to customize MDC sass

### ISSUE THREAD

**Issue by TomzBench** [material-components/material-components-web-components#1012]
**Is your feature request related to a problem? Please describe.**
The mdc library which this component library is dependent on has a very rich sass API that I would like access too when using this library.  It appears the mwc build process will compile all the sass and not allow for customization.

**Describe the solution you'd like**
It seems the current ideas are to create a unique themeing experience but I think it would be easier if you just pass through the native mdc styling API.  I think this would mean changing the way this library is built.

**Describe alternatives you've considered**
Right now I clone and hack my changes into the components directly (for example a dense textfield or something).  Then since I am forking, my sass gets compiled into the main components.

**Additional context**

**Comment by TomzBench** [comment]
https://github.com/TomzBench/m-elements

Here is some example passing through mdc components sass to the component.

It uses a higher order function to pass a css object to the LitElement.  When you instantiate the custom element it will load your sass as part of it's shadow dom.

https://github.com/TomzBench/m-elements

**Comment by asyncLiz** [comment]
Closing this for now since we talked offline in Slack.

The tl;dr is that we recommend extending our components if you'd like to use MDC's Sass functionality to customize them currently. We're actively working to achieve parity with MDC's customizability.
