### ISSUE TITLE
Demo is not working?

### ISSUE THREAD

**Issue by zaki-yama** [material-components/material-components-web-components#1025]
**Describe the bug**
When I clicked [Demos on Glitch](https://mwc-demos.glitch.me/demos/) on README, only a blank page appeared.

**To Reproduce**
1. Open https://mwc-demos.glitch.me/demos/

Then blank page appears.

**Expected behavior**
I can see demo.

**Browser Version (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - Browser: chrome 
 - Version 80.0.3987.149

**Additional context**
Here's the error message I could see in browser devtool.

> updating-element.js:1 Failed to load module script: The server responded with a non-JavaScript MIME type of "". Strict MIME type checking is enforced for module scripts per HTML spec.

**Comment by asyncLiz** [comment]
I just checked the demos and the site is up and working for me. Can you check again? It's possible Glitch had a glitch.

**Comment by zaki-yama** [comment]
@asyncLiz 
Thank you for checking!
Now I can see the demo. Sorry it was a Glitch's problem...
