### ISSUE TITLE
Add focus forwarding for BaseElement

### ISSUE THREAD

**Issue by 200Puls** [material-components/material-components-web-components#1026]
**Is your feature request related to a problem? Please describe.**
I need to programatically set the focus to a mwc-icon-button

**Describe the solution you'd like**
The focus() method should focus the button. 

**Describe alternatives you've considered**
As a workaround it is possible to set the focus by accessing the shadowRoot directly:

`this.shadowRoot.querySelector('mwc-icon-button').shadowRoot.querySelector('button').focus();`

**Comment by asyncLiz** [comment]
[ShadowRoot.delegatesFocus](https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot/delegatesFocus) would be nice to use for this, though it's only available in Chrome/Edge. Adding to our backlog to prioritize.

**Comment by asyncLiz** [comment]
We're going to re-purpose this to add focus/click forwarding functionality for all elements in our BaseElement class.
