### ISSUE TITLE
Support space-between in form field

### ISSUE THREAD

**Issue by Misiu** [material-components/material-components-web-components#1041]
**Is your feature request related to a problem? Please describe.**
I'm trying to create this type of UI:
![image](https://user-images.githubusercontent.com/1741838/77621811-74b61680-6f3d-11ea-872e-1fcc7be57dd9.png)

with web components, but unfortunately, it isn't easily doable.
I was suggested to use formfield but this gives me this:
![image](https://user-images.githubusercontent.com/1741838/77621821-78e23400-6f3d-11ea-8821-0cda48f467bd.png)
or:
![image](https://user-images.githubusercontent.com/1741838/77624382-058ef100-6f42-11ea-8c2e-b460706238c7.png)
 when I add `alignEnd` to `mwc-formfield`

**Describe the solution you'd like**
I'd like to have the ability to easily add space between label and slot inside `mwc-formfield`.

Proposed syntax:
      <mwc-formfield label="Lisa" alignEnd spaceBetween>
        <mwc-switch />
      </mwc-formfield>

Results I'm expecting to get:
![image](https://user-images.githubusercontent.com/1741838/77624667-759d7700-6f42-11ea-8e12-d7d2e244574a.png)

**Describe alternatives you've considered**

**Additional context**
I was suggested by @asyncLiz (in https://github.com/material-components/material-components-web-components/issues/999) to create this FR. Maybe she will be able to add additional context to this.
I've tried doing that with styles, but I wasn't able to get results I want:
https://stackblitz.com/edit/material-web-components-fiqjsb?file=index.js

**Comment by asyncLiz** [comment]
Upstream dependent on https://github.com/material-components/material-components-web/issues/5747

**Comment by asyncLiz** [comment]
Fixed in #1083

**Comment by Misiu** [comment]
@asyncLiz thank you 🙂
