### ISSUE TITLE
Two instances of 'mwc-textfield' produces an error.

### ISSUE THREAD

**Issue by anoblet** [material-components/material-components-web-components#106]
Not sure if this is the right place to post something like this, but I've been trying to test these elements.

Cloning and linking, I am getting this error when trying to use two instances of 'mwc-textfield' directly inside of the render function without a parent element:

Uncaught (in promise) TypeError: Cannot read property 'parentNode' of null

Creating a single instance of 'mwc-textfield' works as expected.

I'm using the pwa-starter-kit from Polymer.

https://github.com/anoblet/pwa-starter-kit/blob/template-no-redux/src/components/Countdown/View/Input.js

**Comment by keanulee** [comment]
We are aware of this issue and hoping to release the fix soon - see https://github.com/Polymer/lit-element/issues/202

**Comment by anoblet** [comment]
Awesome! Thanks a lot!

**Comment by keanulee** [comment]
Fix released in lit-element 0.6.1 (which should match the semver targets of these elements)
