### ISSUE TITLE
mwc-tab does not allow you to left justify tabs

### ISSUE THREAD

**Issue by mbinette** [material-components/material-components-web-components#1070]
**Describe the bug**
I have a <mwc-tab-bar> with <wmc-tab minWidth> inside of it. The tab itself displays as I expect but it is in the middle of the screen rather than left justified in the tab-bar. Looking at the CSS, .mdc-tab-bar is set to 100% width and mwc-tab :host is set to justify-content:center, flex: 1 0 auto. 

If we could change that justify-content: center to justify-content: flex-start and flex: 1 0 auto to flex: 0 0 auto when minWidth is set then it would work as I would expect.

**Expected behavior**
When adding tabs set to minWidth I expect them to be left justified and not take up the entire width of the div it is contained in.

**Screenshots**
Current:
![image](https://user-images.githubusercontent.com/1036991/78275005-0ba34580-74df-11ea-806e-58e4ad63b194.png)

Expected:
![image](https://user-images.githubusercontent.com/1036991/78275159-3b524d80-74df-11ea-99d6-309a28b0a3e4.png)

**Comment by asyncLiz** [comment]
Like this? https://jsbin.com/fivokowice/edit?html,output

Set the width of the `<mwc-tab-bar>` explicitly. Setting it to `min-content` will collapse it to the natural width of the tabs with their labels.

**Comment by mbinette** [comment]
Well that was easy! Just tested and that works. Thanks.
