### ISSUE TITLE
Slider min/max is not respected

### ISSUE THREAD

**Issue by bennypowers** [material-components/material-components-web-components#1079]
**Describe the bug**
When setting min/max on a slider, the bounds are not respected. Dragging the thumb sets values from 0-100 regardless of min/max

**To Reproduce**
```js
render() {
  return html`
    <mwc-slider .min="2000" .max="2050" pin step="1" .value="2020"></mwc-slider>
 `;
}
```

https://webcomponents.dev/edit/H9vYUiJDCU1ilo7ELKE1

**Expected behavior**
Values out of bounds should not be set. Dragging the thumb should move the slider between bounds.

**Browser Version (please complete the following information):**
 - OS: mac
 - Browser: FF
 - Version: 75 series

**Comment by e111077** [comment]
Sorry, slider has not yet been migrated to the material 2 spec, so it hasn't had as much love

**Comment by e111077** [comment]
in review #1081
