### ISSUE TITLE
Usage Questions regarding use in HoloViz Panel

### ISSUE THREAD

**Issue by MarcSkovMadsen** [material-components/material-components-web-components#1080]
Hi

I'm a contributor to [HoloViz Panel](https://panel.holoviz.org/) a framework for creating awesome analytics web apps using Python only.

I would like to increase the functionality/ layout/ styling functionality of Panel and is looking to Material Design and Web components for this.

I have created the core functionality for easily adding any web components to Panel via simple configuration of attributes and properties to bind to. See https://github.com/holoviz/panel/pull/1122.

I'm now ready to start experimenting with the `mwc` components but have some questions.

- Would the most basic mwc components be useable now. For example the button and select components?
- Is there some kind of timeline or time estimates for this project?
    - When would the first reliable version be expected?
- Can I style the components?
   - How would I do this?
   - I can see in the Button example that I can style that one individually. But can I style generally and how? The primary thing for me is to be able to set the colors like primary, secondary and warning and the theme (light or dark).
- Where should I ask questions?
    - Is there a forum or gitter channel?
- Is there some documentation?
- Are there alternatives that I should look to instead right now?
    - Should I use the [MDC Web Components](https://github.com/material-components/material-components-web/) instead?
    - Could I use the [material-ui components](https://material-ui.com/)? (I need something that can be used from html/css/javascript only I think).

Thanks.

#### Additional Context

I am working on contributing a material design inspired **Theme Builder** for Panel. See  https://github.com/holoviz/panel/pull/1157#issuecomment-609375821

![theme_builder](https://user-images.githubusercontent.com/42288570/78469753-316d5c00-7724-11ea-8c8c-d08c4c8310ee.gif)

I have already implemented a lot of the **wiredjs** components so I believe the mwc components should be easy to implement as well.

![web_component_poc](https://user-images.githubusercontent.com/42288570/75579988-3f65f800-5a67-11ea-90b0-10f89ea2aea8.gif)

**Comment by e111077** [comment]
Heya, we haven't forgotten about your question. Just wanted to let you know that I'm going to raise your questions up in our next team meeting later this week

**Comment by MarcSkovMadsen** [comment]
I have started experimenting a bit. I'm not able to use the `mwc-drawer` though due to this issue https://github.com/mjackson/unpkg/issues/242#issuecomment-611327084

```bash
Package blocking-elements@0.1.0 does not contain an ES module
```

**Comment by e111077** [comment]
I'll try to cover all your questions in a similar format:

- _Would the most basic mwc components be useable now. For example the button and select components?_
    - **Most of the ones that are published should be usable for now. They function but may be subject to breaking changes as this library is still in alpha. Additionally, we are still making a11y and performance fixes / improvements as we go along.**
- _Is there some kind of timeline or time estimates for this project?_
    - **We expect to reach component and feature parity with the MDC web library. The last push for component parity work should be around September**
    - _When would the first reliable version be expected?_
        - **I cannot give a concrete date for this. Best I can say is "when it's ready"**
- _Can I style the components?_
    - **yes**
    - _How would I do this?_
		- **Most of our components expose a [CSS Custom Properties](https://developer.mozilla.org/en-US/docs/Web/CSS/--*) API. Each element's API documentation should have a simple example. [Select, for example.](https://github.com/material-components/material-components-web-components/tree/master/packages/select#styled) Additionally you can style most components that are slotted in from the light dom of a component (direct children of a webcomponent). We have also just published [theming documentation](https://github.com/material-components/material-components-web-components/blob/master/docs/theming.md)**
    - _I can see in the Button example that I can style that one individually. But can I style generally and how? The primary thing for me is to be able to set the colors like primary, secondary and warning and the theme (light or dark)._
        - **One of the reasons we use CSS Custom Properties is that they apply and flow down the tree. For example, you can set `body {--mdc-theme-primary: red}` and that should flow and apply through the dom tree and flow through shadow roots as well. We also explicitly expose specific parts of our DOM for styling so that we can make sure it's easy to keep to Material Design specification. If there is something you want to style and are unable to do so, filing an issue would start the process to speak to our designers and contemplate that part of the spec. See the theming doc in the previous response for more information.**
- _Where should I ask questions?_
	- **For MWC-specific questions the Polymer slack (`#material` channel is preferred but `#general` is okay as well.)**
    - _Is there a forum or gitter channel?_
		- **Since the mwc elements are developed by the Polymer team (under Material Design) I would recommend connecting through the [Polymer Slack](https://www.polymer-project.org/slack-invite). There is a `#material` channel that is monitored by the mwc team and a group of helpful community members. MDC questions are also welcome there. `#general` chat would answer most of your `webcomponent` or `lit-element` or `lit-html` questions if you have those (e.g. how do CSS Custom properties work with shadow DOM etc.). We also have a material design discord, but we are recommending people on the web section of that discord ask questions on the Polymer slack as it is more active. Here is an [invite link to the material design discord](https://discord.gg/RcCBEex).**
- _Is there some documentation?_
	- **Yes. Each component has API documentation in the readmes located at `/packages/<component>/README.md`. We are in the process of writing more-general usage documentation and updating https://material.io to include mwc usage docs**
- _Are there alternatives that I should look to instead right now?_
	- **For production use today, we recommend [MDC-Web](https://github.com/material-components/material-components-web/tree/master). We’re actively working toward parity for MWC, and we’re working on a transition path from MDC-Web to MWC. If you’re developing with Angular or React, Angular Material and Material-UI are good choices as well.**
    - _Should I use the [MDC Web Components](https://github.com/material-components/material-components-web/) instead?_
		- **Answered above. TL;DR yes for now**
    - _Could I use the [material-ui components](https://material-ui.com/)? (I need something that can be used from html/css/javascript only I think)._
		- **Answered above. TL;DR yes for now if you are using react.**

I'm going to close this issue, but please feel free to add more questions to this issue
