### ISSUE TITLE
List items within a Drawer don't render correctly

### ISSUE THREAD

**Issue by cdock1029** [material-components/material-components-web-components#1086]
**Describe the bug**
List items within a drawer don't have rounded edges, nor proper padding and margins.

**To Reproduce**
1. Place `mwc-list-item`'s within an `mwc-drawer`
2. Observe how they do not match with list items [here](https://material-components.github.io/material-components-web-catalog/#/component/drawer)

**Expected behavior**
Expect list items within a drawer to have rounded corners and proper margins/padding.

I'm unfamiliar with web components but I assume it is that this css rule which works for regular material web is not applied as the list item does not know it is in a drawer: `.mdc-drawer .mdc-list-item`

**Screenshots**

### **Incorrect**:
![Screenshot from 2020-04-07 23-08-42](https://user-images.githubusercontent.com/802586/78740513-000fae80-7925-11ea-81cd-3f6a0a3aee9d.png)

### **Correct**:

![Screenshot from 2020-04-07 23-16-19](https://user-images.githubusercontent.com/802586/78740832-cee3ae00-7925-11ea-9bf5-7e2e78e32b12.png)

**Browser Version (please complete the following information):**
 - OS: Manjaro Linux
 - Browser: Brave 
 - Version: 1.7.61 Chromium: 80.0.3987.132

**Additional context**
components version: `0.15.0-canary.31eac79f.0`

**Components used as follows:**

```svelte
<mwc-drawer open={$drawerOpen} hasHeader={true} type="dismissible" class="h-screen">
  <span slot="title">Drawer Title</span>
  <span slot="subtitle">subtitle</span>
  <div class="flex flex-col">
    <mwc-list activatable={true}>
      <mwc-list-item graphic="star">
        <span>Item 0</span>
        <mwc-icon slot="graphic">star</mwc-icon>
      </mwc-list-item>
      <mwc-list-item selected={true} activated={true}>Item 1</mwc-list-item>
      <mwc-list-item>Item 2</mwc-list-item>
      <mwc-list-item>Item 3</mwc-list-item>
      <li divider={true} role="separator" padded={true} />
    </mwc-list>
    <mwc-select label="preselected" class="m-2">
      <mwc-list-item />
      <mwc-list-item selected={true} value="0">Item 0</mwc-list-item>
      <mwc-list-item value="1">Item 1</mwc-list-item>
      <mwc-list-item value="2">Item 2</mwc-list-item>
      <mwc-list-item value="3">Item 3</mwc-list-item>
    </mwc-select>
  </div>
  <div slot="appContent">
    <AppBar>
      <slot />
    </AppBar>
  </div>
</mwc-drawer>
```

**Comment by e111077** [comment]
good catch

**Comment by cdock1029** [comment]
Also (I can make another issue...), how to turn `mwc-list-item`'s into links is unclear. I only highlight it here because it's pretty standard use case to have a navigation drawer with links.

Something like this below makes it so only clicking the text within the item navigates... full width/height of item doesn't act as link.

```html
<mwc-list-item>
  <a href="/">Home</>
</mwc-list-item>
```
Other permutations have their own issues. `a` outside of `mwc-list-item` is formatted wrong. Need some way to render a list-item "as" an "a" or..vice versa.

**Comment by e111077** [comment]
Do you mind filing another issue, we have an epic dedicated to that under #441

**Comment by cdock1029** [comment]
@e111077 added https://github.com/material-components/material-components-web-components/issues/1095

**Comment by e111077** [comment]
Coming back to this issue, we have decided that we need to decouple styles across components. This can be implemented in the following way:

```css
mwc-drawer mwc-list-item {
  margin: 8px;
  border-radius: 4px;
}

mwc-drawer mwc-list-item:first-of-type {
  margin-top: 4px;
}

mwc-drawer mwc-list-item:last-of-type {
  margin-bottom: 4px;
}
```
