### ISSUE TITLE
mwc-top-app-bar does not work well in Jupyter Notebook

### ISSUE THREAD

**Issue by MarcSkovMadsen** [material-components/material-components-web-components#1097]
I'm trying to use the `mwc` components in a Jupyter Notebook.

I can see that the `mwc-top-app-bar` does not work well. It sizes to the full width of the screen. Not the full width of the `div class="output_subarea output_html rendered_html">` in which its inserted.

![image](https://user-images.githubusercontent.com/42288570/78916337-9e1e8880-7a8d-11ea-9561-6b87674667b5.png)

Maybe its by design. I was just hoping I could use it in the notebook. I've also tried to set the `width` manually to `400px`. It does not work either.

## Code

```html
%%HTML
<script src="https://unpkg.com/@webcomponents/webcomponentsjs@next/webcomponents-loader.js"></script>
<script type="module" src="https://unpkg.com/@material/mwc-icon-button@0.14.1/mwc-icon-button.js?module"></script>
<script type="module" src="https://unpkg.com/@material/mwc-top-app-bar@0.14.1/mwc-top-app-bar.js?module"></script>
<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Material+Icons&display=block" rel="stylesheet">

<mwc-top-app-bar style="width:300px">
    <mwc-icon-button icon="menu" slot="navigationIcon"></mwc-icon-button>
    <div slot="title">Title</div>
    <mwc-icon-button icon="file_download" slot="actionItems"></mwc-icon-button>
    <mwc-icon-button icon="print" slot="actionItems"></mwc-icon-button>
    <mwc-icon-button icon="favorite" slot="actionItems"></mwc-icon-button>
    <div><!-- content --></div>
</mwc-top-app-bar>
```

**Comment by asyncLiz** [comment]
Thanks for the issue! We're already tracking this feature in https://github.com/material-components/material-components-web-components/issues/1064 and #527, so I'm going to close this as a duplicate 🙂
