### ISSUE TITLE
Loading issues in Glitch demos

### ISSUE THREAD

**Issue by MarcSkovMadsen** [material-components/material-components-web-components#1107]
When using `mwc` components from `unpkg.com` myself or when browsing 
https://mwc-demos.glitch.me/ I get errors in the console and the page does not load.

Often I can reload and the problem goes away.

1. Navigate to https://mwc-demos.glitch.me/demos/index.html
2. Observe the page does not show anything
3. Observe the console shows errors like 

```bash
Loading module from “https://mwc-demos.glitch.me/node_modules/@material/dom/events.js” was blocked because of a disallowed MIME type (“”).
index.html
Loading failed for the module with source “https://mwc-demos.glitch.me/node_modules/@material/dom/events.js”. index.html:25:1
Loading failed for the module with source “https://mwc-demos.glitch.me/node_modules/@material/dom/ponyfill.js”. index.html:25:1
Loading failed for the module with source “https://mwc-demos.glitch.me/node_modules/@material/ripple/foundation.js”. index.html:25:1
Loading failed for the module with source “https://mwc-demos.glitch.me/node_modules/@material/mwc-ripple/mwc-ripple-global-css.js”. index.html:25:1
Loading failed for the module with source “https://mwc-demos.glitch.me/node_modules/@material/ripple/util.js”. index.html:25:1
The connection to https://mwc-demos.glitch.me/__es-dev-server__/message-channel was interrupted while the page was loading. index.html:38:24
```

![image](https://user-images.githubusercontent.com/42288570/79001083-26646280-7b4e-11ea-841f-a1fedf656f50.png)

4. If I click CTRL+f5 the page loads without errors

![image](https://user-images.githubusercontent.com/42288570/79001149-4562f480-7b4e-11ea-902f-fa2c337eef11.png)

5. If I close the tab and open a new one I see the error again

![image](https://user-images.githubusercontent.com/42288570/79001232-64618680-7b4e-11ea-8bda-ff5e39af6185.png)

6. I can then continue closing tabs, opening again and sometimes the error message is there sometimes not.

![mwc_issue](https://user-images.githubusercontent.com/42288570/79001854-8e677880-7b4f-11ea-813a-ada99800220e.gif)

I sometimes get other errors in Chrome when loading the demos from Glitch.

![image](https://user-images.githubusercontent.com/42288570/79001803-755ec780-7b4f-11ea-9dc8-bda974d00776.png)

Chrome: Version 80.0.3987.132 (Official Build) (64-bit)
Fixe Fox: 75.0 (64-bit) on Windows 8.1

**Comment by e111077** [comment]
Hello, this seems to possibly be a regression with our hosting provider. We are investigating now

**Comment by e111077** [comment]
server reboot seems to have solved the issue. can you still repro?

**Comment by e111077** [comment]
nevermind still having server issues. Investigating switching to new provider

**Comment by e111077** [comment]
closing issue in favor of #1112
