### ISSUE TITLE
[mwc-textfield] not robust to undefined value

### ISSUE THREAD

**Issue by christophe-g** [material-components/material-components-web-components#1116]
**Describe the bug**
`mwc-textfield` does not like when its value is set to undefined. 

This happens for instance when we are using the component within a Polymer component, with bindings such as : 

```html
<mwc-textfield value="[[boundTo.value]]"><mwc-textfield>
```

This cause : 
- label not to float again when a new value is set
- throw "Uncaught (in promise) TypeError: Cannot read property 'length' of undefined"

Situation is similar with `mwc-textarea`;

**To Reproduce**
https://codepen.io/christophe-g/pen/ZEbGMwp

**Expected behavior**
The component should be able to handle such case

**Screenshots**
![image](https://user-images.githubusercontent.com/1168053/79128552-fe6e3c80-7da3-11ea-9f79-4d0f299e684a.png)

**Comment by asyncLiz** [comment]
I'm a bit torn on this issue. At the core of the problem, the textfield does not support `value` being set to `undefined`. The type is strictly a string and should only be set to a string. Coercing undefined values should be the responsibility of the application.

This would set a strange precedent for other types as well. What do we do if textfield's value is set to a `Date` or other types?

If we're emulating native behavior, should all types be allowed, and coerced with `.toString()`
https://jsbin.com/vanabequmu/edit?html,output

I think this issue subtly raises a few bigger questions.

**Comment by christophe-g** [comment]
> I'm a bit torn on this issue. At the core of the problem, the textfield does not support value being set to undefined. The type is strictly a string and should only be set to a string. 

I understand the sentiment, but my experience is that when things can go wrong, they will. The problem here is that when an undefined value is set to the component (for whatever reason ... ) it breaks it. 
It is usually safer and less costly to prevent such unwanted behaviors (when easy to do; the proposed fix simply says don't call Foundation `setValue` when value is undefined).

> Coercing undefined values should be the responsibility of the application.

In this case the responsible application is Polymer, which I doubt will change the way it applies values to non-Polymer elements/nodes property. 

I can further override `<mwc-textfield>` so that two-way binding schemes such as  `<mwc-textfield value="{{boundTo.value}}"><mwc-textfield>` work, which I already do <sup>[1](#mytexfield)</sup> . But my sense is that mwc-textfield simply should be more robust in dealing with setting undefined values. 

<a name="mytextfield">1 - current override for two-way bindings</a>: 
```js
class PwiTextField extends TextField {
  handleInputChange() {
    super.handleInputChange(...arguments);
    this.dispatchEvent(new CustomEvent('value-changed', { detail: { value: this.value }, bubbles: true, composed: true }));
  }
}
```

**Comment by asyncLiz** [comment]
We're going to do a little more research on the Polymer side of things to see if we can find a better pattern to handle for how this should be handled using mwc in Polymer.

For example, this could be a computed binding instead of a direct binding to ensure that the value is not undefined.

We're also going to do a little more research on exactly what we want to do when textfield's value is set to undefined given how it's handled natively with `<input>`.

**Comment by christophe-g** [comment]
Great ! Thanks a lot ; )
