### ISSUE TITLE
[mwc-textfield] attribute size does not populate to input element

### ISSUE THREAD

**Issue by masaoliou** [material-components/material-components-web-components#1158]
**Is your feature request related to a problem? Please describe.**
`<mwc-textfield size="5"></mwc-textfield>` does not change the visible width from 20 to 5.

**Describe the solution you'd like**
Implement property `size` that will populate its value to element `input`.

![textfield](https://user-images.githubusercontent.com/696936/79549450-93857400-80c9-11ea-8079-d0b324808a6b.png)
`input`.

**Comment by asyncLiz** [comment]
Thanks for the issue! I'm assuming that the reason you want this attribute is to control the width of the textfield, correct?

https://jsbin.com/civojirepi/1/edit?html,output

I'll add this to our backlog

**Comment by masaoliou** [comment]
> I'm assuming that the reason you want this attribute is to control the width of the textfield, correct?

Yes, I do.

Thank you!
