### ISSUE TITLE
De-duplicate textarea styles

### ISSUE THREAD

**Issue by asyncLiz** [material-components/material-components-web-components#1175]
## Description
Textarea's Sass duplicates textfield's Sass. Instead, it should pull in the stylesheet from `@material/mwc-textfield` so that only one copy of textfield styles are loaded on the page.

```ts
import {styles as textfieldStyles} from '@material/mwc-textfield/mwc-textfield.css.js';
import {styles} from './mwc-textarea.css.js';

@customElement('mwc-textarea')
export class TextArea extends TextAreaBase {
  static styles = [textfieldStyles, styles];
}
```

## Acceptance criteria
Textarea should load base textfield styles from external textfield package's style module.

**Comment by taylor-vann** [comment]
fixed with [1640](https://github.com/material-components/material-components-web-components/pull/1640)
