### ISSUE TITLE
target from elements missing declarative reference

### ISSUE THREAD

**Issue by sashafirsov** [material-components/material-components-web-components#1181]
It is quite inconvenient when for HTML nodes/Web Components there is a need for JS while it could be done in primitive way on HTML level. 

In `mwc-menu` component there is a `anchor` reference to another element which contradicts the declarative nature of HTML components as self-sufficient solution. In HTML such kind of references are usually provided by reference by `for` or `href` attribute which is treated as lookup by ID.
It is understandable that ID meant to be unique and does not work well for auto-generated code. But the way of using JS for relation definition goes against separation of concerns in css/js/html: it belongs to HTML as structure definition layer adding additional burden for HTML developers.

**Proposing to add optional `for` attribute** which would provide ID of referenced element.

If there is a will to fix the lack of classic `for` flexibility, the css selector would be more useful. 
Going further, CSS does  not provide back reference up on dom  tree, which is essential for using HTML as structure. Proper solution should account such back-and-forward selectors. I.e. back-lookup following with usual forward lookup CSS. 

`<mwc-menu for="...li .another-child">`

In sample above `for` attribute looks up up the dom  multiple levels until closest `li` element reached. Than `.another-child` css selector picks element. 

**Alternatives**
custom element for element selection which would populate `anchor` property of menu. It allows to keep the html structure where it belongs - in DOM and allows to make app without engaging custom JS layer.

`<wel-css-query src="#cornerButton" dst="#menu1" dstprop="anchor" ></wel-css-query>`
https://github.com/EPA-WG/web-elements-loader/blob/master/src/wel-css-query.js

**Comment by e111077** [comment]
in this case, javascript-less declarative setup fights with encapsulated modularity. A component should only know about itself and its subtree. By adding `for`, the component would have to traverse its siblings or parent trees. This additionally runs into query selection issues and shadow dom. How far up and how many shadow roots should the querySelector traverse? What if it is slotted in and should actually traverse a slot's `assignedNodes`. This would lead to quite a performance hit as opposed to the user setting the `anchor` property themselves.

Our recommended approach here would be the mediator method where a common parent would mediate this data on menu's behalf. In lit-element it is possible to do the following pattern:

```ts
@customElement('my-element')
export class MyElement extends LitElement {
  @query(#button) buttonElement!: HTMLButtonElement;
  @query(#menu) menuElement!: Menu;
  render () {
    return html`
      <button id="button" @click=${this.menuElement.show}>This is the anchor</button>
      <mwc-menu id="menu" .anchor=${this.buttonElement}></mwc-menu>
    `;
  }
}
```

the `@query` decorator allows for declarative query selection; unfortunately there is not a native html way to do this.

I like your second recommendation more than the first, though, I feel that implementing a generic query selector or packaging one with the component is out of the scope of MWC.

**Comment by sashafirsov** [comment]
@e111077, Sorry you did not want to collect counterarguments and closed the story. IMO without all arguments on hand. 

> A component should only know about itself and its subtree. 

Which is OK, it does not know ahead of time about DOM where it would be injected. It also does not care if developer made a wrong reference, right? It is developer who sets an `anchor` in context where component resides. `for` is just another syntax to achieve same goal: reference the node, only declarative instead of JS.

> This additionally runs into query selection issues and shadow dom.

What issues you foresee? I could not find any. Like none.
> How far up and how many shadow roots should the querySelector traverse? 

 `Node.getRootNode()` method been made for a reason: defining available scope. It would limit "for" selector to scope. Developer also would work in the scope of current container and use relative selector only within. It is not intention of `for` attribute to refer outer scopes( that is subject of `href` BTW ).
The `...` would traverse not more than `Node.getRootNode()` before failing. But usual use case is few levels up matching the complexity of container component. That is way less than using global IDs or global selectors. And even less than selector from rootNode which is current pattern for internal CSS selectors. So it is **more performant**.

> What if it is slotted in and should actually traverse a slot's assignedNodes. This would lead to quite a performance hit as opposed to the user setting the anchor property themselves.

You have same issues with `@query(#button)` so argument of performance is not relevant. Instead of ID it could be any CSS selector which also would be sensitive to slot border.

As for code complexity try to compare your sample with this one:
```javascript
@customElement('my-element')
export class MyElement extends LitElement {
  render () {
    return html`
      <button @click=${this.menuElement.show}>This is the anchor</button>
      <mwc-menu for="... button" ></mwc-menu>
    `;
  }
}
```
It is 3x smaller and simpler: 
* no IDs, making HTML readability simpler, less chances for typo-kind mistakes
* no intermediate variables, which is a just initialization time garbage polluting JS

The primary advantage that developer is focusing on functional side skipping the plumbing coding.
Which I really hope is in scope of MWC :)

**Comment by sashafirsov** [comment]
PS. JS has given a unique AOP ability to extend existing functionality of JS module, so I could mix-in  HTMLElement including MWC components by adding extra attributes support, including proposed one. Have to think about.

**Comment by e111077** [comment]
Heyo, sorry I'm on triage duty and our guidelines are to close proposals we don't immediately see as actionable / assignable and continue conversation while closed and reopen afterwards once it is; we discuss this as a team at a weekly triage meeting. Sorry I didn't notify you at the end of my post.

Just a few clarifications:

> > This additionally runs into query selection issues and shadow dom.

by this I meant that finding a node given a query selector may run into performance issues when it comes to traversing shadow roots (multiple calls to `getRootNode` vs the singular `window.document` most people are used to. Though I see that you clarified later that your proposal is to keep it within the shadow root.

Though there are 2 other points I'd like to make:

`mwc-menu` in its current form occasionally needs to be hoisted to `body`. In cases such as when inside a dialog or non-statically positioned element. See #832. This means that often the anchor is often not immediately query-selectable as their anchors are often in other shadow roots. This means that we will in one form or another need to keep the `anchor` property. And, if we keep the `anchor` property, I feel as if we have a sufficiently-declarative method for achieving `for="..."`'s behavior with LitElement and without adding more code to the menu component itself.

Secondly, the Polymer team tries to stick to the mediator method for component design style and again as this seems to be easily solvable by a mediating parent element.

Your CSS Query CE approach seems to be a great way to solve this without LitElement or starter javascript.

**Comment by sashafirsov** [comment]
Sorry for long communication chain. `for` was not meant as full substitution of `anchor`, rather a complimentary initializer. In simple cases it is enough to use declarative `for` initializer, in other cases like you given or dynamic re-assignment the direct setting of node via `anchor` definitely beneficial.

**Comment by e111077** [comment]
I brought this proposal up to the team, and the decision was that the anchor property provides a sufficient API surface for what Menu needs to do as well as `@query` with LitElement

**Comment by e111077** [comment]
Also there is upcoming shadow dom-related work for the `for` and all of the a11y selectors coming up in the standards world and that we will be keeping a close eye on how that progresses.
