### ISSUE TITLE
lebel on textfield disappear when value is given

### ISSUE THREAD

**Issue by sashafirsov** [material-components/material-components-web-components#1185]
The label is invisible when **value** attribute is given by HTML.

**To Reproduce**
`<mwc-textfield type="number" label="ZZZZ" outlined=""  value="123"></mwc-textfield>
`
**Expected behavior**
"ZZZZ" should be shown on the top of input area.

**Screenshots**
![image](https://user-images.githubusercontent.com/3978089/80152228-29a91680-8570-11ea-9e92-49ff13cc9b2e.png)

**Browser Version (please complete the following information):**
 - Win10
 - chrome
 - Version 81.0.4044.113 (Official Build) (64-bit)

**Comment by dfreedm** [comment]
Hmm, I can't seem to repro this in a jsbin: https://jsbin.com/niqitezaxo/edit?html,output.

Can you provide a live demo link that shows this behavior?

**Comment by asyncLiz** [comment]
Are you rendering the textfield inside a dialog or other container that is initially invisible? If so you may be experiencing the zero-width label bug (#812)

Example: https://jsbin.com/gagapaheju/1/edit?html,output

The solution is to wait until the container/dialog is opened before rendering the textfield, or call `.layout()` on the textfield after the container/dialog has opened.

**Comment by sashafirsov** [comment]
@asyncLiz , your assumption is correct. HTML is loaded dynamically. The `layout()` call does not make any sense as there is no JS at all. Live demo will follow.

**Comment by asyncLiz** [comment]
This is a problem with the implementation of textfield's floating label. When inside a container that is initially hidden (`display: none` for example), the container has an inherit offsetWidth of zero and the label cannot determine its width properly.

The textfield does not know when to check again, which is why it's necessary to call `.layout()` on the textfield or delay rendering the textfield until the container is fully visible.

**Comment by sashafirsov** [comment]
@asyncLiz , there are several methods to solve the bug. From pure CSS responsible for positioning and visibility of label to add `if( this.value ) this.layout()` to the end of rendering cycle( not sure how it is done in Lit, but I am doing such things in `connectedCallback()`  ).
IMO JS is not a place for solving layout UX, that is CSS responsibility.

**Comment by sashafirsov** [comment]
@dfreedm , here is live sample, look into "menu" section:
https://cdn.xml4jquery.com/web-elements-loader/build/esm-unbundled/demo/material-web-components-demo.html

**Comment by sashafirsov** [comment]
As I found the initial value also breaks label in other elements like `mwc-select`

**Comment by asyncLiz** [comment]
There's a little more involved to the issue than just a debate on CSS vs JS to solve all the necessary requirements. Ultimately this is an upstream issue with MDC.

Closing since we're already tracking a fix in #812.
