### ISSUE TITLE
[mwc-list] Safari webpage crash when using <slot> + <div slot="graphic">

### ISSUE THREAD

**Issue by fgirardey** [material-components/material-components-web-components#1222]
**Describe the bug**

When using directly the `<slot>` element inside the light dom + using a `<div slot="graphic">` it makes Safari crash.

At first I thought about a Safari bug because it works fine with Chrome but it seems to happen with the `slot="graphic"` only.

**To Reproduce**
1. Go to https://typescript-mwc-list-safari-slot-bug.stackblitz.io with Safari ([stackblitz project](https://stackblitz.com/edit/typescript-mwc-list-safari-slot-bug))
2. See Safari crashes
3. Remove the second `<mwc-list-item>` in the stackblitz
4. See Safari doesn't crashes anymore

**Expected behavior**

It should not make the page crash like that.

**Browser Version (please complete the following information):**
 - OS: MacOS 10.15.4
 - Browser: Safari
 - Version: 13.1 (15609.1.20.111.8) and Release 105 (Safari 13.2, WebKit 15610.1.10)

**Additional context**

Removing the `<slot>` does fix the issue but I originally took the example from the [mwc-list example page](https://github.com/material-components/material-components-web-components/tree/master/packages/list#item-noninteractive).

**Comment by fgirardey** [comment]
I just tried to set the `twoline` property on the list item that was making Safari crash and it now works. https://typescript-mwc-list-safari-slot-bug-qghurr.stackblitz.io ([stackblitz project](https://stackblitz.com/edit/typescript-mwc-list-safari-slot-bug-qghurr))

My guess is that Safari doesn't like `<slot>` distributed in a `<slot>` at the top level of a shadow host, i noticed the `twoline` attribute adds a wrapper around the default `<slot>` of the `<mwc-list-item>` .

Maybe we should issue a bug to Webkit Bugzilla and meanwhile update the documentation?

**Comment by e111077** [comment]
woah that's gnarly!

**Comment by e111077** [comment]
Interesting observation, but on the note about top-level slot:

It actually is already wrapped. A single-line renders like so

```html
<mwc-list-item graphic="icon">
  # shadow root
    <span class="mdc-list-item__graphic material-icons">
      <slot name="graphic"></slot>
    </span>
    <span class="mdc-list-item__text">
      <slot></slot>
    </span>
  # /shadow root
  <slot></slot>
  <div slot="graphic>edit</div>
</mwc-list-item>
```

so the slot is already not at root

**Comment by e111077** [comment]
may not be exactly what you want, but wrapping the slot with default content inside of a `<span><slot>default</slot></span>` seems to prevent the crash. This is indeed a WebKit bug and filed it here:

https://bugs.webkit.org/show_bug.cgi?id=211159

Closing this issue since it's not inherent to this library and has a workaround. Will reopen if we get a significant amount of reports

**Comment by fgirardey** [comment]
Well, you perfectly understood my observations that were totally wrong 😂 you are right, I am sorry I went too fast in conclusions.

Thank you for taking the time to issue the bug to Webkit.

Actually I worked around by simply removed the `<slot>` in the light dom, i just copied and pasted the [mwc-list example](https://github.com/material-components/material-components-web-components/tree/master/packages/list#item-noninteractive) that uses `<slot>` and I don't think I need it.

Can I suggest to update the mwc-list documentation to remove the `<slot>` usage? Or is it really required? (I bet it does, just curious to know why)

**Comment by e111077** [comment]
update: Apple seems to have picked up the issue

**Comment by dfreedm** [comment]
Issue seems to be fixed in the WebKit bug tracker.
I guess it will be in the next version of Safari Technology Preview.
https://bugs.webkit.org/show_bug.cgi?id=211159#c4

**Comment by fgirardey** [comment]
Hell yeah! Thanks again guys 😇
