### ISSUE TITLE
Question: How to use components in a contrast color

### ISSUE THREAD

**Issue by Jack-Works** [material-components/material-components-web-components#1224]
Text field has a dark border and color.
![image](https://user-images.githubusercontent.com/5390719/80303742-a8a68500-87e4-11ea-8d02-b0acdb7d2abe.png)

If I want to use it in a App Bar, must I set all those CSS custom variables to get this?
![image](https://user-images.githubusercontent.com/5390719/80303789-fc18d300-87e4-11ea-89b4-4938f29c83ad.png)

```css
      background: rgba(255, 255, 255, 0.2);
      --mdc-text-field-filled-border-radius: 4px;
      border-radius: var(--mdc-text-field-filled-border-radius);
      --mdc-text-field-idle-line-color: rgba(255, 255, 255, 0.4);
      --mdc-theme-primary: rgba(255, 255, 255, 0.6);
      --mdc-text-field-idle-line-color: rgba(255, 255, 255, 0.6);
      --mdc-text-field-hover-line-color: white;
      --mdc-text-field-disabled-line-color: white;
      --mdc-text-field-outlined-idle-border-color: white;
      --mdc-text-field-outlined-hover-border-color: white;
      --mdc-text-field-outlined-disabled-border-color: white;
      --mdc-text-field-ink-color: white;
      --mdc-text-field-label-ink-color: white;
      --mdc-text-field-disabled-ink-color: white;
```

**Comment by asyncLiz** [comment]
At the moment yes, this is what you need to do to change the theme to achieve a "dark mode".

We're investigating a theming system in #1072 that will make things easier so that it's a bit easier to write light/dark themes for your components.
