### ISSUE TITLE
Decide which properties should be reflected

### ISSUE THREAD

**Issue by azakus** [material-components/material-components-web-components#123]
It seems likely that at least _some_ of the properties of the MWC components should be reflected to attributes.

Most likely candidates are boolean properties like `disabled`.
Least likely candidates are stringy properties like `value`.

**Comment by ZempTime** [comment]
Internally we've been using a modified version of `mwc-textfield`. Here are the properties thus far we've reflected:
```
      outlined: { type: Boolean, reflect: true },
      disabled: { type: Boolean, reflect: true },
      required: { type: Boolean, reflect: true },
      type: { type: String, reflect: true },
      pattern: { type: String, reflect: true },
      maxlength: { type: Number, reflect: true },
      min: { type: Number, reflect: true },
      max: { type: Number, reflect: true },
      touched: { type: Boolean, reflect: true },
```
