### ISSUE TITLE
npm run bootstrap fails on Windows 10

### ISSUE THREAD

**Issue by kr05** [material-components/material-components-web-components#125]
Initially, the bootstrap-unreleased.sh script was refusing to run altogether, but that was fixed with the following npm configuration change.

```
npm config set script-shell "C:\\Program Files\\Git\\bin\\bash.exe
```

Unfortunately, I get a different error now. Running "npm run bootstrap" throws with the following error:

```
lerna success clean finished
module.js:550
    throw err;
    ^

eposmaterial-components-web-components/packages/base/package.json'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at [eval]:1:13
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at Object.runInThisContext (vm.js:139:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:653:30)
    at evalScript (bootstrap_node.js:479:27)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! material-components-web-components@ bootstrap: `npm install && ./scripts/bootstrap-unreleased.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the material-components-web-components@ bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kevin\AppData\Roaming\npm-cache\_logs\2018-10-02T20_43_37_181Z-debug.log
```

Any ideas for resolving this?

**Comment by azakus** [comment]
Yeah, this script is super hacky, as the default behavior of `lerna bootstrap --hoist` doesn't do what we want.

I think we can fix this by using yarn workspace integration with lerna.

**Comment by kr05** [comment]
In the meantime, I was able to work around this problem by enabling the Windows Subsystem for Linux and installing a Linux distro from the Windows Store. Now I simply run the npm run commands from within the linux command line and everything works as expected.

**Comment by Biggisb** [comment]
i am still having isuess on win10
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! material-components-web-components@ bootstrap: `npm install && ./scripts/bootstrap.sh && npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the material-components-web-components@ bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.


any help?
