### ISSUE TITLE
mwc-slider binding shows incorrect thumb position

### ISSUE THREAD

**Issue by mahdiridho** [material-components/material-components-web-components#1252]
**Describe the bug**
I'm implementing mwc-slider on my lit-element library. All work well till I applied a hidden scenario (show/hide element). On the first time, I want to hide the mwc-slider and it will be appear once login succeed.

Well, now I can see the slider thumb not working well. Every bind the value from other event, the slider value is correct but the slider thumb not move.

**To Reproduce**
I created a demo repo on https://github.com/mahdiridho/mwc-slider-binding-issue. Just follow the readme to reproduce the issue

**Expected behavior**
My current solution is show the mwc-slider then hide it on the first lifecycle like so :

```
constructor() {
   super();
   this.view = true;
}

firstUpdated() {
   this.view = false;
}

```

I expect we shouldn't need to do this trick

**Screenshots**
![Screenshot from 2020-05-04 22-46-48](https://user-images.githubusercontent.com/10230037/80985287-37f10f80-8e59-11ea-88ce-dc8dae375e0b.png)

**Browser Version (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser [Chrome, Firefox]
 - Version [81, 75]

**Comment by asyncLiz** [comment]
Thanks for the issue! Can you try adding the following to your LitElement class?

```js
updated(changed) {
  if (changed.has('view') {
    this.slider.layout();
  }
}
```

This may be related to #812 and other bugs, where some issues can occur when rendering components inside a hidden container. The workaround is to call `.layout()` on them after the container is rendered visible. The `updated()` lifecycle should be a safe place to do that in LitElement.

**Comment by mahdiridho** [comment]
@asyncLiz well, following your solution I got rid my previous soluton and changed my element class like so :

```
  updated(changed) {
    super.updated(changed)
    this.slider.layout();
  }

```
It's fixed now, thanks

**Comment by asyncLiz** [comment]
You can find the documentation for the method here: https://github.com/material-components/material-components-web-components/tree/master/packages/slider#methods
