### ISSUE TITLE
mwc-textfield: problem with focus

### ISSUE THREAD

**Issue by aegeavaz** [material-components/material-components-web-components#1257]
Hi...

I'm calling the focus method of the element:

document.getElementById("myTextField").focus()

And I have three problems:

1) The first time it is executed, the component gets focus correctly, but if I click on other elements, it doesn't blur.
2) Only works the first time. The next executions don't do anything.
3) When the component gets focus, the input inside doesn't get the focus (i'm registering a focus event in the input, and it is not fired).

is this the normal behaviour of the focus method?

Thank you.

**Comment by asyncLiz** [comment]
I'm not able to reproduce this issue with this link that tries to follow your problem: https://jsbin.com/ditakacihe/edit?html,output

I'm able to focus the textfield multiple times, it blurs correctly when I focus the other input (both with keyboard and mouse), and piercing the shadow root reveals that the inner input is receiving focus events.

Can you add a playground link that reproduces the problem?

**Comment by aegeavaz** [comment]
Hi... thanks for your answer.

I think the problem comes when you try to focus it after enable it.

Look this examples: https://jsbin.com/bagadebolu/edit?html,output

If you click, the textfield is enabled, it is focused (styled), but the
input doesn't get focus, and if you click on the input outside, the
textfield doesn't blur.

Regards.

**Comment by asyncLiz** [comment]
When you set `disabled = false`, you need to let the element update itself before calling focus. This is because the element updates asynchronously when properties change. You can do that by awaiting the `updateComplete` promise.

https://jsbin.com/ribelaledi/1/edit?html,output

**Comment by aegeavaz** [comment]
Now makes sense and its working fine.

I couldn't find any reference about that promise in any documentation.

Thank you very much for the help.
Regards.
