### ISSUE TITLE
NotSupportedError: CustomElementRegistry.define: 'mwc-notched-outline' has already been defined as a custom element

### ISSUE THREAD

**Issue by jorgeme0996** [material-components/material-components-web-components#1264]
Error when importing '@material/mwc-select'

**Comment by asyncLiz** [comment]
This sounds like you have duplicate versions of notched-outline installed. This can happen when you have different versions of mwc elements installed (such as a different version of textfield vs select).

You can run `npm ls @material/mwc-notched-outline` that will show you where the duplicates are.

Updating all elements to the same version will fix the issue. Let us know if you have any questions!

**Comment by jorgeme0996** [comment]
Issue resolved. Thanks!!!
