### ISSUE TITLE
Select is hiding parts of itself.

### ISSUE THREAD

**Issue by milesje** [material-components/material-components-web-components#1274]
**Describe the bug**
When using a mwc-select inside a mwc-dialog and the select is opened, the actual outlined field is removed causing the other elements on the dialog to shift around.

**Expected behavior**
I would expect the element not to be removed so that things do not move.

**Screenshots**
![image](https://user-images.githubusercontent.com/537359/81258518-7a525200-8ffb-11ea-8e74-db447d0639b1.png)
![image](https://user-images.githubusercontent.com/537359/81258545-89390480-8ffb-11ea-94f0-bc4158cd4d01.png)

**Browser Version (please complete the following information):**
 - OS: MacOSX Catalina
 - Browser: Edge (Chromium)
 - Version: 81.0.416.68 (Official build) (64-bit)

**Additional context**
I have not tried this outside of a mwc-dialog so I'm not sure if it this behavior is limited to only while inside of a mwc-dialog.

**Comment by asyncLiz** [comment]
Thanks for the issue! At the moment select does not work properly inside a dialog. You can track #832 for updates.

Closing as a duplicate.
