### ISSUE TITLE
mwc-select: margin around helper text making input too tall

### ISSUE THREAD

**Issue by aarondrabeck** [material-components/material-components-web-components#1275]
**Screenshots**
![image](https://user-images.githubusercontent.com/9825025/81320406-5f5cfd80-904e-11ea-92c5-c03b9534bc83.png)

**Browser Version (please complete the following information):**
All

**Comment by asyncLiz** [comment]
Confirmed on the demos. It does not look like any of the MDC select helper text core styles are applying. Notably [this section](https://github.com/material-components/material-components-web/blob/f83e00898fb57e49e38ef59b3458df4525332302/packages/mdc-select/helper-text/_mixins.scss#L34-L41) which sets the default `<p>` margin to 0 and adds baseline and typography.

It looks like [we're importing the helper text styles](https://github.com/material-components/material-components-web-components/blob/ac065e36b80ed9d91f9c93ebe59279424da78ce4/packages/select/src/mwc-select.scss#L19), and that import should apply core-styles.

Might need to do a bit more digging.
