### ISSUE TITLE
[Drawer] Change width custom property to use Sass mixin

### ISSUE THREAD

**Issue by e111077** [material-components/material-components-web-components#1281]
**Is your feature request related to a problem? Please describe.**

The width of the drawer cannot be resized.

**Describe the solution you'd like**

set a css custom property to resize drawer e.g. `--mdc-drawer-width: 400px`;

**Describe alternatives you've considered**

Width of aside grows to content width

**Comment by e111077** [comment]
kinda makes it useless for certain cases

**Comment by asyncLiz** [comment]
This would be a good use case to update the [`width()`](https://github.com/material-components/material-components-web/blob/e844443878b9711a306e72b951c7ea931b17d837/packages/mdc-drawer/_mixins.scss#L393-L405) drawer mixin to support custom properties.

**Comment by maartenst** [comment]
the weird thing is this is documented in the docs, maybe remove that until this works?

**Comment by asyncLiz** [comment]
@maartenst does the custom property not work in the `@material/mwc-drawer@canary` version? It was added a couple weeks ago.

@e111077 looks like we had a duplicate issue for this #1306. I'm going to keep this issue open though, because I still believe this could be cleaned up a bit by switching to the width mixin.

**Comment by ronnyroeller** [comment]
> the weird thing is this is documented in the docs, maybe remove that until this works?

I just stumbled over the same issue. Indeed, would be great to remove from docs to avoid confusion.

**Comment by asyncLiz** [comment]
@ronnyroeller can you show an example on the canary version where it is not working?

Remember that docs on the master branch in this GitHub repo are for _canary_. If you're looking for the docs for a specific version, you can check npm's readme for that version, or navigate to the version tag in GitHub.

At time of writing, the latest version is v0.15.0, which does _not_ include the new width property described in the [unreleased](https://github.com/material-components/material-components-web-components/blob/master/CHANGELOG.md#unreleased) section of our changelog.

Canary: https://github.com/material-components/material-components-web-components/tree/master/packages/drawer
v0.15.0: https://github.com/material-components/material-components-web-components/tree/v0.15.0/packages/drawer

https://www.npmjs.com/package/@material/mwc-drawer (at time of writing) is v0.15.0 and does not include the width property either.

**Comment by ronnyroeller** [comment]
@asyncLiz Thanks for clarifying! Indeed, I had used 0.15.0. What confused me was that this ticket is marked as opened - so I had wrongly assumed that it wasn't fixed in master.

**Comment by asyncLiz** [comment]
Updated in https://github.com/material-components/material-components-web-components/pull/1420
