### ISSUE TITLE
mwc-formfield text color

### ISSUE THREAD

**Issue by nicolasr75** [material-components/material-components-web-components#1300]
I have just tried the basic examples and am now trying to give my example page a theme.
I follow the specification in the (preview) theming guide but I can't figure out how to change the text color of an mwc-formfield. 

The description page of mwc-formfield says there are no custom CSS properties so I thought its text color would be derived from the global properties which I set to this:

		--mdc-theme-primary: blue;
		--mdc-theme-secondary: yellow;
		--mdc-theme-surface: red;
		--mdc-theme-background: pink;
		--mdc-theme-on-primary: green;
		--mdc-theme-on-surface: lime;
		--mdc-theme-on-secondary: white;

which affects other components like button, textfield and dialog but nothing changes the text color of mwc-formfield.
Do I miss something or is this not yet supported?

**Comment by asyncLiz** [comment]
We're still working on documenting some of the more subtle text-related theming colors, but right now the one you want is `--mdc-theme-text-primary-on-background` 🙂

**Comment by nicolasr75** [comment]
Perfect, thanks!
