### ISSUE TITLE
Stencil got error duplicate identifier when import @material/mwc-tab lib

### ISSUE THREAD

**Issue by nqhy** [material-components/material-components-web-components#1322]
**Describe the bug**
When i import ```@material/mwc-tab-bar``` and ```@material/mwc-tab```

I got this error (duplicate identifier and do not know why import ```@materila/mwc-button``` i got no error but when import two libs above i face the below issue)

**To Reproduce**
```I create the web component using stencil lib```

**Expected behavior**
It supposed to be worked well when import @marterial lib

**Screenshots**
<img width="427" alt="Screen Shot 2020-05-18 at 10 40 23" src="https://user-images.githubusercontent.com/40130936/82172305-fd28b600-98f3-11ea-8bfa-4836de5ffcb1.png">
<img width="706" alt="Screen Shot 2020-05-18 at 10 40 56" src="https://user-images.githubusercontent.com/40130936/82172332-103b8600-98f4-11ea-9d9c-9e6dfef17cad.png">

**Browser Version (please complete the following information):**
 - OS: [MAC OS]
 - Browser [e.g. chrome]

**Additional context**

**Comment by asyncLiz** [comment]
Looks like you got the issue resolved, but just in case (or if someone else runs into the same problem), the sub `node_modules/` folder usually points to conflicting versions (for example, `@material/tab` being on v6 and `@material/tab-bar` being on v7).

Aligning the components to the same version is a sure way to fix it. You can also rely on installing the `material-components-web` dependency, which will install everything under the same version for you.
