### ISSUE TITLE
Mwc-menu - inconsistent import of component

### ISSUE THREAD

**Issue by yinonov** [material-components/material-components-web-components#1323]
**Describe the bug**
[mwc docs](https://github.com/material-components/material-components-web-components/tree/master/packages/list#basic) in general specify that each required component should be imported by the consumer. so [here](https://github.com/material-components/material-components-web-components/tree/master/packages/list#basic) even `mwc-list` isn’t importing `mwc-list-item` by itself right? 
**BUT** `mwc-menu-base.ts` imports `mwc-list` right at the top of itself and it's not even its direct child component (it is the list's child).
Is there any reason why this isn’t the case with the menu?

_mwc-menu-base.ts_
![image](https://user-images.githubusercontent.com/15140652/82180181-b41f3480-98e8-11ea-8d6d-d1f3beada834.png)

_mwc docs_
![image](https://user-images.githubusercontent.com/15140652/82180097-7e7a4b80-98e8-11ea-9e1d-6668948c7540.png)

**Comment by e111077** [comment]
Heya, you have the concept right; the user should be importing any dependencies they use explicitly. So to reiterate, list does not use list-item in its shadow DOM so it does not import list-item and the user must do so. The same goes for menu.

Though, menu uses menu-surface as well as list:

https://github.com/material-components/material-components-web-components/blob/master/packages/menu/src/mwc-menu-base.ts#L151

I think the confusion here might be that `@material/mwc-list` does not actually import all the files in the `mwc-list` package but rather what `package.json`'s `main:` / `module:` field points to:

https://github.com/material-components/material-components-web-components/blob/master/packages/list/package.json#L5

in this case it only imports `mwc-list` and not `mwc-list-item`.

Does this answer your question? If not please respond and I can reopen

**Comment by yinonov** [comment]
sorry, didn't catch that, yes it does 👍
