### ISSUE TITLE
MWC-Button classMap returns function not string

### ISSUE THREAD

**Issue by ryanwhite04** [material-components/material-components-web-components#1378]
**Describe the bug**
The MWC-Button Component calls `classMap` on `classes` which should return a string, but the `classMap` function returns a function.

**To Reproduce**
1. `import "@material/mwc-button@^0.15.0"`
2. Use `<mwc-button></mwc-button>`
3. Inspect `<mwc-button></mwc-button>` in elements panel.
4. Inspect the class of the `<button>` element within the shadow root

```html
<button id="button" class="mdc-button (part) => {
    if (!(part instanceof AttributePart) || (part instanceof PropertyPart) ||
        part.committer.name !== 'class' || part.committer.parts.length > 1) {
        throw new Error('The `classMap` directive must be used in the `class` attribute ' +
            'and must be the only part in the attribute.');
    }
    const { committer } = part;
    const { element } = committer;
    let previousClasses = previousClassesCache.get(part);
    if (previousClasses === undefined) {
        // Write static classes once
        // Use setAttribute() because className isn't a string on SVG elements
        element.setAttribute('class', committer.strings.join(' '));
        previousClassesCache.set(part, previousClasses = new Set());
    }
    const classList = (element.classList || new ClassList(element));
    // Remove old classes that no longer apply
    // We use forEach() instead of for-of so that re don't require down-level
    // iteration.
    previousClasses.forEach((name) => {
        if (!(name in classInfo)) {
            classList.remove(name);
            previousClasses.delete(name);
        }
    });
    // Add or remove classes based on their classMap value
    for (const name in classInfo) {
        const value = classInfo[name];
        if (value != previousClasses.has(name)) {
            // We explicitly want a loose truthy check of `value` because it seems
            // more convenient that '' and 0 are skipped.
            if (value) {
                classList.add(name);
                previousClasses.add(name);
            }
            else {
                classList.remove(name);
                previousClasses.delete(name);
            }
        }
    }
    if (typeof classList.commit === 'function') {
        classList.commit();
    }
}" aria-label="">
        <!----><!---->
        <span class="leading-icon">
          <slot name="icon">
            
    </slot>
</span>
<span class="mdc-button__label"><!----><!----></span>
<slot></slot>
<span class="trailing-icon">
    <slot name="trailingIcon">
    
    </slot>
</span>
</button>
```

**Expected behavior**
The class of the button within the shadow root of the mwc-button element should be a combination of `mdc-button` and the following:
- `mdc-button--raised`
- `mdc-button--unelevated`
- `mdc-button--outlined`
- `mdc-button--dense`

**Code**

The classMap function is called in `mwc-button-base.ts`

https://github.com/material-components/material-components-web-components/blob/0ba7b095207c5fb6a9f150a0849782e5d195a5f6/packages/button/src/mwc-button-base.ts#L98

and the classMap function is defined in the lit-element directive for classmaps

[`export const classMap = directive((classInfo: ClassInfo) => (part: Part) => {`](https://github.com/Polymer/lit-html/blob/abcb1664d2ff262471479e25d59769a583ee9d8c/src/directives/class-map.ts#L68)

**Browser Version (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 83

**Additional context**
I'm importing the element directly from pika.
The complete html file is 
```html
<!DOCTYPE html>
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Material+Icons&display=block" rel="stylesheet">
  </head>
  <body>
    <script type="module" src="https://cdn.pika.dev/@material/mwc-button@^0.15.0"></script>
    <mwc-button>Button Label</mwc-button>
  </body>
</html>
```

**Comment by ryanwhite04** [comment]
Looking at the documentation for the classMap directive on the [lit-html guide](https://lit-html.polymer-project.org/guide/template-reference#classmap) is looks like this MWC-Button is using the classMap directive correctly, and the issue is with [lit-html](https://github.com/polymer/lit-html)

**Comment by ryanwhite04** [comment]
If I load the file from [unpkg](https://unpkg.com/@material/mwc-button/mwc-button.js?module) instead of pika, there is no longer an issue

```html
<script type="module" src="https://unpkg.com/@material/mwc-button/mwc-button.js?module"></script>
```

So i'm going to close this and assume it's just a weird pika thing.

**Comment by hunterloftis** [comment]
I'm seeing this exact behavior with mwc installed and imported into a TypeScript project. I suspect it's an issue with my build configuration (TS + RollUp).

This is the sort of thing that's difficult to reproduce (if I knew what mismatched config caused it, I'd just fix it). Sharing the tsconfig here in case anyone has suggestions:

```json
{
    "compilerOptions": {
        "allowJs": true,
        "target": "es6",
        "experimentalDecorators": true,
        "moduleResolution": "node",
        "allowSyntheticDefaultImports": true,
        "resolveJsonModule": true
    }
}
```

and rollup.config.js:

```js
const config = {
  input: 'client/table.ts',
  output: {
    dir: 'dist/client/assets',
    format: 'es',
    sourcemap: true,
  },
  plugins: [
    typescript({
      tsconfig: 'client/tsconfig.json'
    }),
    minifyHTML(),
    copy(copyConfig),
    resolve(),
    // terser(),
  ],
  preserveEntrySignatures: false,
}
```

**Comment by hunterloftis** [comment]
For anyone who runs into this later, this comment seems to be in the right direction: https://github.com/material-components/material-components-web-components/issues/851#issuecomment-586997532

(I see two versions of lit-html on the page)

**Comment by hunterloftis** [comment]
For me, this ended up being an npm vs yarn issue.

Yarn was installing multiple versions of lit-html, and claiming that it automatically dedupes:

```
# yarn why lit-html
yarn why v1.22.5
[1/4] Why do we have the module "lit-html"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "lit-html@1.3.0"
info Has been hoisted to "lit-html"
info Reasons this module exists
   - Hoisted from "@material#mwc-top-app-bar#lit-html"
   - Hoisted from "@material#mwc-icon-button#@material#mwc-ripple#lit-html"
info Disk size without dependencies: "1.23MB"
info Disk size with unique dependencies: "1.23MB"
info Disk size with transitive dependencies: "1.23MB"
info Number of shared dependencies: 0
=> Found "lit-element#lit-html@1.2.1"
info This module exists because "@material#mwc-icon-button#lit-element" depends on it.
info Disk size without dependencies: "2.16MB"
info Disk size with unique dependencies: "2.16MB"
info Disk size with transitive dependencies: "2.16MB"
info Number of shared dependencies: 0
Done in 0.43s.
```

However, `rm -rf node_modules && npm install && npm dedupe` led to a working project, fixing the above issue. 🤦
