### ISSUE TITLE
Dropdown causes text to overlap with 508 compliance

### ISSUE THREAD

**Issue by dman777** [material-components/material-components-web-components#1387]
**Describe the bug**
Tabbing in, selecting first item without return, and then tabbing out of dropdown causes text to overlap 

**To Reproduce**
1. Go to [demo site](https://material-components.github.io/material-components-web-components/demos/menu/)
2. Tab into the dropdown that contains 'menu corner'.
3. Use down arrow to select first entry but do not hit return
4. Tab out of that component and you will see the below:

![image](https://user-images.githubusercontent.com/887815/83545256-9515ca80-a4c4-11ea-8c32-82a9cdedca28.png)

**Comment by asyncLiz** [comment]
Note that issue does not appear to happen with MDC: https://jsbin.com/gexiposano/edit?html,output
