### ISSUE TITLE
[Tutorial] Getting Started with Rollup

### ISSUE THREAD

**Issue by aress31** [material-components/material-components-web-components#1422]
**Is your feature request related to a problem? Please describe.**
I have watched the great talk from this lady at Google - https://www.youtube.com/watch?v=we3lLo-UFtk - and it really made me want to spend some time researching `web components` and more specifically how to migrate my `React based PWA` to a `lithtml` and `litelement`, as this talk is from 2018 many suggested repository to quickly set up a new projects have been superseded.

Right now, the most popular tool to quickly setup a PWA enabled project designed for web components is `Open WC` - https://github.com/open-wc/open-wc - when scaffolding an application project `Open WC` defaults to using `Rollup`. I have posted many tickets over the past last days about `Rollup` and `SASS` as `MWC` is relying on `SASS`, e.g. https://github.com/open-wc/open-wc/issues/1704, https://github.com/open-wc/open-wc/issues/1704, etc.

**Describe the solution you'd like**
The official Google documentation describe how to get started with `webpack` - https://material.io/develop/web/docs/getting-started/ - but not with `Rollup/Parcel` which are two big actor of the JavaScript world. What I would like is Google spending more time working on the documentation, specifically how to quickly get started with `open wc/rollup` and `MWC`.

Adding documentation (the more the merrier) about tasks that might seem basics or trivial for professional developer but which are not for enthusiasts (e.g. how to set up `SASS` for `Rollup`) would give the confidence to more people for switching/migrating their current projects to `MWC`.

**Describe alternatives you've considered**
More documentation about Open WC/Rollup setups.

**Additional context**

**Comment by e111077** [comment]
Heya, I hear your frustrations and I have a lot of the same ones as you do over bundlers like rollup, webpack, and parcel, and oh gosh wait until you have to deal with Babel documentation!

Unfortunately, I think it's out of the scope of MWC as it is a component library where we only require that the library is compatible with the bundlers and not necessarily rely on them.

I think this is an issue that is better filed on [Polymer/lit-element](https://github.com/polymer/lit-element), but unfortunately the polymer team right now is focusing on element-development experience and less app-development. We will eventually get there, but we unfortunately have more-pressing priorities right now.

Though, you should not need to run rollup to compile sass on MWC components. In our [NPM distribution](https://unpkg.com/browse/@material/mwc-button/), you will see that we do this compilation step for you and export a `mwc-component-name.css.js` for you.

The only thing you'll need rollup for MWC is to either bundle your components into your application or if you are not bundling, you'll need it to resolve the non-absolute or non-relative imports.

I'm going to close this issue, but you should still be able to comment if you have any further questions

**Comment by aress31** [comment]
@e111077 thanks for the reply, on the official `Material Web Component` documentation, on the `Getting Started` section, instructions are given to set up the environment with `Webpack`, my suggestion here would be to expand these instructions to cover `Rollup` and `Parcel` as well.

The problem with web components is the `Shadow DOM`, preventing the definition of a global CSS theme style and import it in the index to have the style propagated to all the children. Therefore, we must import the component styles in each component that we create, this approach is very cumbersome, that is why I believe the Material Team went for the SASS approach for global theme definition but unfortunately the documentation is a bit thin on this matter - for `Rollup` and `Parcel` at least.

I don not believe that this is outside the scope of this library, since it is a pre-requiste to get the library work.

**Comment by asyncLiz** [comment]
Keep in mind that while our upstream MDC library _does_ require Sass at runtime, and therefore a build system for your dev environment like Webpack or Rollup, this library does not.

While MWC is built with Sass, at runtime the end-user does not need Sass to use or customize MWC like they would with MDC; Webpack/Rollup are not pre-requisites, just an encouragement for production-ready apps!

If that changes in the future though, I'm sure we'll include documentation on how to set up your dev environment for all the required MWC build tools.

Perhaps a better question might be what process are you going through right now that requires you to use Sass with MWC? Are you trying to build the components from source in your app instead of using the built distributed JS files? Maybe that's the root of the problem.

**Comment by aress31** [comment]
@asyncLiz, I would be really grateful, if you could give me a bit of help on how to get started with my project - I am not a career front end developer just a hobbyist.

This my current setup, resulting in unstyled Material web components being displayed - I bootstrapped this project with Open WC, including TypeScript, Linting and Build with Rollup:

This is the content of `index.html`:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <--- SNIP --->
    <!-- import Normalize for better cross-browser consistency -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css"
    />
    <!-- import Roboto from Google Fonts -->
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700"
    />
    <!-- import Material Icons from Google Fonts -->
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/icon?family=Material+Icons"
    />
  </head>
  <body>
    <my-app></my-app>
    <script type="module" src="./out-tsc/src/my-app.js"></script>
  </body>
</html>
```

This is the content of `my-app.ts` file:
```ts
import { css, customElement, html, LitElement, property } from 'lit-element';
import { Logo } from './assets/logo.js';
import './layouts/header.js';

@customElement('my-app')
export class App extends LitElement {
  static styles = css``;

  render() {
    return html`
      <my-header></my-header>
    `;
  }
}
```

This is the content of `header.ts` file:
```ts
import '@material/top-app-bar';
import { css, customElement, html, LitElement, property } from 'lit-element';
// import style from '../styles/index.scss'; is this what I should be doing?
// const sheet = new CSSStyleSheet(style); is this what I should be doing?

@customElement('my-header')
export class Header extends LitElement {
  static styles = css`
    <--- I do not know how to import my "_common.scss" - which contains the application theme - 
            style in there
    --->
    <--- I do not know how to import the Material UI mdc-top-app-bar default style in there 
            resulting in un-styled common being displayed
     --->
  `;

  render() {
    return html`<header class="mdc-top-app-bar">
      <div class="mdc-top-app-bar__row">
        <section
          class="mdc-top-app-bar__section mdc-top-app-bar__section--align-start"
        >
          <button
            class="material-icons mdc-top-app-bar__navigation-icon mdc-icon-button"
            aria-label="Open navigation menu"
          >
            menu
          </button>
          <span class="mdc-top-app-bar__title">Page title</span>
        </section>
        <section
          class="mdc-top-app-bar__section mdc-top-app-bar__section--align-end"
          role="toolbar"
        >
          <button
            class="material-icons mdc-top-app-bar__action-item mdc-icon-button"
            aria-label="Favorite"
          >
            favorite
          </button>
          <button
            class="material-icons mdc-top-app-bar__action-item mdc-icon-button"
            aria-label="Search"
          >
            search
          </button>
          <button
            class="material-icons mdc-top-app-bar__action-item mdc-icon-button"
            aria-label="Options"
          >
            more_vert
          </button>
        </section>
      </div>
    </header>`;
  }
}
```

This is content of my `rollup.config.js` file:
```js
// use createSpaConfig for bundling a Single Page App
import { createSpaConfig } from '@open-wc/building-rollup';
import autoprefixer from 'autoprefixer';
import cssnano from 'cssnano';
import merge from 'deepmerge';
import postcss from 'postcss';
import sass from 'rollup-plugin-sass';

// use createBasicConfig to do regular JS to JS bundling
// import { createBasicConfig } from '@open-wc/building-rollup';

const baseConfig = createSpaConfig({
  // use the outputdir option to modify where files are output
  // outputDir: 'dist',

  // if you need to support older browsers, such as IE11, set the legacyBuild
  // option to generate an additional build just for this browser
  // legacyBuild: true,

  // development mode creates a non-minified build for debugging or development
  developmentMode: process.env.ROLLUP_WATCH === 'true',

  // set to true to inject the service worker registration into your index.html
  injectServiceWorker: false,
});

export default merge(baseConfig, {
  // if you use createSpaConfig, you can use your index.html as entrypoint,
  // any <script type="module"> inside will be bundled by rollup
  input: './index.html',

  // alternatively, you can use your JS as entrypoint for rollup and
  // optionally set a HTML template manually
  // input: './app.js',

  plugins: [
    sass({
      processor: css =>
        postcss([autoprefixer, cssnano])
          .process(css)
          .then(result => result.css),
      // Write all styles to the bundle destination where .js is replaced by .css
      output: true,
    }),
  ],
});
```

Unrelated question: Does anyone know how to turn off the `Shadow Dom` on an `LitElement` component written with `TypeScript`?

**Comment by asyncLiz** [comment]
First, I'd point out that you might be in the wrong repository. You're using `@material/top-app-bar`, which is part of the MDC library that uses Sass:

https://github.com/material-components/material-components-web/

This is the MWC library. It's built off of MDC, and wraps everything in a web component, making it easier to use. I'd highly recommend trying that instead since it's much easier to set up and use than MDC. You can install most of the MWC components with the `mwc-*` prefix before the component (`npm install @material/mwc-top-app-bar`).

Secondly, I'd recommend joining our Polymer Slack channel for general app help. Then Open WC folk have a dedicated #open-wc channel there and they're super friendly! There's also a #material channel where you can ask questions about both MDC and MWC, and you can ask about all sorts of LitElement-related questions in #general. There's even a #tools channel that'd be great for Rollup questions.

https://www.polymer-project.org/slack-invite
