### ISSUE TITLE
Vertical-Padding CSS var

### ISSUE THREAD

**Issue by aress31** [material-components/material-components-web-components#1458]
**Is your feature request related to a problem? Please describe.**
For components such as `<mwc-textfield>` and `<mwc-button>`, exposing a CSS variable `--vertical-padding` would enhance the customisation potential.

**Describe the solution you'd like**
Adding a new CSS variable to apply arbitrary vertical padding to relevant components, e.g. buttons and textfields.

**Describe alternatives you've considered**

**Additional context**

**Comment by asyncLiz** [comment]
This sounds more like a request to change the density and height of a component, which is an upcoming feature that you can track in https://github.com/material-components/material-components-web-components/issues/841.

The Material Design spec allows for some padding values to be customized, and those are exposed as custom properties where that is allowed. However, there won't be an arbitrary variable exposed to change the overall padding of all components. This is outside the scope of what is allowed to be customized in Material Design.

What you could do is extend the components and add another stylesheet with customizations to make Material-inspired components that aren't as strict to adhering to the spec.

```ts
@customElement('my-button')
class MyButton extends Button {
  static styles = [
    Button.styles,
    css`
      /* overriding styles and customizations */
    `
  ];
}
```

**Comment by aress31** [comment]
I wasn't aware that I could extend existing components this way, this is worth adding to the doc. 😇

**Comment by asyncLiz** [comment]
While it's _possible_, this isn't something we directly support right now. This is essentially "forking" at runtime, you'll be susceptible to breaking changes in the DOM structure with minor version updates.

So, proceed with caution!
