### ISSUE TITLE
disabling a button should prevent handling click/tap events

### ISSUE THREAD

**Issue by elf-pavlik** [material-components/material-components-web-components#148]
I remember in paper-button disabling it would prevent handing click/tap events on it, which comes very handy when binding computed property, for example `?disabled=${!formValidates}`. Current button implementation seems to only style it as disabled but still leaves it functionality enabled.

**Comment by balloob** [comment]
The mdc-button under the hood already does this internally, but it doesn't work for us as the click listener is attached to the `<mwc-button>` web component element and not to the `<button>` class used internally.

The `mdc-button` css:

https://github.com/material-components/material-components-web/blob/7ed6123a959b48e2b3062d557b35633922bad87d/packages/mdc-button/_mixins.scss#L261-L272

Here is how `iron-control-state` behavior does it for Polymer, which is what powers `<paper-button>`: 

https://github.com/PolymerElements/iron-behaviors/blob/ee0e52250de419811a26e0d25e2752037ad6df04/iron-control-state.js#L76-L78

```js
  _disabledChanged: function(disabled, old) {
    this.setAttribute('aria-disabled', disabled ? 'true' : 'false');
    this.style.pointerEvents = disabled ? 'none' : '';
```

**Comment by balloob** [comment]
Created a PR to fix it: https://github.com/material-components/material-components-web-components/pull/227
