### ISSUE TITLE
Allow resizing <mwc-button>'s height

### ISSUE THREAD

**Issue by mothepro** [material-components/material-components-web-components#1504]
**Is your feature request related to a problem? Please describe.**
Unable to customize the height of `<mwc-button>`s.

**Describe the solution you'd like**
Add a CSS custom property that allows this to be changed.

**Describe alternatives you've considered**
The workaround is very ugly, assuming you have a custom element that renders `<mwc-button id="btn">hello</mwc-button>` and want to change the height of it's contents, the host element can run the follow snippet during it's `firstUpdated` stage.

```typescript
protected async firstUpdated() {
  await this.updateComplete
  const style = document.createElement('style')
  style.textContent = '#btn{ height: auto }'
  this.shadowRoot?.firstElementChild?.shadowRoot.appendChild(style)
}
```

**Additional context**
[It is forced to 36px](https://github.com/material-components/material-components-web/blob/master/packages/mdc-button/_variables.scss) and the must crawl into the shadow dom to set its height to `auto`.

**Comment by asyncLiz** [comment]
This will be possible with the upcoming density system. Duplicate of https://github.com/material-components/material-components-web-components/issues/81

**Comment by MarcSkovMadsen** [comment]
I would also need this.

**Comment by Glamurio** [comment]
When is this density update coming?
