### ISSUE TITLE
mwc-textfield requirements for publishing to npm

### ISSUE THREAD

**Issue by kr05** [material-components/material-components-web-components#151]
I would like to help out with the development mwc-textfield, but I'm at a loss as to what missing features, bugs, etc... this component has that is preventing it from being published. I understand it would require some time investment from the team's part to compile this checklist, but a very short list would be really helpful in pointing me in the right direction! 

I made my own checklist that bases itself on the few bugs I encountered and the needs of my own project:
afterNextRender missing export bug
fullWidth 
readonly
labelAlwaysFloat
more customizable css
...and what I imagine is one of the most important requirements: rewrite to typescript

I made a local copy of the component and was able to implement the first five, but my question still remains: what can I do to help get this component published?

**Comment by pitus** [comment]
I'd like to help as well in getting several components into npm, including the textfield. How can we help?

**Comment by JosefJezek** [comment]
`npm ERR! 404 Not Found - GET https://registry.npmjs.org/@material%2fmwc-textfield - Not found`

**Comment by azakus** [comment]
Closing for #293
