### ISSUE TITLE
mwc-dialog field validation

### ISSUE THREAD

**Issue by nicolasr75** [material-components/material-components-web-components#1514]
What is the recommended way to validate data entered by the user in an mwc-dialog?

Following the examples I have OK/Cancel buttons on my dialog. The OK button uses dialogAction="ok" which closes the dialog. I could listen for the closed event and validate the data there but that doesn't seem to be a good idea. The user could have entered data in a dozen fields with one of them invalid. Since my validation error would come after the dialog has been closed, the user would have to enter all data again.

Should I use a button without dialogAction="ok", validate and close the dialog myself? What is the recommended pattern?

**Comment by dfreedm** [comment]
Yes, use a button without a `dialogAction` and manually closing the dialog is the recommended pattern.
I'll keep this bug open to remind us to add this pattern to the documentation for dialog.
