### ISSUE TITLE
mwc-top-app-bar slot actionItems disappear on desktop media

### ISSUE THREAD

**Issue by mahdiridho** [material-components/material-components-web-components#1517]
**Describe the bug**
I create a app with mwc-drawer + mwc-top-app-bar. The mwc-drawer type is modal and the top app bar has actionItems slot icon button. On mobile media size, I can see the actionItems slot icon button, but not for desktop media.

How to make the actionItems slot always appear on every media?

**To Reproduce**
My code is like so :

      <mwc-drawer hasHeader .type="${this.desktop?'':'modal'}">
        <span slot="title">Menu</span>
        <span slot="subtitle">subtitle</span>
        <div>
          <p>Drawer content!</p>
        </div>
        <div slot="appContent">
          <mwc-top-app-bar>
            <mwc-icon-button slot="navigationIcon" class="menu" icon="menu" ?hidden="${this.desktop}"></mwc-icon-button>
            <div slot="title">${this.appTitle}</div>
            <mwc-icon-button slot="actionItems" icon="account_circle" title="Profile"></mwc-icon-button>
          </mwc-top-app-bar>
          <div>
            <p>Main Content!</p>
          </div>
          <mwc-snackbar labelText="You are now ${this._offline ? 'offline' : 'online'}."></mwc-snackbar>
        </div>
      </mwc-drawer>

**Expected behavior**
I want the actionsItems slot icon button always appear either on desktop and mobile media size.

**Screenshots**
Desktop version
![Screenshot from 2020-07-10 15-11-19](https://user-images.githubusercontent.com/10230037/87133632-ce123d80-c2c1-11ea-9f57-324532d9e354.png)

Mobile version
![Screenshot from 2020-07-10 15-11-39](https://user-images.githubusercontent.com/10230037/87132283-d8333c80-c2bf-11ea-8224-d517e1a53407.png)

**Browser Version (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - Browser [e.g. chrome, firefox]

**Comment by dfreedm** [comment]
This should be fixed with #1508. More information is available in this comment: https://github.com/material-components/material-components-web-components/issues/705#issuecomment-656317015

**Comment by mahdiridho** [comment]
I have read the related issue and left a comment there. It's similar but different case. If you read my created issue carefully, I'm implementing dynamic drawer switch between desktop and mobile version.
