### ISSUE TITLE
mwc-checkbox disabled broken

### ISSUE THREAD

**Issue by Avocher** [material-components/material-components-web-components#153]
It seems that the disabled attribute doesn't work anymore:
https://material-components.github.io/material-components-web-components/demos/checkbox.html

**Comment by eskan** [comment]
i think demo is not in sync with master branch : clone the repo and 

> npm run dev

 to verify the master

**Comment by eskan** [comment]
i did, you're right it's doesn't work anymore

**Comment by kenchris** [comment]
I also tries upgrading mwc-radio and mwc-formfield from 0.2.1 to 0.3.1 and both stopped working (just renders [Object object] now)

**Comment by eskan** [comment]
@kenchris i think this happen when you have multiple lit-html you can 

> npm ls lit-html

and maybe

>  npm dedup

can solve this

**Comment by kenchris** [comment]
`npm ls lit-html` lists lit-html@0.12.0 for all projects and shows that some of deduped
