### ISSUE TITLE
Allow <mwc-select> to have <a> links as children

### ISSUE THREAD

**Issue by bennypowers** [material-components/material-components-web-components#1585]
**Is your feature request related to a problem? Please describe.**
Users may want to add links to a select dropdown.

**Describe the solution you'd like**
`<mwc-select>` should allow link children
```html
<mwc-select>
  <a href="#a" tabindex="-1"><mwc-list-item selected>A!</mwc-list-item></a>
  <a href="#b" tabindex="-1"><mwc-list-item>B!</mwc-list-item></a>
  <a href="#c" tabindex="-1"><mwc-list-item>C!</mwc-list-item></a>
</mwc-select>
```

**Describe alternatives you've considered**
Routing with JavaScript by handling select events will work, but breaks user expectations about how web navigation works.
Alternately, nesting the link inside the list item breaks a pattern well-established elsewhere (to wrap the CE in the link), as well, the item's whitespace would not possess the link properties users expect (click to nav, hover to inspect URL)

**Comment by dfreedm** [comment]
What is the use case for using select in this scenario?
The textfield presentation of the selected item doesn't make sense to me if selecting the item causes a navigation.
Could you show an example of how you would use this?

**Comment by bennypowers** [comment]
:wave: Imagine you have an app that implements a list/detail view for a collection of items.

```html
<!-- /items/ -->
<h2>List View</h2>
<data-table>
  <data-row data-name="An Item" data-id="an-item-eui7"></data-row>
  <data-row data-name="Another Item" data-id="another-item-cdd7"></data-row>
  <data-row data-name="Odd Item" data-id="odd-item-z70x"></data-row>
</data-table>
```
Clicking on a `<data-row>` will navigate the user to a detail view at `/items/${itemId}`:

```html
<!-- /items/an-item-eui7/ -->
<header>
  <h2>Detail View</h2>
  <mwc-select>
    <a href="/items/an-item-eui7/" tabindex="-1"><mwc-list-item selected>An Item</mwc-list-item></a>
    <a href="/items/another-item-cdd7/" tabindex="-1"><mwc-list-item>Another Item</mwc-list-item></a>
    <a href="/items/odd-item-z70x/" tabindex="-1"><mwc-list-item>Odd Item</mwc-list-item></a>
  </mwc-select>
</header>

<item-card heading="An Item">
  <!-- let's imagine `<item-details>` fetches and displays item by id --> 
  <item-details item-id="an-item-eui7"></item-details>
</item-card>
```

So what we're trying to achieve here is a drop-down menu which, upon selection, switches the detail view from one item to another. In other words, we'd like to provide a shortcut UX, so that the user does not need to navigate back to the list view to select an item. Consider that `<item-details>` might contain its own deep routes, so we might end up switching (in the select> from a URL like `/items/odd-item-z70x/boop/snoot` to a URL like `/items/an-item-eui7/boop/snoot`

**Comment by asyncLiz** [comment]
I believe that you want two user experiences (correct me if I'm wrong):

1. Display the current navigation item (the text field part of the select)
2. Change to a new navigation item in a dropdown (the menu part of the select)

I'm concerned about the accessibility of what this is trying to accomplish. For starters, what you're trying to do is not possible with a native `<select>`. Anchor tags within or surrounding `<option>` elements do not cause page navigation events. Additionally the ARIA roles of `<mwc-select>` are likely incorrect for this use case and would need investigation. I'd expect to see a combination of "navigation"/"list"/"listitem", not "listbox"/"option".

Furthermore, Material Design already has an established pattern for navigation from menus with list items. 

My recommendation would be to avoid the `<mwc-select>` component for this UX and represent the display of the current navigation item in a different UX that consists of the menu's anchor: for example, the text of a button that opens the menu with navigation list items to display.

**Comment by e111077** [comment]
Closing this issue as wontfix as it deviates from material navigation guidelines
