### ISSUE TITLE
Support "global" format for components

### ISSUE THREAD

**Issue by jifalops** [material-components/material-components-web-components#159]
Allow components to be imported as a global variable, similar to how `material-components-web` can be imported via a script that exposes `mdc.<component/group>.<class>`, e.g. `mdc.base.MDCComponent`. This may be resolved naturally as part of #158.

**Comment by azakus** [comment]
I'm not really sure that we want to do that.
Given that custom elements are globally usable via `document.createElement("tag-name")`, there's really no need to make globals for the constructors.

If you really want to, you can do `window.TagName = customElements.get("tag-name")` and make globals for yourself.
