### ISSUE TITLE
adding checkbox with appendChild() failed in typescript

### ISSUE THREAD

**Issue by qwefgh90** [material-components/material-components-web-components#160]
I am developing an electron app with material checkbox. 
When `div.appendChild(new Checkbox())` after importing `import { Checkbox } from "@material/mwc-checkbox"`, ts-loader emits a following error (webpack --watch).

![image](https://user-images.githubusercontent.com/7572251/48050946-f2fa0780-e1e6-11e8-8f5e-7de548ad441b.png)

I found out some workarounds that It is to adding accessKey property after casting to any type.
![image](https://user-images.githubusercontent.com/7572251/48051084-79aee480-e1e7-11e8-9191-42766665f0e4.png)

**Comment by frankiefu** [comment]
I believe this is fixed now. Let us know if you are still having issue.
