### ISSUE TITLE
Several Missing Packages in NPM

### ISSUE THREAD

**Issue by hen42** [material-components/material-components-web-components#162]
Many of the components are not in npm, although the readme file tells me it is.

npm i @material/mwc-slider 

npm ERR! 404 Not Found: @material/mwc-slider@latest

Best regards

**Comment by elf-pavlik** [comment]
duplicate of #76 ?

**Comment by hen42** [comment]
yes, thanks duplicate of #76 .

Any updates on the roadmap, when will these components be released ?
