### ISSUE TITLE
`mwc-circular-progress` doesn't render correct inside `mwc-button`

### ISSUE THREAD

**Issue by bramkragten** [material-components/material-components-web-components#1647]
**Describe the bug**
When a `mwc-circular-progress` element is placed inside `mwc-button` the animation is not shown correct.

**To Reproduce**
```html
<mwc-button>
  <mwc-circular-progress
    indeterminate 
    density="-5"
  >
  </mwc-circular-progress>
</mwc-button>
```

**Expected behavior**
The normal animation.

**Screenshots**
![image](https://user-images.githubusercontent.com/5662298/89306900-c18ac600-d670-11ea-8102-2766a973703c.png)

**Browser Version (please complete the following information):**
 - OS: MacOSX
 - Browser Chrome
 - Version 84.0.4147.89

**Additional context**

**Comment by e111077** [comment]
upstream fix in material-components/material-components-web#6332

will close on merge + merge of deps bump

**Comment by allan-chen** [comment]
@e111077 can this be closed now with dep bump 5 days ago?
