### ISSUE TITLE
npm run bootstrap script is malfunctioning

### ISSUE THREAD

**Issue by andythsu** [material-components/material-components-web-components#166]
I cloned the project, ran
-npm run bootstrap
it returned the error while trying to run this line:
  -./scripts/bootstrap.sh

```
find: warning: you have specified the -maxdepth option after a non-option argument -name, but options are not positional (-maxdepth affects tests specified before it as well as those specified after it).  Please specify options before other arguments.

module.js:549
    throw err;
    ^

Error: Cannot find module '/packages/base/package.json'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at [eval]:1:13
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at Object.runInThisContext (vm.js:139:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:652:30)
    at evalScript (bootstrap_node.js:463:27)
```

How to fix this?

_Originally posted by @andythsu in https://github.com/material-components/material-components-web-components/issue_comments#issuecomment-442939718_

**Comment by kr05** [comment]
Are you by any chance using Windows? I'm asking because I was unable to get the build script to work on it; if you are indeed using Windows, I strongly recommend reading into the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10). It's a fantastic feature that enables you to sidestep all of these nasty errors. I've been using it for all of my development, and it's been great so far (save for a few times when it fails to load, but a simple restart fixes the problem).

**Comment by andythsu** [comment]
> Are you by any chance using Windows? I'm asking because I was unable to get the build script to work on it; if you are indeed using Windows, I strongly recommend reading into the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10). It's a fantastic feature that enables you to sidestep all of these nasty errors. I've been using it for all of my development, and it's been great so far (save for a few times when it fails to load, but a simple restart fixes the problem).

@kr05 Thank you for your reply! Does that mean I'll need Linux environment for starting the project? Is there by any chance I can bypass this error on Windows?

**Comment by andythsu** [comment]
@kr05 Hi, I ran the command (npm run bootstrap) in WSL Ubuntu, but it's still throwing the error
```
find: warning: you have specified the -maxdepth option after a non-option argument -name, but options are not positional (-maxdepth affects tests specified before it as well as those specified after it).  Please specify options before other arguments.

module.js:549
    throw err;
    ^

Error: Cannot find module '/packages/base/package.json'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at [eval]:1:13
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at Object.runInThisContext (vm.js:139:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:652:30)
    at evalScript (bootstrap_node.js:463:27)

npm ERR! Linux 4.4.0-43-Microsoft
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "bootstrap"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! material-components-web-components@ bootstrap: `npm install && ./scripts/bootstrap.sh && npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the material-components-web-components@ bootstrap script 'npm install && ./scripts/bootstrap.sh && npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the material-components-web-components package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install && ./scripts/bootstrap.sh && npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs material-components-web-components
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls material-components-web-components
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/andy/material-components-web-components/npm-debug.log
```

**Comment by kr05** [comment]
Do you have the environment set up correctly? Since it's a different system, you need to start from scratch. Treat it as if you had just reset your computer. Install git, node, and anything else you might need (or confirm their presence by logging the versions with their respective command). Afterwards, make sure you do a fresh git clone from within the linux terminal and try running the script again.

The setup is a bit of a pain, but it's definitely worth it in my opinion.

**Comment by andythsu** [comment]
@kr05  yes I'm sure I have set up everything correctly.

I installed git, npm, node from sudo apt-get, cloned the repo, and still ran into this error :(

**Comment by kr05** [comment]
Can you post the npm-debug,log file? I was able to get it to work on my machine after a bit of struggling.

**Comment by kr05** [comment]
Are you still unable to setup the project?

**Comment by andythsu** [comment]
> Are you still unable to setup the project?

Hello,
We have decided to move on to a different approach and therefore I haven't tested it since then.
Thank you for your help

**Comment by kr05** [comment]
No worries. Do you mind telling me how you worked around the problem? Or do you mean you decided to use a different project altogether.

**Comment by andythsu** [comment]
Yes. We have abandoned this and moved on to a different project altogether.

**Comment by fernandopasik** [comment]
I've tried to run this and I haven't seen any problem. I see that in your run you use **node 8** which has reached end-of-life.

Is anybody else having problems with this?

**Comment by dfreedm** [comment]
Closing this due to age and inactivity.
