### ISSUE TITLE
build fails after latest commit

### ISSUE THREAD

**Issue by bravius** [material-components/material-components-web-components#1665]
**Describe the bug**

Build fails, throws an error. Seems to be related to this recent commit:

https://github.com/material-components/material-components-web-components/commit/3a2df1b9c22b1ee484816a3288ebb8c6ed4ed86f

**To Reproduce**

1. git clone git@github.com:material-components/material-components-web-components.git mwc
2. cd mwc
3. yarn install
4. yarn run build

**Expected behavior**

Successful build.

**Additional context**

build console output:

Generating packages/button/src/mwc-button-css.ts
Generating packages/checkbox/src/mwc-checkbox-css.ts
Generating packages/circular-progress/src/mwc-circular-progress-css.ts
Generating packages/circular-progress-four-color/src/mwc-circular-progress-four-color-css.ts
Generating packages/dialog/src/mwc-dialog-css.ts
Generating packages/drawer/src/mwc-drawer-css.ts
Generating packages/fab/src/mwc-fab-css.ts
Generating packages/floating-label/src/mwc-floating-label-css.ts
Generating packages/formfield/src/mwc-formfield-css.ts
Generating packages/icon/src/mwc-icon-host-css.ts
Generating packages/icon-button/src/mwc-icon-button-css.ts
Generating packages/line-ripple/src/mwc-line-ripple-css.ts
Generating packages/linear-progress/src/mwc-linear-progress-css.ts
Generating packages/list/src/mwc-control-list-item-css.ts
Generating packages/list/src/mwc-list-item-css.ts
Generating packages/list/src/mwc-list-css.ts
Generating packages/menu/src/mwc-menu-surface-css.ts
Generating packages/menu/src/mwc-menu-css.ts
Generating packages/notched-outline/src/mwc-notched-outline-css.ts
Generating packages/radio/src/mwc-radio-css.ts
Generating packages/ripple/src/mwc-ripple-global-css.ts
Generating packages/ripple/src/mwc-ripple-css.ts
Generating packages/select/src/mwc-select-css.ts
Error: $string: (hover: (varname: --mdc-select-hover-line-color, fallback: rgba(0, 0, 0, 0.87))) is not a string.
    ╷
228 │     str_slice($style, 1, 4) == 'var(' or $style == 'inherit' or $style ==
    │     ^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  node_modules/@material/theme/_theme-color.scss 228:5                    is-valid-theme-prop-value-()
  node_modules/@material/theme/_theme.scss 119:14                         prop()
  node_modules/@material/line-ripple/_mixins.scss 99:7                    @content
  node_modules/@material/feature-targeting/_feature-targeting.scss 218:5  targets()
  node_modules/@material/line-ripple/_mixins.scss 97:3                    inactive-color()
  node_modules/@material/select/_select-theme.scss 1086:5                 -bottom-line-color()
  node_modules/@material/select/_select-theme.scss 252:5                  @content
  node_modules/@material/select/_select-theme.scss 1052:5                 -if-enabled()
  node_modules/@material/select/_select-theme.scss 251:3                  bottom-line-color()
  packages/select/src/mwc-select.scss 91:5                                root stylesheet
    at Object._newRenderError (/mnt/d/projects/mwc/node_modules/sass/sass.dart.js:14381:19)
    at Object._wrapException (/mnt/d/projects/mwc/node_modules/sass/sass.dart.js:14228:16)
    at _render_closure1.call$2 (/mnt/d/projects/mwc/node_modules/sass/sass.dart.js:77610:21)
    at _RootZone.runBinary$3$3 (/mnt/d/projects/mwc/node_modules/sass/sass.dart.js:26152:18)
    at _RootZone.runBinary$3 (/mnt/d/projects/mwc/node_modules/sass/sass.dart.js:26156:19)
    at _FutureListener.handleError$1 (/mnt/d/projects/mwc/node_modules/sass/sass.dart.js:24600:19)
    at _Future__propagateToListeners_handleError.call$0 (/mnt/d/projects/mwc/node_modules/sass/sass.dart.js:24897:40)
    at Object._Future__propagateToListeners (/mnt/d/projects/mwc/node_modules/sass/sass.dart.js:4311:88)
    at _Future._completeError$2 (/mnt/d/projects/mwc/node_modules/sass/sass.dart.js:24725:9)
    at _AsyncAwaitCompleter.completeError$2 (/mnt/d/projects/mwc/node_modules/sass/sass.dart.js:24117:12) {
  formatted: 'Error: $string: (hover: (varname: --mdc-select-hover-line-color, fallback: rgba(0, 0, 0, 0.87))) is not a string.\n' +
    '    ╷\n' +
    "228 │     str_slice($style, 1, 4) == 'var(' or $style == 'inherit' or $style ==\n" +
    '    │     ^^^^^^^^^^^^^^^^^^^^^^^\n' +
    '    ╵\n' +
    '  node_modules/@material/theme/_theme-color.scss 228:5                    is-valid-theme-prop-value-()\n' +
    '  node_modules/@material/theme/_theme.scss 119:14                         prop()\n' +
    '  node_modules/@material/line-ripple/_mixins.scss 99:7                    @content\n' +
    '  node_modules/@material/feature-targeting/_feature-targeting.scss 218:5  targets()\n' +
    '  node_modules/@material/line-ripple/_mixins.scss 97:3                    inactive-color()\n' +
    '  node_modules/@material/select/_select-theme.scss 1086:5                 -bottom-line-color()\n' +
    '  node_modules/@material/select/_select-theme.scss 252:5                  @content\n' +
    '  node_modules/@material/select/_select-theme.scss 1052:5                 -if-enabled()\n' +
    '  node_modules/@material/select/_select-theme.scss 251:3                  bottom-line-color()\n' +
    '  packages/select/src/mwc-select.scss 91:5                                root stylesheet',
  line: 228,
  column: 5,
  file: '/mnt/d/projects/mwc/node_modules/@material/theme/_theme-color.scss',
  status: 1
}
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by asyncLiz** [comment]
The build should be fixed as soon as https://github.com/material-components/material-components-web-components/pull/1664 is merged

**Comment by e111077** [comment]
merged, but tests still break due to another issue. Though project should still build after the following action completes:

https://github.com/material-components/material-components-web-components/actions/runs/199571213
