### ISSUE TITLE
Cannot update markers attribute on mwc-slider programmatically

### ISSUE THREAD

**Issue by MarcSkovMadsen** [material-components/material-components-web-components#1671]
I would like to be able to update the `markers` attribute programmatically. But it does not work

# Code

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>MWC Slider</title>
    <script src="https://unpkg.com/@material/mwc-button@0.18.0?module" type="module"></script>
    <script src="https://unpkg.com/@material/mwc-slider@0.18.0?module" type="module"></script>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Material+Icons&display=block" rel="stylesheet">
    </head>
  <body>
    <mwc-slider style="width:100%" value="0" min="0" max="10" step="1"></mwc-slider>
    <mwc-button onclick='el=document.getElementsByTagName("mwc-slider")[0];el.setAttribute("markers", "")'>Toggle Markers</mwc-button>
  </body>
</html>
```

# Steps

Open in browser

![image](https://user-images.githubusercontent.com/42288570/89703683-34d05880-d94d-11ea-8004-a4d137e1f1c0.png)

Click button

![image](https://user-images.githubusercontent.com/42288570/89703692-444fa180-d94d-11ea-89db-bb76d9eb3171.png)

As you can see the markers attribute has been set but the markers are not showing.

#### Additional Context

It works if the `markers` are set initially.

**Comment by asyncLiz** [comment]
Thanks for the bug report! I'll add this to our backlog to fix
