### ISSUE TITLE
importing mwc-list-item using cdn causes DOM error

### ISSUE THREAD

**Issue by smsajid** [material-components/material-components-web-components#1675]
**Describe the bug**
I am using CDN to import required modules. Most components import without any issue. Importing '@material/mwc-list/mwc-list-item' along with other components causes the below error:
``` 
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "mwc-ripple" has already been used with this registry
    at legacyCustomElement (https://unpkg.com/lit-element@2.3.1/lib/decorators.js?module:15:25)
    at https://unpkg.com/lit-element@2.3.1/lib/decorators.js?module:50:1
    at __decorate (https://unpkg.com/tslib@1.13.0/tslib.es6.js?module:56:88)
    at https://unpkg.com/@material/mwc-ripple@0.18.0/mwc-ripple.js?module:25:10
```

**To Reproduce**
Use the below HTML code to reproduce the error:
```
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Sample</title>
  	
	<script type="module" src="https://unpkg.com/@material/mwc-drawer?module"></script>
	<script type="module" src="https://unpkg.com/@material/mwc-icon-button?module"></script>
	<script type="module" src="https://unpkg.com/@material/mwc-top-app-bar?module"></script>
	<script type="module" src="https://unpkg.com/@material/mwc-tab-bar?module"></script>
	<script type="module" src="https://unpkg.com/@material/mwc-select?module"></script>
	<script type="module" src="https://unpkg.com/@material/mwc-list/mwc-list-item?module"></script>
	<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Material+Icons&display=block" rel="stylesheet">
</head>
<body>
	<mwc-drawer id="drawer" hasHeader type="dismissible">
	    <span slot="title">Filters</span>
	    <span slot="subtitle"></span>	
	    <div>
	        <mwc-select  label="filled">
				<mwc-list-item></mwc-list-item>
				<mwc-list-item value="0">Item 0</mwc-list-item>
				<mwc-list-item value="1">Item 1</mwc-list-item>
				<mwc-list-item value="2">Item 2</mwc-list-item>
				<mwc-list-item value="3">Item 3</mwc-list-item>
			</mwc-select>
			<mwc-select outlined label="outlined">
				<mwc-list-item></mwc-list-item>
				<mwc-list-item value="0">Item 0</mwc-list-item>
				<mwc-list-item value="1">Item 1</mwc-list-item>
				<mwc-list-item value="2">Item 2</mwc-list-item>
				<mwc-list-item value="3">Item 3</mwc-list-item>
			</mwc-select>
	    </div>
	    <div slot="appContent">
	    	<div>
		    	<mwc-icon-button id="menuButton" slot="navigationIcon" icon="menu"></mwc-icon-button>
	        </div>
	        <div>
	            <mwc-tab-bar>
					<mwc-tab label="Landscape"></mwc-tab>
					<mwc-tab label="Card Mode"></mwc-tab>
				</mwc-tab-bar>
	        </div>
	    </div>
	</mwc-drawer>

	<script>
		menuButton.addEventListener('click', () => {
			drawer.open = !drawer.open;
		});
	</script>
</body>
</html>
```

**Expected behavior**
mwc-list-item should have been imported without error. And the component should have rendered as expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/534252/89740720-f2656380-da93-11ea-9748-b1b856b6def9.png)

**Browser Version (please complete the following information):**
 - OS: Windows 10
 - Chrome Browser 
 - Version 84.0.4147.105

**Additional context**

**Comment by asyncLiz** [comment]
Thanks for the issue! This is caused by list-item importing ripple in a slightly different way than other elements that causes unpkg to interpret it as a different module. We should be able to fix it in https://github.com/material-components/material-components-web-components/pull/1678.

**Comment by asyncLiz** [comment]
Here is your demo working with unpkg and the latest canary version: https://jsbin.com/huvovogewa/edit?html,output

**Comment by sansclouds** [comment]
I had a  similar issue. I was trying to build a prototype app using the Deno" and Oak framework with lit-html as web components. However, I am now running into another issue.

To the above code if I add a mwc-button I get a similar error with mwc-icon this time.

![mwc-error](https://user-images.githubusercontent.com/26308088/95231600-588b1000-07d1-11eb-9138-7dcd9f004ff3.PNG)


### To Reproduce

Just add mwc-button to the above code.


`
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>My Example App</title>
    
    <script type="module" src="https://unpkg.com/@material/mwc-switch@canary?module"></script>
    <script type="module" src="https://unpkg.com/@material/mwc-checkbox@canary?module"></script>
    <script type="module" src="https://unpkg.com/@material/mwc-button@canary?module"></script>
    <script type="module" src="https://unpkg.com/@material/mwc-fab@canary?module"></script>
    <script type="module" src="https://unpkg.com/@material/mwc-textfield@canary?module"></script>
    <script type="module" src="https://unpkg.com/@material/mwc-textarea@canary?module"></script>
    <script type="module" src="https://unpkg.com/@material/mwc-select@canary?module"></script>
    <script type="module" src="https://unpkg.com/@material/mwc-drawer@canary?module"></script>
    <script type="module" src="https://unpkg.com/@material/mwc-icon-button@canary?module"></script>
    <script type="module" src="https://unpkg.com/@material/mwc-top-app-bar@canary?module"></script>
    <script type="module" src="https://unpkg.com/@material/mwc-tab-bar@canary?module"></script>
    <script type="module" src="https://unpkg.com/@material/mwc-list@canary/mwc-list-item?module"></script>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Material+Icons&display=block" rel="stylesheet">
   </head>
<body>
 
<mwc-drawer hasHeader type="modal">
    <span slot="title">Drawer Title</span>
    <span slot="subtitle">subtitle</span>
    <div>
        <p>Drawer content!</p>
        <mwc-icon-button icon="gesture"></mwc-icon-button>
        <mwc-icon-button icon="gavel" id="gavel"></mwc-icon-button>
    </div>
    
    <div slot="appContent">
        <mwc-top-app-bar>
            <mwc-icon-button slot="navigationIcon" icon="menu"></mwc-icon-button>
            <div slot="title">Money Manager</div>
        </mwc-top-app-bar>
        <div>
            <p>Main Content!</p>
             
    <div>
      <mwc-select  label="Category">
         <mwc-list-item></mwc-list-item>
         <mwc-list-item value="0">Mortgage</mwc-list-item>
         <mwc-list-item value="1">Groceries</mwc-list-item>
         <mwc-list-item value="2">Utilities</mwc-list-item>
         <mwc-list-item value="3">Insurance</mwc-list-item>
         <mwc-list-item value="4">Transportation</mwc-list-item>
      </mwc-select>
  <BR>
    <mwc-select outlined label="Type">
       <mwc-list-item></mwc-list-item>
       <mwc-list-item value="0">Checking</mwc-list-item>
       <mwc-list-item value="1">Saving</mwc-list-item>
      <mwc-list-item value="2">Credit Card</mwc-list-item>
      <mwc-list-item value="3">Investment</mwc-list-item>
    </mwc-select>
  </div> 
</mwc-drawer>
<script>
  var drawer = document.getElementsByTagName('mwc-drawer')[0];
  var container = drawer.parentNode;
  container.addEventListener('MDCTopAppBar:nav', function(e) {
    drawer.open = !drawer.open;
  });
  
</script>
</body>
</html>
`

**Comment by ais-one** [comment]
This still has a problem in 0.20.1

**Comment by RoXuS** [comment]
+1 same issue.
