### ISSUE TITLE
demos/index.html fails on IE11

### ISSUE THREAD

**Issue by JEAxero** [material-components/material-components-web-components#168]
When I visit the demos page from the README on IE11, it fails with the following in the IE11 console:

(warning) HTML1414: Unexpected character: U+0021 EXCLAMATION MARK (!)
index.html (31,14)

(warning) HTML1416: Unexpected character in comment end. Expected "-->".
index.html: (31,15)

(error) SCRIPT1009: Expected '}'
index.html (2047,26)

I realize that the GitHub site itself no longer supports IE11 but I wanted to test the demos on IE11 to confirm (for a presentation at work) that these web components really did work in IE11. Will revert to trying to use them in my own web app but, from a "first impression" perception, the demos really should work in IE11 to readily confirm the browser support listed on the README.

**Comment by straversi** [comment]
Investigated: The published demos page fails, while the demos page on master does not, at least when served from the dev server. Either the publish script transforms demos in a way that breaks for IE 11, or we just need to re-deploy.

**Comment by dfreedm** [comment]
Migrated demos to glitch, which uses conditional serving for IE11
