### ISSUE TITLE
[TabBar] Trailing Icon for Menu Support

### ISSUE THREAD

**Issue by aress31** [material-components/material-components-web-components#1769]
Could it be possible to add support for a trailing (right aligned) icon to a tab item to support opening menu on click?

**Comment by e111077** [comment]
Can you explain this further using the issue template? Additionally, the `slot="actionItems"` won't work for this?

**Comment by aress31** [comment]
This screenshot might help:

![image](https://user-images.githubusercontent.com/11601622/92518467-4fc60f00-f210-11ea-94cb-b001c84964e5.png)

See in the `<tab-bar>`, the `Services` and `Resources` navigation options have a drop down icon that open a `<mwc-menu>` `onClick`, I checked the `tab-bar` it seems not possible to set a trailing icon, it seems however possible to set a Stacked and Left icon.

**Comment by e111077** [comment]
ah i misread tab bar as app bar. Guidance warns against mixing tabs with and without icons. Also I have some reservations about mixing selection components together. e.g. what would make Services become underlined? when you click it, or when you select something inside of the menu?

Will defer to design

**Comment by e111077** [comment]
b/168048350

**Comment by aress31** [comment]
If that helps, this is how I implemented it:

![image](https://user-images.githubusercontent.com/11601622/92522968-763b7880-f217-11ea-9cbc-d5cdeb1d93cf.png)

**Comment by e111077** [comment]
Design says this pattern is unsupported:

> Having children navigation in an individual tab item is actually not supported, and is actually not a good idea.
Based on the screenshot you provided, I would advise against a dropdown menu on a tab item, and using a trailing icon.

**Comment by aress31** [comment]
Makes sense but in this case what does the Material Design team suggest for website navigation menus? 90% of the websites on the internet have a horizontal navigation menu with drop down menus for children routes.

**Comment by e111077** [comment]
This is why we are making this component set; to provide components that fit the official material design guidelines and not promote patterns and interactions that the design guidelines do not promote

**Comment by aress31** [comment]
Totally understand that but the Material Design spec - as far as I understand it - has no built in mechanisms for normal website navigation beside the drawer, the drawer is the main navigation component of the Material Spec. 

I am no UI/UX specialist but I heard from many of them that on large viewport a Drawer is actually awful for navigation, and the only other component for navigation is the tab-bar which doesn't support nested routes. 

So what is the Material Design recommended way of achieving what I illustrated in the previous posts screenshot?

I am eager to learn. 🤓
