### ISSUE TITLE
[LinearProgressBar] Custom thickness/width

### ISSUE THREAD

**Issue by aress31** [material-components/material-components-web-components#1771]
Could it be possible to arbitrarly set the `width/thickness` of the `LPB` or alternatively to introduce a thinner version? Right now it is `4px` `width`, a `2px` `width` could be a good choice!

**Comment by e111077** [comment]
upstreamed to design, meanwhile can you give me a use case for the thinner progressbar? perhaps screenshots?

**Comment by e111077** [comment]
b/168044130

**Comment by aress31** [comment]
Could be for a scrolling indicator like in the following screenshot:

![image](https://user-images.githubusercontent.com/11601622/92519570-12fb1780-f212-11ea-9546-9447c42e5349.png)

As you can see the bar is a bit thick and take away the users' attention from the main content, it is there as a simple indicator and should therefore be "lighter".

Also, I can think about custom loading indicators, for example on the Youtube website when the site loads, at the very top of the window there is a very thin red progress bar indicator.

There might be many more use cases I am not aware of but providing granular control on the thickness of the LPB can - I reckon - only be a good thing! 🤗

**Comment by e111077** [comment]
Just a heads up, material guidance notes that it should be used to "Focus user attention", but I brought this topic up to design in the meanwhile

**Comment by e111077** [comment]
Designers advise against thinner progress bars (which means we might add a min-height). If you want a thicker one, please give us an example of how and what context it would be used.

**Comment by aress31** [comment]
As mentioned in my previous post, a few uses cases for a thinner `LPB` could be:
- sleek and thin scroll indicator
- top page loading indicator (YouTube style)
