### ISSUE TITLE
[mwc-button-icon and Material Icons] Extra/unnecessary Top Padding

### ISSUE THREAD

**Issue by aress31** [material-components/material-components-web-components#1772]
**Describe the bug**
I have noticed using the Chrome dev tools, that using Material Icons together with `mwc-button-icon` add unnecessary top padding on the icon.

**To Reproduce**
```js
import linkedinIcon from '../components/svgs/brands/linkedin.svg.js';

--- SNIP-- -
    
<div class="action-icons" slot = "actionItems" >
    <!-- social icons -->
    <mwc-icon-button
        @click=${() =>
        Router.go(socialMedia.href)}
        >linkedinIcon</mwc-icon-button
    >
</div>

--- SNIP ---
```

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/11601622/92524217-9ec47200-f219-11ea-81a0-382792288a2c.png)

**Browser Version (please complete the following information):**
```
Google Chrome
Version 85.0.4183.83 (Official Build) (64-bit)
```

**Additional context**

**Comment by e111077** [comment]
This is an internal <i> and style because its a part of the implementation. What are you trying achieve in which it cannot be applied to `<mwc-icon-button>` directly?

**Comment by aress31** [comment]
I am not trying to achieve anything `mwc-button-icon` works just fine it is just this internal extra top padding which bugs me a bit like is it really necessary?

**Comment by e111077** [comment]
It is necessary. Without the padding it looks like this

![image](https://user-images.githubusercontent.com/5981958/92539483-6e1f1100-f1f6-11ea-8afa-9be6772f0b49.png)
