### ISSUE TITLE
Test Failing

### ISSUE THREAD

**Issue by romulocintra** [material-components/material-components-web-components#18]
Chrome 67.0.3396 (Mac OS X 10.13.4) ERROR
  {
    "message": "Uncaught Error: Cannot find module \"@material/mwc-button\"\nat webpack:///test/unit/mwc-button.test.js:18:0 <- test/unit/index.js:1778:169\n\nError: Cannot find module \"@material/mwc-button\"\n    at webpackMissingModule (webpack:///test/unit/mwc-button.test.js:18:0 <- test/unit/index.js:1778:82)\n    at Object.<anonymous> (webpack:///test/unit/mwc-button.test.js:18:0 <- test/unit/index.js:1778:179)\n    at __webpack_require__ (webpack:///webpack/bootstrap%208bcbc6ae67f3971d3045:19:0 <- test/unit/index.js:35:30)\n    at webpackContext (webpack:///test/unit%20/.test/.js$:22:0 <- test/unit/index.js:1754:9)\n    at Array.forEach (<anonymous>)\n    at Object.map../mwc-button.test.js (webpack:///test/unit/index.js:20:20 <- test/unit/index.js:1727:21)\n    at __webpack_require__ (webpack:///webpack/bootstrap%208bcbc6ae67f3971d3045:19:0 <- test/unit/index.js:35:30)\n    at webpack:///webpack/bootstrap%208bcbc6ae67f3971d3045:62:0 <- test/unit/index.js:78:18\n    at test/unit/index.js:81:10\n    at webpackUniversalModuleDefinition (webpack:///webpack/universalModuleDefinition:9:0 <- test/unit/index.js:14:17)",
    "str": "Uncaught Error: Cannot find module \"@material/mwc-button\"\nat webpack:///test/unit/mwc-button.test.js:18:0 <- test/unit/index.js:1778:169\n\nError: Cannot find module \"@material/mwc-button\"\n    at webpackMissingModule (webpack:///test/unit/mwc-button.test.js:18:0 <- test/unit/index.js:1778:82)\n    at Object.<anonymous> (webpack:///test/unit/mwc-button.test.js:18:0 <- test/unit/index.js:1778:179)\n    at __webpack_require__ (webpack:///webpack/bootstrap%208bcbc6ae67f3971d3045:19:0 <- test/unit/index.js:35:30)\n    at webpackContext (webpack:///test/unit%20/.test/.js$:22:0 <- test/unit/index.js:1754:9)\n    at Array.forEach (<anonymous>)\n    at Object.map../mwc-button.test.js (webpack:///test/unit/index.js:20:20 <- test/unit/index.js:1727:21)\n    at __webpack_require__ (webpack:///webpack/bootstrap%208bcbc6ae67f3971d3045:19:0 <- test/unit/index.js:35:30)\n    at webpack:///webpack/bootstrap%208bcbc6ae67f3971d3045:62:0 <- test/unit/index.js:78:18\n    at test/unit/index.js:81:10\n    at webpackUniversalModuleDefinition (webpack:///webpack/universalModuleDefinition:9:0 <- test/unit/index.js:14:17)"
  }

**Comment by azakus** [comment]
I think this should have been fixed with #45
