### ISSUE TITLE
Enable mwc-icon to use non material font icons 

### ISSUE THREAD

**Issue by homerjonathan** [material-components/material-components-web-components#1826]
When writing a progresive application you try and limit the download of the fonts, so you might want to download a smaller set to get going.  Or desiging your application the materials fonts are fantastic but you need 1 or 2 specific to your application.  At the moment you can do this:

```css
.myicons {
  font-family: myiconfont;
}
```
You can then set the class of the icon to use the new family.  You can then use the ligatures to select your own set of icons.

However that means when you select the font you need to do

```html
<mwc-icon class="myicons">myappicon</mwc-icon>
```

I built my code from Polymer and it used to have the idea of a ":" to do this.  So values before the colon linked it to the class, then aftewards the name.  Since I am moving an application over from Polymer I have had to modfy my code to do it like this:

```html
<mwc-icon>myicons:myappicon</mwc-icon>
```

I use the colon as a flag with simple index before afterwards to split the two values (there may be a better way, it was a quick fix).  If it has none it selects the normal material icon font.  Otherwise it changes class of mwc-icon and adds to the class="myicons" to the icon automatically effectively changing the font.  Which works well in my application.  So I have solved my issue.

I have raised this feature request to see if the community feels that this would be a valuable feature to add to the mwc-icon rather than expanding as I have demonstrated. I think it adds a powerful feature to the code with only minimal cost for running.  Or perhaps an entry into the documentation to show the simple technique of opening up <mwc-icon> to other icons.

**Comment by asyncLiz** [comment]
You can use the `--mdc-icon-font` custom property to change the icon font family in `<mwc-icon>` and many other components. The documentation can be found in the [icon readme](https://github.com/material-components/material-components-web-components/tree/master/packages/icon#css-custom-properties).

```css
.myicons {
  --mdc-icon-font: myiconfont;
}
```

Not all icon strings in our components are provided to the `<mwc-icon>` element, so adding a prefix and logic to split and load different icon families would not be useful for components that do not use the element, such as text field.

```html
<!-- Does not use <mwc-icon>, does not know how to handle the prefix -->
<mwc-textfield icon="myicons:myappicon"></mwc-textfield>

<!-- This use case is simpler for the text field -->
<style>
  mwc-textfield {
    --mdc-icon-font: myicons;
  }
</style>
<mwc-textfield icon="myappicon"></mwc-textfield>
```

We believe the simplicity of providing a single custom property that can be shared and scoped to different sections of a document using CSS selectors is sufficient without the extra logic of prefixes, elements, or font loading. The `<mwc-icon>` is simply a helper element for users that wish to use icons themselves!
