### ISSUE TITLE
mwc-textfield outlined error

### ISSUE THREAD

**Issue by achutkiran** [material-components/material-components-web-components#183]
When user click mwc-textfield outlined. then text field moves to the right
![image](https://user-images.githubusercontent.com/26334163/50986859-8b558680-14cd-11e9-9f2f-ad4f2817e190.png)

![image](https://user-images.githubusercontent.com/26334163/50986884-a0321a00-14cd-11e9-84bf-ca6cc263ddd1.png)

**Comment by azakus** [comment]
mwc-textfield is being re-implemented, and we'll make sure this is working before it is released.
