### ISSUE TITLE
Select missing option to only show helper text when invalid

### ISSUE THREAD

**Issue by christophe-g** [material-components/material-components-web-components#1838]
**Describe the bug**
- Helper text on mwc-select is always visible. 
- `helperPersistent` does not change the behavior on focus/blur

**To Reproduce**
1. https://material-components.github.io/material-components-web-components/demos/select/
2. set helper = 'myHelper' on a mwc-select
3. focus-in and out
4. helper not disappearing

**Expected behavior**
helper should not be visible when `helperPersistent` is not `true`:

>
> helper | string | "" | Helper text to display below the select. Display default only when focused.
> -- | -- | -- | --
> helperPersistent | boolean | false | Always show the helper text despite focus.
>

**Screenshots**
![image](https://user-images.githubusercontent.com/1168053/94146755-aff5bb80-fe74-11ea-88cf-fe4a1f9ecab8.png)

**Browser Version (please complete the following information):**
 - OS: Linux
 - Browser: chrome
 - MWC Version 0.18

**Comment by asyncLiz** [comment]
Thanks for the bug! This looks like a combination of inaccurate documentation and a missing feature.

For the select component, helper text is either always persistent or only displays in the invalid state. Unlike text field, there is no `helperPersistent` option to only show the helper text on focus.

> Why? On mobile, there isn't a strict "focus" state. When the user taps on a select, they open it, which will immediately hide the helper text due to the menu opening. This is why select behaves differently from text field and always shows its helper text.

So two things need to happen:

1. Our documentation needs to be updated and the `helperPersistent` section and code examples removed.
2. We need to add an option to only display the helper text when invalid. This option is currently missing from MWC.

**Comment by allan-chen** [comment]
Note that feature #2 is already supported by setting `validationMessage` attribute on the element, so this will be a docs fix only.
