### ISSUE TITLE
Slider interface is not documented in slider package README

### ISSUE THREAD

**Issue by hamza1311** [material-components/material-components-web-components#1848]
Unlike other components (like [`mwc-list`](https://github.com/material-components/material-components-web-components/tree/master/packages/list#mwc-list-2)), `Slider` interface [mentioned in `slider` component's Event section](https://github.com/material-components/material-components-web-components/tree/master/packages/slider) is undocumented.

**Comment by e111077** [comment]
Hello, slider is undergoing a complete rewrite for #523, so the documentation will not be updated as this documentation will be obviated by that issue, but `Slider` refers to the instance of the actual element itself. i.e. `<mwc-slider>` or `this`
