### ISSUE TITLE
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry'

### ISSUE THREAD

**Issue by jayeshrpatel** [material-components/material-components-web-components#1857]
I have tried to use <mwc-linear-progress> component in my 2 different components like fetch users and fetch modules.
My both components are placed in single HTML file so it gave below error because both component tried to define <mwc-linear-progress>.
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': this name has already been used with this registry.

Could you please guide how to use same component multiple time on same page?

**To Reproduce**
Create 2 Stencil web components.
NPM install mwc-linear-progress  in both components.
Use these 2 stencil web components in single page
It will throw an error  "Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry'"

**Comment by e111077** [comment]
Hello, it seems as if you have a dependency clash. The solution is to `npm ls @material/mwc-<name of duplicated component>` which should tell you which dependencies are causing this clash. You must then clear your node_modules, update your package.json dependencies, and then reinstall.

If this solution does not work, please paste in your `npm ls` output and your package.json dependencies here and i will reopen the issue
