### ISSUE TITLE
test engine fail to start locally

### ISSUE THREAD

**Issue by christophe-g** [material-components/material-components-web-components#1873]
**Describe the bug**
Testing engine fail to start locally

**To Reproduce**
As suggested in the readme:

1. git clone git@github.com:material-components/material-components-web-components.git mwc
1. cd mwc
1. npm install
1. npm run build
1. npm run test -- --packages=mwc-button

>  06 10 2020 17:10:25.506:ERROR [karma-server]: Server start failed on port 9876: Error: No provider for "framework:mocha"! (Resolving: framework:mocha)
 ERROR  Test failed. See above for more details.

**Expected behavior**
test engine starts 

**Proposed fix**
https://github.com/material-components/material-components-web-components/commit/b020c1fa8dd29d0c21e8758b022b65fe7fcc0a20 (change on the plugin part)
 

**Browser Version (please complete the following information):**
 - OS: Linux
- Node: v10 / v14

**Comment by e111077** [comment]
On Linux with node v14.8.0 and am unfortunately unable to replicate this behavior. Does this work if you revert your changes to the package.json, clear your node_modules, and reinstall, build, and test?

**Comment by christophe-g** [comment]
All right - the culprit is `pnpm`. Works as expected with `npm`. Sorry.

**Comment by e111077** [comment]
No worries, thanks for the reoort!
