### ISSUE TITLE
mwc-drawer: can't change background-color and border-color

### ISSUE THREAD

**Issue by frankiefu** [material-components/material-components-web-components#188]
Currently there is no easy way to change the default background-color (`#fff`) and border-color (`rgba(0,0,0,.12)`).

**Comment by azakus** [comment]
Related to https://github.com/material-components/material-components-web/issues/5242

**Comment by govis** [comment]
Priority: High since Jan 15, 2019 and it's still not possible to change the drawer background color

**Comment by Alos** [comment]
Would love if this issue is fixed 👍

**Comment by asyncLiz** [comment]
Going to close this as a duplicate of https://github.com/material-components/material-components-web-components/issues/953, which has more information related to the issue. Subscribe to that for further updates!
