### ISSUE TITLE
Will you be implementing mwc-tree?

### ISSUE THREAD

**Issue by jayhamilton** [material-components/material-components-web-components#1880]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by e111077** [comment]
Hello, we currently have no plans to implement a tree or tree-like navigation component for now. AFAIK the designers are working on a spec for a list-like navigation tree which as of now you should be able to compose on top of `mwc-list-item`, but all of that is in super early stages as https://material.io currently does not have any recommendations on such a component
