### ISSUE TITLE
Slider knob is always on the left when embedded in mwc-drawer content

### ISSUE THREAD

**Issue by jimmy-huang** [material-components/material-components-web-components#1885]
**Describe the bug**
When you have a mwc-slider element inside the drawer-content of mwc-drawer, and the slider has a preset value, the slider knob is not set to the value of the slider, but instead always set to the first value on the left.  This happens if the drawer is a modal or dismissed type of drawer.  If the drawer doesn't move, then the bug is not reproduced.

**To Reproduce**

Add a `<mwc-slider>` inside the drawer content in the demo

```
  <mwc-drawer hasHeader type="modal">
    <span slot="title">Drawer Title</span>
    <span slot="subtitle">subtitle</span>
    <div class="drawer-content">
      <mwc-slider step="1" pin markers min="0" max="10" value="5"></mwc-slider>
    </div>
    <div slot="appContent">
      <mwc-top-app-bar>
        <mwc-icon-button slot="navigationIcon" icon="menu"></mwc-icon-button>
        <div slot="title">Title</div>
        <mwc-icon-button slot="actionItems" icon="cast"></mwc-icon-button>
        <mwc-icon-button slot="actionItems" icon="fingerprint"></mwc-icon-button>
      </mwc-top-app-bar>
      <div class="main-content">
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </div>
    </div>
  </mwc-drawer>
```

**Expected behavior**
When you toggle the drawer, the mwc-slider value should be set to 5, and the knob on the slider should be set to 5.

**Screenshots**
Current behavior
![Screenshot from 2020-10-08 15-11-45](https://user-images.githubusercontent.com/1037247/95519580-37b1ee80-097a-11eb-918d-344e8aa48bb7.png)

Expected behavior
![Screenshot from 2020-10-08 15-13-17](https://user-images.githubusercontent.com/1037247/95519587-3da7cf80-097a-11eb-90f8-063613cfbeec.png)

**Browser Version (please complete the following information):**
 - OS: Linux/ChromeOS
 - Browser chrome
 - Version [85.0.4183.83]

**Comment by e111077** [comment]
Slider is still undergoing a rewrite to material 2. This means all work on issues related to it will not be worked on until that migration has finished in which case hopefully this issue is obviated.

**Comment by Jklein64** [comment]
I was running into the same problem but my slider was inside of a `mwc-dialog` in addition to an `mwc-drawer`.  It isn't perfect (as you can see in the gif), but I came up with a cheap workaround.  Calling the slider's `layout()` method as soon as it is visible and not still animating puts it in the right position. 

```js
// this is for a dialog, but if you can find a way to catch when the drawer is done opening it would work too.
 dialog.addEventListener("opened", function oneShot() {
    dialog.removeEventListener("opened", oneShot)
    slider.layout()
})
```
![slider in drawer (in dialog)](https://user-images.githubusercontent.com/43863752/102680808-ded8b080-4189-11eb-9cfd-325e7eec3ff2.gif)

**Comment by christophe-g** [comment]
This is also happening when slider is embedded within a `mwc-menu`.

**Comment by gullerya** [comment]
Hopefully I can add some more general observation on this one: slider used `getBoundingClientRect` and calculates the transform of the thumb from the `width` of that one.
In any case, when slider is rendered with 'zeroised' bounding client rect (for example any time it is rendered in `display: none` container) - the thumb is mislocated.
Since the client rect part of the slider is not reactive, the same mislocation happens when slider is being resized.

My solution to this issue, roughly, is to use `ResizeObserver` and trigger `layout` on each resize (with some naive debounce).

Hope this help to triage the issue.

Do you think the migration to Material 2 would address it?

Would you like to get a PR with such a fix?

**Comment by e111077** [comment]
Hello, we already have an implementation of material 2 slider in an internal CL that's not finalized yet. We're working with some theming tokenization with it to prepare it for future endeavors. Will also try to solve this issue before we release it on MWC at all.

**Comment by gullerya** [comment]
Great, thanks!
Can we possible leave this issue opened until the fix is released, so that we can track it and remove our own fix in the future?

**Comment by jimmy-huang** [comment]
Yeah, this is great, thanks for the update.

**Comment by e111077** [comment]
update: working on the m2 slider right now and expect a release possibly in the next week or so
