### ISSUE TITLE
Textfield validation partially occurs on input and partially occurs on blur

### ISSUE THREAD

**Issue by allan-chen** [material-components/material-components-web-components#1889]
**Describe the bug**
Currently textfield calls MDC foundation's [`setValue()`](https://github.com/material-components/material-components-web-components/blob/5f6894b191aacdb7da61e0e9f91bae96169fb190/packages/textfield/mwc-textfield-base.ts#L300) on each character typed, which triggers validation at MDC layer. Separately, MWC layer validation (which shows/hides validation/helper text) is only triggered on blur. This inconsistency leads to behavior where typing to cause invalid input causes red "invalid" styling realtime, but the validation message only occurs on blur.

**To Reproduce**
1. Go to demo and set required=true, validationText to 'please enter nonempty value'
2. Type one or more characters into the input
3. Without losing focus, backspace to delete all characters from input
4. Notice red error styling, but validation text is not shown. This is because `setValue` is called every time a char is typed which causes MDC foundation to add `mdc-textfield--invalid` class, but actual MWC validation doesn't occur until blur.

**Expected behavior**
We should be consistent - either do validation styling + show error message on change only or on blur only, but not half & half.

**Additional context**
We may need to replace `setValue` call with something else - `setValue` is intended to replace the entirety of textfield's value instead of handling char by char changes.

**Comment by e111077** [comment]
ugh intended behavior is that it shouldn't validate at all unless you have `autovalidate`. It works as intended when that is set. Other than that, we have to find some way to prevent validation on `@input` in the foundation unless that is true
