### ISSUE TITLE
Duplicate identifiers errors with Stencil for some components

### ISSUE THREAD

**Issue by rutwick-alic** [material-components/material-components-web-components#1898]
**Describe the bug**
We were using MDC for development via their material-web-components package, and now we are slowly moving to these components. When I use the mwc-formfield along with mwc-checkbox, I run into a bunch of 'Duplicate Identifiers' errors. This also happens with the mwc-slider component. Stuck very badly.

**Screenshots**
![error](https://user-images.githubusercontent.com/72026410/95860646-f48ebb80-0d7d-11eb-8a6e-0d2c135aaaa0.png)

**Additional context**

**Comment by taylor-vann** [comment]
Hey @rutwick-alic! Thanks for submitting.

Currently, I see you using both: mdc.Base.d.ts and mdc.base.d.ts. So your error makes sense.

There is a duplicate identifier because you are exporting conflicting namespace declarations through those two files but I think that shouldn't be a problem unless you're using both classes in the same file.

But before we go further, could you provide a little more code so we have some better context :) We might be able to help you more!

**Comment by rutwick-alic** [comment]
Hey @taylor-vann!

We have the 'material-components-web' package installed, from which we were using some other components earlier, which we are now doing away with and replacing with mwc-components. I figured out that the issue is with the @material/base package, more so with the versions. Because the above package has installed base version 7, whereas the mwc-formfield, mwc-slider etc. use base version 8.0 (canary something). I tried something with npm-force-resolutions so both of them refer to the same version of the @material/base package, but then Sass is not able to find the mixins, however the duplicate identifiers issue doesn't reproduce.

There is nothing in my code! Just a Stencil component that is trying to render a slider. I am just getting started with a new component and this is what I face. Here:

```
import { Component, h} from '@stencil/core';
import '@material/mwc-slider';

@Component({
  tag: 'my-component',
  styleUrl: 'my-component.scss',
  shadow: false,
})

export class MyComponent {
    render() {
        return (
            <mwc-slider
                step="5"
                pin
                markers
                max="50"
                value="10">
            </mwc-slider>
        )
    }
}
```

With resolving the dependency using npm-force-resolutions, the duplicate identifiers issue does not occur. But I get this error, and I have used the mdc textfield for some other component in my application:

sass-error
Can't find stylesheet to import.

/......\node_modules\@material\mdc-text-field.import.scss
1 @forward "@material/animation/variables" as mdc-animation-*;
2 @forward "@material/base/mixins" as mdc-base-*; <--- ERROR HERE

**Comment by rutwick-alic** [comment]
@taylor-vann Hey I have posted a question here too, with better details and a new use case!

https://github.com/material-components/material-components-web/issues/6533

**Comment by taylor-vann** [comment]
thanks @rutwick-alic

marking as duplicate from [6533](https://github.com/material-components/material-components-web/issues/6533)

the preferred recommendation (and possible solutions) will be posted in issue
[6533](https://github.com/material-components/material-components-web/issues/6533#issuecomment-710452803)

Also thanks @joyzhong !
