### ISSUE TITLE
Implement List component

### ISSUE THREAD

**Issue by dfreedm** [material-components/material-components-web-components#190]

**Comment by fernandopasik** [comment]
Is this blocked from a particular issue in https://github.com/material-components/material-components-web ?

**Comment by e111077** [comment]
Hello, it's under active development in the mwc-select branch

**Comment by fernandopasik** [comment]
Thanks @e111077 for landing this one  in https://github.com/material-components/material-components-web-components/pull/763

**Comment by dfreedm** [comment]
@e111077 can this be closed?
