### ISSUE TITLE
<mwc-dialog> Safari crash report on demo

### ISSUE THREAD

**Issue by jpic** [material-components/material-components-web-components#1907]
Hello !

A safari user has reported the modal crashes Safari on https://oss.yourlabs.me/autocomplete-light/

We're using the same scripts as your dialog demo page, I asked the user if they could reproduce on https://material-components.github.io/material-components-web-components/demos/dialog/

They said yes indeed.

I'm sorry but I have no more to offer (I run Linux without Safari)

Have a great day

**Comment by taylor-vann** [comment]
closing as deduplicate #1908 #1720
