### ISSUE TITLE
use em rather than rem in shadow dom

### ISSUE THREAD

**Issue by colscott** [material-components/material-components-web-components#1911]
**Is your feature request related to a problem? Please describe.**
We have an existing application that we are trying to migrate to material web components. One of the current issues we are facing is that our root font size is 10px.

`:root { font-size: 62.5%; }`

Changing this value at this point it in time would require a lot of work.
This makes the text in the TextField for example very small.

**Describe the solution you'd like**
Since Material is using a shadow DOM it should be safe to use em units inside the component shadow DOM. Current behavior could be maintained by setting a font-size of 1rem on the host of the component.

`:host {
    font-size: var(--mdc-typography-subtitle1-font-size, 1rem);
}`

Then use em units inside the component which will be based on the font size of the host.

This is also nice because, as a user, I can now set the font-size using the CSS property, or by simply setting the font-size on the Web Component overriding it's default of 1rem.

Also, things like the TextField label, which if changed to 0.75em, would automatically scale with the set font-size where at the moment it seems to be hard coded to 0.75rem and does not change with any CSS property.

**Describe alternatives you've considered**
The current work around for us is to extend the Lit Element classes and override the CSS.

**Comment by taylor-vann** [comment]
Hey @colscott, thanks for reaching out.

We use rem to ensure component text will scale across a document as the browser font-size changes.

Rem allows our typography to consistently scale with a the browser. It helps address usability and accessibility concerns.

**Comment by colscott** [comment]
Hi @taylor-vann, wouldn't it still scale by setting 1 rem at the shadow host of the Web Component as in the example above? The idea being that the shadow host of the Web Component baselines itself at a default of 1 rem. Then it's content in the shadow tree would use em units. But the em is relative to the 1rem in the shadow host so should scale.

After reading more about material [type system](https://material.io/design/typography/the-type-system.html#type-scale). is this because we're not meant to change the size of the font (even though in our case it's to correct it back to the default 1rem = 16px as we have it set in the root to 1 rem = 10px)?
