### ISSUE TITLE
Is it possible to turn off the ripple effect on Tab Bar?

### ISSUE THREAD

**Issue by shirleyhsliu81** [material-components/material-components-web-components#1946]
Hi There,

Is there a convenient  way to remove the ripple effect on Tab Bar?

Many Thanks,
Shirley

**Comment by taylor-vann** [comment]
hey @shirleyhsliu81 

Unfortunately the ripple behavior is apart of Tab Bar specs.
There are [styling](https://github.com/material-components/material-components-web-components/blob/46b50e2e7c199df71bbb1693cd5a478810fa27f3/packages/ripple/README.md) and [theming](https://github.com/material-components/material-components-web-components/blob/master/docs/theming.md) options you can override. But ripples are an expected interaction pattern required of material web components.
