### ISSUE TITLE
Allow users to define icon font themselves

### ISSUE THREAD

**Issue by azakus** [material-components/material-components-web-components#195]
Users would like to be able to load their own icon font for the `Material Icons` family.
We need to determine if this should be an opt-in, or require users to load the font themselves always.

**Comment by jonmann20** [comment]
I've been experimenting using this with a LitElement app.  I spent some time trying to do this (and also prevent FOUC).  It was far easier to just use SVG.  I believe this is similar to how iron-icon worked under the hood.  Here is what I came up with:
https://gist.github.com/jonmann20/411f5b8de91536f9bb2561f72cbfe59a

**Comment by Yuen92** [comment]
Also can you provide a way to remove the dependency to the icon like PolymerElement provides for the font roboto : 
`window.polymerSkipLoadingFontRoboto = true;`

Proposition : 
`window.mwcSkipLoadingIcon = true;`

PolymerElement Reference : 
> https://github.com/PolymerElements/font-roboto/blob/master/roboto.js

What do you think @azakus ?

**Comment by JosefJezek** [comment]
good solution is here https://github.com/andreasbm/weightless/tree/master/src/lib/icon#-%EF%B8%8F-load-the-icon-font
