### ISSUE TITLE
mwc-select: An editable dropdown menu

### ISSUE THREAD

**Issue by zsarnett** [material-components/material-components-web-components#1957]
**Is your feature request related to a problem? Please describe.**

When using the `mwc-select` element, I can not allow my users to enter a value that's not listed in the select element. 

**Describe the solution you'd like**

I would like to be able to set an attribute on `mwc-select` that forces the element to allow values, not in the element. This would also allow setting the value of the element to a value, not in the list items.

Example: https://material.io/components/menus#exposed-dropdown-menu -> Variations -> Editable dropdown menu

**Describe alternatives you've considered**

My current workaround I have chosen is to use Vaadin Combo Box with an MWC Text field (to stay with Material Guidelines)

**Additional context**

I understand the element is recently released and more features will come with time and a variation of the element is probably not a priority. Just looking to note this in the repo as a Feature Request for tracking purposes.

**Comment by dfreedm** [comment]
There are currently no plans to build a combobox like you describe here in the Material spec. Using a Vaadin Combo Box with a MWC text field is probably the most appropriate solution.

**Comment by christophe-g** [comment]
@dfreedm - I am also looking for this behavior, which is actually described in the specs (https://material.io/components/menus#exposed-dropdown-menu): 

> Behavior
> 
> Upon selecting an item, an exposed dropdown menu updates to display that item. In some cases, **it can accept and display user input (whether or not it’s listed as a menu choice)**.

Any chance to get this revived ? 
Thanks
