### ISSUE TITLE
Remove "extra row" from top-app-bar

### ISSUE THREAD

**Issue by azakus** [material-components/material-components-web-components#197]
This is complicated to implement, and not supported by all MDC wrappers.

**Comment by straversi** [comment]
Discussion in #228 highlights how extra row is utilized for adding tabs to top app bars, including in pwa-starter-kit.

**Comment by jsilvermist** [comment]
My use case for this is for a secondary title with some dynamic effects to produce a similar effect to what was present in the first Polymer Starter Kit (a long time ago).

**Comment by straversi** [comment]
After reviewing, we preempted MDC Web by implementing this, and we'd like to avoid that and wait for them to release features first. So this issue will remain valid. `extraRow` will return when it is released in MDC Web.
