### ISSUE TITLE
mwc-textfield missing smart search function

### ISSUE THREAD

**Issue by shirleyhsliu81** [material-components/material-components-web-components#1976]
mwc-textfield doesn't have smart search function, which should be similar to ReactSearchAutocomplete in React components

**Comment by asyncLiz** [comment]
Thanks for the issue!

At the moment we do not have plans to implement the autocomplete component, but it is possible to do so yourself using `<mwc-textfield>` and `<mwc-menu>`. I'd recommend joining [our Slack](https://www.polymer-project.org/slack-invite) and asking around in the `#material` room for ideas and suggestions (I know a few people have created implementations themselves).

You can also subscribe to https://github.com/material-components/material-components-web/issues/45 for future updates on an official autocomplete implementation.

**Comment by linhdoan24** [comment]
![image](https://user-images.githubusercontent.com/24908232/149129423-0a414fcd-a482-4a97-ab57-c514acbd5110.png)
Help me please. how to fix this?
