### ISSUE TITLE
[mwc-textfield] Remove styling

### ISSUE THREAD

**Issue by masaoliou** [material-components/material-components-web-components#1987]
The in-line styling unnecessarily consumes control width:
`.mdc-text-field {padding:0 16px;}`

Please remove that in-line styling from file `mwc-textfield-css.js`.

The attached screen shot shows the negative side effect - the width being too narrow for the display of _mwc-textfield_ values of _number_ type in table cells - of this in-line styling.

![mwc-textfield](https://user-images.githubusercontent.com/696936/100721611-828c3780-33fa-11eb-8e1b-41a9caa659a8.png)

**Comment by e111077** [comment]
Hello, this is not a good place to use mwc-textfield. Your cells should use an <input>since most of the benefits and stylings of mwc-textfield are not being used at all in this case and does not follow material density guidelines

**Comment by masaoliou** [comment]
@e111077 
Is it the `input` element you suggest?

Thank you very much!

**Comment by e111077** [comment]
correct!
