### ISSUE TITLE
Live/Hot Reloading can be broken due to unnecessary reimport (use include guards on Custom Element Registry)

### ISSUE THREAD

**Issue by rogueyoshi** [material-components/material-components-web-components#2015]
**Describe the bug**
Some Live/Hot Reload features in certain test environments break since they don't clear the Custom Element Registry. But this is due to not having an include-guard (checking if it's already registered) at the component-level to avoid re-registering the web components.

**To Reproduce**
1. Load up the Svelte REPL Example https://svelte.dev/repl/8fd85f8aa1e84182af632d4e9d930ea0?version=3.31.0
2. Attempt an edit to an element
3. Notice REPL breaks until manual reload

**Expected behavior**
What should be happening is that the content in the preview updates instantly, but instead it causes an unrecoverable error.

**Browser Version (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 87.0.4280.88 (Official Build) (64-bit)

**Comment by asyncLiz** [comment]
Thanks for the detailed report!

Unfortunately our team believes that hot module reloading is a concern that should be dedicated more towards development tools (such as webpack-dev-server), and not a responsibility of the libraries that consume native platform features. Doing so would add additional bloat that would be unsuitable for production usage.

In the realm of HMR with web components, there are many strategies, such as [using an iframe](https://dev.to/nicolalc/customelements-webcomponents-live-reload-2m3h). [Storybook recommends a full page reload](https://developer.aliyun.com/mirror/npm/package/@storybook/web-components#user-content-setup-page-reload-via-hmr). There's also a [discussion in LitElement](https://github.com/Polymer/lit-element/issues/673) about HMR and the pros/cons about one library that adds runtime HMR features.

Ultimately, there is not a unified consensus with how to address HMR with custom elements right now, so it is our belief that we should not add runtime features dedicated to it or any specific build system's strategy.
