### ISSUE TITLE
mwc-checkbox has no `setCustomValidity`

### ISSUE THREAD

**Issue by YonatanKra** [material-components/material-components-web-components#2038]
Hi,
I've just found out `mwc-checkbox` does not implement `setCustomValidity`. 
I'd be happy to take this as a task. Are there any reasons why this was not implemented like in the rest of the form fields?

**Comment by taylor-vann** [comment]
We are aiming for a light experience with mwc-checkbox: checked or not checked. Implementing a `setCustomValidity` method was considered overkill.

However, we're always open to new feature requests. If you can provide a use-case scenario and examples, we'll examine this further!

**Comment by asyncLiz** [comment]
Closing for now since there are no plans to implement this. Feel free to comment with your use case if you still need this functionality!
