### ISSUE TITLE
mwc-dialog add shadow part to content element

### ISSUE THREAD

**Issue by dave52** [material-components/material-components-web-components#2039]
**Is your feature request related to a problem? Please describe.**
`mwc-dialog` provides some customization with CSS custom properties but is quite limited.

**Describe the solution you'd like**
If `part="custom-part-name"` was added to the content element where it renders in the shadow DOM, a lot more style capability would be available, such as styling scrollbar (when overflow-y), custom margin/padding on the card, etc.

![image](https://user-images.githubusercontent.com/6565619/103682175-1d25ec00-4f4e-11eb-9381-40a690f3d8f3.png)

Example based on current (screenshot above) modified with shadow part...
`<div part="custom-part-name" id="content" class="mdc-dialog__content" >...</div>`

**Describe alternatives you've considered**
Another solution would be exposing more CSS custom properties but would be more effort than shadow part.

**Comment by taylor-vann** [comment]
Hey @dave52 thanks for submitting

Our CSS Custom Properties listed in our [our docs](https://github.com/material-components/material-components-web-components/tree/master/packages/dialog) support certain theme-ing options.

Unfortunately, we don't currently plan on exposing more properties

**Comment by dave52** [comment]
Would you kindly reconsider adding this as a feature :)

By adding the shadow part to the mark up like this:
```
<div part="foo" id="content" class="mdc-dialog__content" >...</div>
```

It opens the door to lots of style changes on this specific element, without being locked down to exposed CSS custom props, and it is a very low risk change.

Element styling:
```
mwc-dialog::part(foo) {
  // CSS to hearts content
  background: hotpink;
  margin: 4rem;
}
```

...and scrollbar styling:
```
mwc-dialog:part(foo)::-webkit-scrollbar {
  width: 1em;
}
 
mwc-dialog:part(foo)::-webkit-scrollbar-track {
  box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.3);
}
 
mwc-dialog:part(foo)::-webkit-scrollbar-thumb {
  background-color: darkgrey;
  outline: 1px solid slategrey;
}
```
