### ISSUE TITLE
adapter object undefined

### ISSUE THREAD

**Issue by BedfordPeterson** [material-components/material-components-web-components#2097]
On mwc-list-foundation.js, I'm getting console errors because the adapter object is undefined.  When I inspect "this" I can see "adapter_" vs "adapter".

![image](https://user-images.githubusercontent.com/1258403/105472832-62def600-5c6a-11eb-959d-19eef3758b01.png)

![image](https://user-images.githubusercontent.com/1258403/105473016-99b50c00-5c6a-11eb-8e75-8f7d46288f47.png)

![image](https://user-images.githubusercontent.com/1258403/105473210-d3861280-5c6a-11eb-9e87-ee7dcdf8af6f.png)

package.json

"dependencies": {
    "@ai/webdev": "^0.4.2",
    "@material/dom": "^9.0.0",
    "@material/mwc-checkbox": "^0.20.0",
    "@material/mwc-formfield": "^0.20.0",
    "@material/mwc-icon-button": "^0.20.0",
    "@material/mwc-list": "^0.20.0",
    "@material/mwc-ripple": "^0.20.0",
    "@material/mwc-top-app-bar": "^0.20.0",
    "@material/theme": "^8.0.0",
    "@polymer/polymer": "^3.4.1",
    "@webcomponents/webcomponentsjs": "^2.4.3",
    "lit-element": "^2.4.0",
    "lit-html": "^1.3.0",
    "navigo": "^8.6.4"
  },
  "devDependencies": {
    "@babel/core": "^7.12.3",
    "@babel/plugin-proposal-class-properties": "^7.12.1",
    "@babel/plugin-proposal-decorators": "^7.12.1",
    "@babel/preset-env": "^7.12.1",
    "chai": "^4.2.0",
    "mocha": "^8.2.1",
    "sinon": "^9.2.1"
  }

**Comment by dfreedm** [comment]
Hmm, it looks like `adapter_` was renamed to `adapter` in MDC a while ago (https://github.com/material-components/material-components-web/pull/5959).

Can you double check that you have the latest version of MWC and MDC?

**Comment by e111077** [comment]
Hello, in a previous comment we have asked for a bit more clarification due to us having trouble reproducing your error. Please respond within 5 days otherwise we will close this issue for being stale. If you comment after the bug closure with the requested feedback, we will reopen the issue

**Comment by BedfordPeterson** [comment]
dist/mdc.list.js -- 5.0.0-canary.a1a0deb3e.0
@material/mwc-list -- 0.20.0

I'm also referencing another published module that is using @material/mwc-list -- 0.13.0.  

When I have time, I will get the source for that project and upgrade it and see if it addresses the issue.  (It's the item listed above under packages, @ai/webdev": "^0.4.2.)

**Comment by e111077** [comment]
`npm dedupe` may help. I don't think the API of list has changed between those versions very much. I only see one breaking change:

https://github.com/material-components/material-components-web-components/blob/master/CHANGELOG.md#v0140---2020-03-19

**Comment by BedfordPeterson** [comment]
That didn't work.  Thanks for the suggestion.

I would say lets close this issue for now.  And later when I'm able to upgrade the other private npm package, I can see then if it's still an issue.

But I'm open to trying something else if you would like me to.

**Comment by e111077** [comment]
I will open on request
