### ISSUE TITLE
mwc-slider's pin attribute does not work without setting the step attribute

### ISSUE THREAD

**Issue by lozandier** [material-components/material-components-web-components#2108]
**Describe the bug**
`mwc-slider` pin functionality does not work without setting the `step`. This breaks the principle of least surprise and is not behavior shared w/ `paper-slider` (Material 1 version of this component)

**To Reproduce**
1. Declare `mwc-slider` w/ `pin` attribute with a `min` & `max` attributes set without `step` (use of `markers optional)
2. View `mwc-slider` instance in the browser & interact with its knob

**Expected behavior**
Knob shows pin UI displaying values

**Screenshots**

**Browser Version (please complete the following information):**
 - OS:  MacOS Catalina & Big Sur
 - Browser: Chrome
 - Version: 87

**Additional context**
Discussed with @dfreedm & @e111077

**Comment by e111077** [comment]
Working on M2 slider implementation, and this unfortunately is WAI as this is how the spec dictates it. A quick summary of spec behvaior of the pin / value indicator:

shows for conditions:
  - step is defined / is discrete and
    - has focus
    - or is range and has hover
    
This is WAI but I will keep open to make sure that this is documented clearly.
