### ISSUE TITLE
mwc-slider does not snap to values corresponding to the step attribute (& visually represented by the markers attribute) if set to a non-integer

### ISSUE THREAD

**Issue by lozandier** [material-components/material-components-web-components#2109]
**Describe the bug**
If a non-integer is set to the `step` attribute of `mwc-slider` , the slider does not behavior correctly. When interacted with, `mwc-slider` instances will skip non-integer values to the next integer. 

 The UI toggable by `marker` & `pin` has no problem respecting such values, making this behavior extremely confusing. 

This behavior occurs even when the initial minimum value is a non-integer valid within the `min` & `max` of an instance.

This behavior is completely deviant from `paper-slider`; the Material 1 version of this component. 

**To Reproduce**
1. Instantiate or in mark-up define a `mwc-slider`
2. Set the `step` attribute to a non-integer (i.e. `0.5`)
3. Set the `markers` attribute ; optionally the `pin`, `min` & `max` attributes to more clearly identify the problem (the latter two should have sensible bounds:

```html
<mwc-slider
    pin
    markers
    min="0"
    max="2"
    value="0.5"
    step="0.5">
</mwc-slider>
```

4. Interact with the knob of the slider back-n-forth 

**Expected behavior**
That the component can step to all possible values of the slider based on the `step`  & `max` attributes aligning with how the Material 1 version of this component, `paper-slider`, behaves. 

**Screenshots**
Video demonstration of problem: https://user-images.githubusercontent.com/1223224/105733034-efe1b380-5ee5-11eb-88b1-70745eeac652.mov

**Browser Version (please complete the following information):**
 - OS: MacOS Catalina & Big Sur
 - Browser: Chrome
 - Version: 87.0.4280.141+

**Additional context**
Discussed in detail w/ @dfreedm & @e111077

**Comment by e111077** [comment]
I am working on the M2 implementation of slider right now, and this is fixed there. Keeping open until that is merged

**Comment by christophe-g** [comment]
> I am working on the M2 implementation of slider right now, and this is fixed there. Keeping open until that is merged

Thanks @e111077, this is good to know. Any tentative ETA ?
