### ISSUE TITLE
Movable/sizable mwc-dialog

### ISSUE THREAD

**Issue by nicolasr75** [material-components/material-components-web-components#2116]
Are there any plans to support movable and/or sizable (modal) `mwc-dialogs`?

Or is this by intention not supported?

_Google Drive/Sheets_ f.e. includes a movable Help dialog (although it is not modal), or a movable modal dialog _File -> Document details._

A movable dialog can be useful to be able to unhide the underlying content in order to fill out a form in a dialog. F.e. you have a list of items and a dialog to create a new item. While filling out the dialog form you may want to compare your entries to existing items in the list which unfortunately may be partly hidden by the dialog.

A sizable dialog can be useful, if a dialog displays a longer list of items or a longer text. If the content of the dialog is not known in advance, there may be no reasonable default size. Using scrollbars is one solution but sometimes a user has a large enough screen to view the entire content at once.

**Comment by e111077** [comment]
Hello, unfortunately there is nothing in the official material spec for a movable dialog which determines whether we will implement a component variant.

Though a quick fix would be to subclass our element and simply add `position:fixed` to the `.mdc-dialog__container`, insert a drag bar, and add `pointerdown` `pointermove` and `pointerup` listeners that add `left` and `top` as you drag it around (and make sure it can't go off screen). Here's an example of one I whipped up for an internal project at google:

https://gist.github.com/e111077/1bb50247396d382a077300c1b47991c5

**Comment by nicolasr75** [comment]
Thanks nevertheless for sharing your ideas and code.
