### ISSUE TITLE
Always float label on mwc-select

### ISSUE THREAD

**Issue by stucker71** [material-components/material-components-web-components#2124]
**Is your feature request related to a problem? Please describe.**
A useful option would be to always float label on mwc-select. A blank or empty string is a valid and useful value to have as an mwc-select option. However, you may want the user to view 'None' rather than simply a blank option. For example:

```
<mwc-select label="filled">
  <mwc-list-item selected value="">None</mwc-list-item>
  <mwc-list-item value="0">Item 0</mwc-list-item>
  <mwc-list-item value="1">Item 1</mwc-list-item>
  <mwc-list-item value="2">Item 2</mwc-list-item>
  <mwc-list-item value="3">Item 3</mwc-list-item>
</mwc-select>
```

At the moment this would cause the non-floating label 'filled' to overlay on top of the display value 'None' (not good). Taken from API - NOTE: The label will not float if the selected item has a falsey value property (in this case value of "" would be falsey).

**Describe the solution you'd like**
A boolean property alwaysFloatLabel.

**Describe alternatives you've considered**
No other solution possible other than to have a blank display value which some may consider not user friendly or intuitive.

**Additional context**

**Comment by e111077** [comment]
tracking b/178730083

**Comment by e111077** [comment]
Spoke to design and they said that if there is no content the label should not be able to float in the select, so we will not be adding functionality in our component. Perhaps achievable via subclassing our component, but it is not a use case we will offer support
