### ISSUE TITLE
Use other icon fonts with MWC

### ISSUE THREAD

**Issue by maicol07** [material-components/material-components-web-components#2127]
**Is your feature request related to a problem? Please describe.**
I can't use other icon fonts that envolves classes with MWC components

**Describe the solution you'd like**
I know you can use <mwc-icon> with the --mdc-font-icon CSS var, but this enforces to use the Material Design Icons building system (the i tag + the icon name inside the tag) while other well-known icon fonts like [Font Awesome](https://fontawesome.com/) or [Material Design Icons](https://materialdesignicons.com/) uses CSS classes to render icons. The two methods aren't compatible each other

**Describe alternatives you've considered**
At the moment the only way to do this is to use the standard material web components

**Additional context**

**Comment by e111077** [comment]
Hello, in most all cases where we have an icon, we have a `<slot>` as well so that users can slot in their own icon DOM. Is there a component that you are using that currently does not have a slot and does not yet have an issue filed for it?

**Comment by maicol07** [comment]
@e111077 what about the MWC button?

**Comment by e111077** [comment]
mwc-button has a slot named icon as well which you should be able to use like this:

```html
<mwc-button label="add">
  <i slot="icon" class="fa plus"></i>
</mwc-button>
```

documentation is in readme slots section
https://github.com/material-components/material-components-web-components/tree/master/packages/button#slots

I am aware there are certain components that are missing the slot, but I think we should have bugs filed for them. Are you currently running into one of these components?

**Comment by maicol07** [comment]
Didn't know about slots (It's the first time I use MWC)

**Comment by maicol07** [comment]
Works! Thank you!
