### ISSUE TITLE
Allow to set buttons border radius

### ISSUE THREAD

**Issue by maicol07** [material-components/material-components-web-components#2133]
**Is your feature request related to a problem? Please describe.**
At the moment standard buttons border radius is set to 4px and it's impossible to change via CSS.

**Describe the solution you'd like**
Allow to change the border radius of the mwc-button component. This will allow us to get rounded buttons, like this one:
![immagine](https://user-images.githubusercontent.com/9463142/106593743-7d11b180-6551-11eb-959b-e1e7efad4a81.png)

**Describe alternatives you've considered**
Using the ::shadow CSS selector but it doesn't seem to work...
The only workaround I found is using JS:
```js
document.querySelector('.mwc-button--rounded').shadowRoot.firstElementChild.style = 'border-radius: 100px;';
```

**Comment by taylor-vann** [comment]
Hey @maicol07

Thanks for submitting. We have custom properties that affect 'shape' similar to your example :)

Unfortunately our docs need to be updated to include 'shape' in our theming :(

I'll fix the docs and update here!

**Comment by asyncLiz** [comment]
Fixed in https://github.com/material-components/material-components-web-components/pull/2179
