### ISSUE TITLE
mwc-top-app-bar(-fixed): Set bottom border

### ISSUE THREAD

**Issue by maicol07** [material-components/material-components-web-components#2134]
**Describe the solution you'd like**
A CSS variable to set the Top App Bar bottom border width and color

**Describe alternatives you've considered**
The only workaround I found is using JS:
```js
document.querySelector('mwc-top-app-bar-fixed').shadowRoot.firstElementChild.style = 'border-bottom: 1px solid #e0e0e0;';
```

**Comment by aress31** [comment]
Border or/and shadow would be better.

**Comment by taylor-vann** [comment]
Hey @maicol07 and @aress31

There is a CSS Custom Property you can try to override:

`--mdc-top-app-bar-fixed-box-shadow`

However that property only affects mwc-top-app-bar-fixed when content is scrolled underneath. More information can be found [here](https://github.com/material-components/material-components-web-components/tree/master/packages/top-app-bar-fixed#css-custom-properties).

Outside of that property, there isn't a recommended way of overriding styles in mwc-top-app-bar-fixed.
