### ISSUE TITLE
Document dialog modal behaviour

### ISSUE THREAD

**Issue by gullerya** [material-components/material-components-web-components#2149]
I've not found a way to make dialog behave as modal - reject any clicks on scrim and prevent dialog from being closed.

Would be great to know is such an option exists or any plans to implement it?

Thanks in advance!

**Comment by dfreedm** [comment]
Hey @gullerya!

You can do this today by setting `scrimClickAction=""` and `escapeKeyAction=""` on the `<mwc-dialog>`.

Here's a demo: https://jsbin.com/lofedozate/edit?html,output

We don't have this behavior documented in dialog, so we'll add that. 

Thanks!

**Comment by gullerya** [comment]
Thanks @dfreedm ! 
Eventually we've found those 2, but yes, I wasn't sure about the API-wise designation of them (also due to lack of documentation).
Assuming from you answer that there is no plans to provide any kind of direct API, (something like `isModal`), right?

**Comment by asyncLiz** [comment]
At the moment, no, there are no plans to provide a convenience property that sets both of them. The concept of a "modal" dialog can be a bit more opinionated on how the user is able to dismiss the modal.

Instead, we'd rather provide granular options on how the modal can be dismissed.

**Comment by gullerya** [comment]
Thanks!

**Comment by asyncLiz** [comment]
We're gonna keep this open to address and fix documentation issue so it's more obvious how others can do this 🙂

**Comment by asyncLiz** [comment]
This has been fixed in the latest version
