### ISSUE TITLE
mwc-slider doesnt submit when used in a form

### ISSUE THREAD

**Issue by lsatheeshkumar** [material-components/material-components-web-components#2157]
**Describe the bug**
When the slider component is embedded into a form, the expectation is that it should send the value on form submit however its not happening

**To Reproduce**
1) Embed the mwc-slider into a form with post method
2) Submit the form
3) Check if the slider value is sent on submitting the form

**Expected behavior**
The current value of the slider should be sent on form submit

**Screenshots**

**Browser Version (please complete the following information):**
 - Browser [e.g. chrome]

**Comment by dfreedm** [comment]
Duplicate of #289.

We need to implement form submission in several components, and that is the umbrella issue.
