### ISSUE TITLE
No label on outlined mwc-textfield using default value

### ISSUE THREAD

**Issue by xkotj** [material-components/material-components-web-components#2166]
**Describe the bug**
While using **outlined** `<mwc-textfield>` with default value in `<mwc-dialog>` there is no label in upper left corner, just blank space

**To Reproduce**
```
<mwc-dialog id="dialog" heading="My Dialog">
  <mwc-textfield id="port" outlined label="Port" type="number" min="0" max="65535" value="8834" required autoValidate></mwc-textfield>
<mwc-dialog>
```

**Expected behavior**
Show label floated upper left corner as it should be.

**Screenshots**
![image](https://user-images.githubusercontent.com/42933817/107944366-49da1400-6f8e-11eb-84aa-b7889a817a94.png)

**Browser Version (please complete the following information):**
 - OS: Windows 10
 - Browser chrome, edge - chromium
 - Version  88.0.4324.150

**Comment by asyncLiz** [comment]
This is a [known issue with rendering elements initially with `display: none`](https://github.com/material-components/material-components-web-components/tree/master/packages/textfield#methods). To solve it, wait for the dialog's `opened` event and call `layout()` on the text field to re-calculate the notched outline after its parent has a display width.

Let us know if you run into any other problems!
