### ISSUE TITLE
MWC Drawer: support styling for app content

### ISSUE THREAD

**Issue by maicol07** [material-components/material-components-web-components#2168]
**Is your feature request related to a problem? Please describe.**
I would like to change background color of app content via CSS variables.

**Describe the solution you'd like**
Using global CSS variables to style the app content div inside the drawer.

**Describe alternatives you've considered**
Workaround: Javascript

**Comment by asyncLiz** [comment]
Thanks for the bug! We're aware of the issue and we're currently tracking support of this in https://github.com/material-components/material-components-web-components/issues/953.

At the moment we're focused on revamping our components' theming system which will support this feature.
