### ISSUE TITLE
v0.3.6 specifies `lit-element` in depedencies, imports from `@polymer/lit-element` in files

### ISSUE THREAD

**Issue by ZempTime** [material-components/material-components-web-components#217]
👋 Hey. We're using `@material/mwc-base` and running into an issue trying to update to `v0.3.6`. All in the title.
```
Module not found: Error: Can't resolve '@polymer/lit-element/lit-element.js' in '/Users/zempelc/code/x/singularity/node_modules/@material/mwc-base'
```
For example, right here: https://github.com/material-components/material-components-web-components/blob/master/packages/base/component-element.js#L17

**Comment by hyperpress** [comment]
The new lit releases are unscoped. So just reference 'lit-lement.js' in your path. Without @polymer.

**Comment by azakus** [comment]
Did you get a funky build somehow?
`base-element.ts` uses `lit-element` with the correct name: https://github.com/material-components/material-components-web-components/blob/master/packages/base/src/base-element.ts#L18

**Comment by hyperpress** [comment]
I think this was referencing base-element.js.

**Comment by azakus** [comment]
There is no `base-element.js`, is the issue with https://github.com/material-components/material-components-web-components/blob/master/packages/base/component-element.js ? That file isn't used by an released packages.

**Comment by ZempTime** [comment]
I've been digging more and this one's on me, I believe. We have a 
```
import {
  ComponentElement,
  html
} from "@material/mwc-base/component-element.js";
```
elsewhere I was unaware of as we were trying to use these mwc as much as we can.

https://github.com/material-components/material-components-web-components/blob/master/packages/textfield/mwc-textfield.js#L17 -> this is the corresponding import in an unreleased element, so I think you're correct.

This issue can be closed! I'll have to workaround `component-element.js` for the time being

**Comment by azakus** [comment]
@ZempTime Thanks for the update! I think the real bug here is that some cruft we've been keeping around to help port elements to typescript is being distributed via npm.

I'll go ahead and explicitly set which files should be exported by our packages to help avoid this in the future.

**Comment by azakus** [comment]
Moved the specifics to #219
