### ISSUE TITLE
mwc-drawer: demo doesn't work on Edge/IE

### ISSUE THREAD

**Issue by frankiefu** [material-components/material-components-web-components#218]
For example in `/demos/drawer/modal.html` nothing happens when I click on the menu button.

**Comment by straversi** [comment]
Initial investigation shows this is probably caused by https://github.com/webcomponents/shadydom/issues/252

**Comment by straversi** [comment]
I've confirmed locally that https://github.com/webcomponents/shadydom/pull/320 fixes this issue. Blocked by release of shadydom, followed by webcomponentsjs.

**Comment by frankiefu** [comment]
Fixed by https://github.com/material-components/material-components-web-components/pull/268
