### ISSUE TITLE
circular-progress: IE doesn't allow ariaLabel

### ISSUE THREAD

**Issue by 43081j** [material-components/material-components-web-components#2191]
**Describe the bug**

In IE, `setAttribute('ariaLabel', 'foo')` doesn't seem to be allowed, i.e. the attribute never appears on the element. The circular progress elements both depend on this for setting the aria label (as they have an `ariaLabel` property).

@e111077  recently worked around this in the unit tests by setting `.ariaLabel` instead of the attribute. an easy way to recreate it is by changing that back to use `ariaLabel` (attribute) in the circular progress tests and running them in IE.

**To Reproduce**

1. In IE render the circular progress element and `node.setAttribute('ariaLabel', 'foo')` in dev tools
2. observe that the attribute never got set

**Expected behavior**

`ariaLabel` is set (as `arialabel`) and propagates to the `ariaLabel` property.

**Browser Version (please complete the following information):**
 - OS: Windows
 - Browser: IE
 - Version: unknown

**Comment by e111077** [comment]
@dfreedm will this cause an issue with the new aria decorator?

**Comment by dfreedm** [comment]
Nope, but this should should be set with the `aria-label` attribute or `ariaLabel` property.
