### ISSUE TITLE
[TopAppBar] Implement Behaviours

### ISSUE THREAD

**Issue by aress31** [material-components/material-components-web-components#2205]
When will you start the implementation of the different behaviours when scrolling defined in the MDC spec (https://material.io/components/app-bars-top#behavior)?

**Comment by taylor-vann** [comment]
Hey @aress31

That feature (top app bar disappears on scroll down and reappears on scroll up) is already implemented! Here's a [demo](https://material-components.github.io/material-components-web-components/demos/top-app-bar/) showing the behavior you're describing.
