### ISSUE TITLE
select with fixedMenuPosition doesn't update the menu position

### ISSUE THREAD

**Issue by yinonov** [material-components/material-components-web-components#2206]
**Describe the bug**
Select dropdown menu is being cutoff inside dialog even with _fixedMenuPosition_ property set to true.

**To Reproduce**
```
<mwc-dialog open>
  <mwc-select label="filled" fixed-menu-position fixedMenuPosition>
    <mwc-list-item></mwc-list-item>
    <mwc-list-item value="0">Item 0</mwc-list-item>
    <mwc-list-item value="1">Item 1</mwc-list-item>
    <mwc-list-item value="2">Item 2</mwc-list-item>
    <mwc-list-item value="3">Item 3</mwc-list-item>
  </mwc-select>
</mwc-dialog>
```
or use the [sandbox](https://codesandbox.io/s/fixed-dropdown-menu-ndmw8)

**Expected behavior**
the dropdown menu should overlay the dialog in a fixed position

**Screenshots**
![image](https://user-images.githubusercontent.com/15140652/109506502-5f7b2d80-7aa6-11eb-83d2-b17fc758fc35.png)

**Comment by e111077** [comment]
Discussed in Slack. Hasn't been released to a beta version just yet. Works on Canary

https://codesandbox.io/s/fixed-dropdown-menu-forked-0es07

cc: @taylor-vann we should probably work on a release
