### ISSUE TITLE
[TopAppBarFixed] Outlined Version

### ISSUE THREAD

**Issue by aress31** [material-components/material-components-web-components#2211]
Is it possible to add a variant of the top app bar without the shadow at the bottom of the bar but rather with an outlined top app bar? 

For example:

![image](https://user-images.githubusercontent.com/11601622/109691541-75105600-7b7f-11eb-932f-909cee6475b9.png)

**Comment by taylor-vann** [comment]
Hey @aress31!

Unfortunately our theming API for the top app bar does not include the shadow at the bottom of the bar. You can see a full list of supported theming properties [here](https://github.com/material-components/material-components-web-components/tree/master/packages/top-app-bar#css-custom-properties).

**Comment by aress31** [comment]
Sorry I meant the fixed-top-app-bar

**Comment by taylor-vann** [comment]
No worries!

[Here](https://github.com/material-components/material-components-web-components/tree/master/packages/top-app-bar-fixed#css-custom-properties) there is a CSS Custom Property you can set to style the box-shadow in top-app-bar-fixed!

:)

Hope it helps!
I'll reopen if this doesn't cover your use case!

**Comment by aress31** [comment]
Thanks @taylor-vann

**Comment by aress31** [comment]
+1
