### ISSUE TITLE
Offer mwc components as complete import of file and named import

### ISSUE THREAD

**Issue by AndreasGalster** [material-components/material-components-web-components#222]
I honestly didn't know how to phrase this title better, sorry. When importing components such as the button, they are imported via their named import according to the docs. 

![image](https://user-images.githubusercontent.com/3836411/52533601-6fe0d400-2d36-11e9-8f3c-7d8af43db64b.png)

This is great if we want to extend the component, however, it is a problem because in many cases it may not be necessary and it'll throw an error with tools like ESLint and IntelliSense.

![image](https://user-images.githubusercontent.com/3836411/52533612-93a41a00-2d36-11e9-8bda-dca6dcc34765.png)

It seems it works to just import the entire file, although not sure what the drawbacks are of this per component. Any thoughts on this? Should this be mentioned in the docs?

**Comment by azakus** [comment]
You can just use `import "@material/mwc-button` in these cases. This will cause `Button` to be loaded and registered, and it is not an "unused import" because it has global side effects.

**Comment by kenchris** [comment]
Makes sense to update the README.md 's for each component because they suggest you import the other way
