### ISSUE TITLE
MWC TextField issue when overriding the shape

### ISSUE THREAD

**Issue by colscott** [material-components/material-components-web-components#2241]
When overriding the TextField border radius using the --mdc-shape-small custom property, the label.mdc-text-field has a border radius of 0 for the bottom borders. When the TextField background is different to the page the background colour results in the following.

![image](https://user-images.githubusercontent.com/1170584/110831538-56d5e480-8268-11eb-99c5-e9ba2702bb27.png)

**Comment by dfreedm** [comment]
Can you make a live demo of this setup in a JSBin or Glitch? Likely there could be an issue with how shape is handled, but it's hard to tell without more context.

Thanks!

**Comment by colscott** [comment]
Hi, this all stems from a product request to give the outlined text field a background colour which I'm not sure material supports.

We wrap the mwc elements so we changed the text field background colour by styling the label like this:
https://jsbin.com/copapatatu/edit?html,output

It would seem the mwc-text-field label element has 0 border radius for the bottom borders and --mdc-shape-small for the top borders. 

We could set the border radius on the host like the JSBin below, but setting the --mdc-shape-small and then the border radius as well doesn't feel as clean. But we do have it a work around so you can close this issue if you want.
https://jsbin.com/tatehidufe/edit?html,output

Thanks :-)
