### ISSUE TITLE
Can non-googlers contribute?

### ISSUE THREAD

**Issue by AndreasGalster** [material-components/material-components-web-components#226]
Hi everyone, I'm doing a course on webcomponents and don't want to wait for some essential components like navs/drawers or chips to arrive anymore to include it in my videos, so I figured I might as well submit PRs if there's a chance they can be approved from non-googlers. 

Is it possible to help out? If so, any suggestions what to start out with? 

I'm especially eyeing some simpler components like chips, navs, drawers and so on that are essential for basic app building.

**Comment by elf-pavlik** [comment]
I recommend asking this question on https://discord.gg/material-components

**Comment by AndreasGalster** [comment]
Didn't get any feedback on the discord, most people weren't even said I should go to the Polymer slack (which isn't the case according to the lit-element team)

@azakus any suggestions how to get started with a successful PR?

**Comment by elf-pavlik** [comment]
In July I found `@Lynnsanity#7412` (@lynnmercier) very helpful on discord, you could try mentioning her there.

**Comment by sarbull** [comment]
**License: Google Open-Source**

**Comment by aomarks** [comment]
In general, contributions are welcome! Unfortunately, in practice we don't review as many contributed PRs as we would like to, but we will try to improve.

- Please be sure to first search through open issues and open PRs before sending your own PR.
- For small bug fixes, sending a PR directly is fine.
- For new features, or any kind of large change, it's really helpful to first file an issue (or find an existing one) and discuss the proposal with one of the maintainers. This will make it much more likely that the PR will be accepted.
- For any PRs or issues you create, please include a detailed explanation of the change. Including screenshots (e.g. before/after), and links to repros for bugs (e.g. on glitch, stackblitz, etc.) is also very helpful.

Thanks for contributing! I'm going to close this issue. You may want to follow https://github.com/material-components/material-components-web-components/issues/246 which tracks adding better documentation about our contribution guidelines.
