### ISSUE TITLE
Any plans for a production release?

### ISSUE THREAD

**Issue by govis** [material-components/material-components-web-components#2287]
It has been a few years of development but still no production ready release. If you want this to be used in real projects you should get a release out as many can't wait years or start using something uncertain.

**Comment by 43081j** [comment]
I agree, it would be super nice to at least have milestones or a roadmap. We've been using it in production for years now, which arguably is a bad idea but they have been stable enough fwiw.

I think the original goal seemed to be to drop material-components and replace it with this, which is a pretty big job probably not completed yet (moving all the foundation classes into here for example).

**Comment by dfreedm** [comment]
Our goal with Material Web Components is to fully replace MDC-Web as the official open-source Material Design component set. Before this can happen, Material Web Components need to be robust and meet our requirements for themability, accessibility, and developer experience. As @43081j said, this is a big job, but we’re working hard to meet these goals.

We’ll have more information to share later this year, so stay tuned!

Thanks!
