### ISSUE TITLE
Textfield input type="date" no longer works on desktop

### ISSUE THREAD

**Issue by epgrove** [material-components/material-components-web-components#2297]
Textfields with input type of date used to work by leveraging the native date picker. This no longer works with Chrome on desktop.

**Comment by asyncLiz** [comment]
Thanks for the issue! I just checked, and it looks like `<mwc-textfield type="date">` still correctly displays an `<input type="date">`. Here's an example: https://jsbin.com/zavimuhafo/edit?html,output

However, text fields with `type="date"` are not officially supported. Some aspects may be different (such as Chrome's calendar icon, which is not display).

Many browsers offer a desktop modal calendar picker, which can be displayed by pressing the spacebar. Keep in mind that this is not part of the [HTML spec](https://html.spec.whatwg.org/multipage/input.html#date-state-(type%3Ddate)), so behavior may vary from browser to browser.

We're currently working on a datepicker element, which will be the recommended control to use for displaying and selecting dates for Material Web.

**Comment by epgrove** [comment]
Yes, it was the loss of the calendar icon that I noticed. I wasn't aware of
the spacebar functionality in some browsers, thanks. Looking forward to an
official datepicker!
