### ISSUE TITLE
Misformatted docs for dialog/icon-button-toggle

### ISSUE THREAD

**Issue by Biggisb** [material-components/material-components-web-components#2334]
Hi 👋,

While browsing some docs I saw that @material-web-copybara copy some wrong formatted docs, so I clicked all current published components and found that there are only 2 affected in master: 

https://github.com/material-components/material-components-web-components/tree/master/packages/icon-button-toggle
https://github.com/material-components/material-components-web-components/tree/master/packages/dialog

Question: Where does that Docs come from? I know that you don't use JSDocs, so I was somehow interested in how you generate that stuff. 

And if you maybe need someone that "doctor" existing Docs with JSDocs inside your current components I would gladly offer myself if you want to support that.
✌

---

> *off-topic
> We use JSDocs and WC-analyzer in combination with custom-elements.json inside storybook works nice for us.
> Using Material WC for some of our own components and "extend" special functions if needed. (💖 it) *

**Comment by e111077** [comment]
thanks for the update will investigate the CL that caused this issue. Copybara is a tool we use to sync our github repo with our internal repo. Sometimes the internal commits don't exactly line up with the external ones and this happens sometimes silently.

**Comment by e111077** [comment]
Oh sorry I didn't notice the second half of your comment. The issues we have with adding new automations with this repo is that our source of truth is technically inside google (hence the need for copybara). An external PR will get internalized and once it's merged into the google monorepo, then copybara will merge the external one.

The issues that causes means that external automations would have to be reimplemented internally at google and thus maintained in two locations e.g. our build systems are completely different.

I'm personally interested in the WC-analyzer auto-docs automation, but we'd have to. weigh the build stability and maintenance benefits of it
