### ISSUE TITLE
Exclude tsconfig.json from node modules

### ISSUE THREAD

**Issue by govis** [material-components/material-components-web-components#234]
It appears that <code>tsconfig.json</code> files are included and published with <code>@material</code> node modules. Once discovered <code>tsc</code> will try to compile the modules regardless of the <code>exclude</code> setting of the consuming project.

**Comment by govis** [comment]
<code>src</code> folder containing .ts files should probably also be left out of the published node module e.g. <code>@material/mwc-icon</code>

**Comment by dfreedm** [comment]
Looks removed with v0.13
