### ISSUE TITLE
Add config option for icon buttons to use outlined version of icon

### ISSUE THREAD

**Issue by dinakachintseva** [material-components/material-components-web-components#2362]
Right now you can only use the filled version.

**Comment by peschee** [comment]
Some icons seem to work when using the `_outline` suffix in the icon name, but it only applies for a few selected icons.

Is there a proper way to use the various styles from the documentation page referenced https://fonts.google.com/icons ?

**Comment by dinakachintseva** [comment]
Yes so I actually got this to work by doing:
mwc-icon-button {
  --mdc-icon-font: 'Material Icons Outlined';
}
