### ISSUE TITLE
type attr mwc-button

### ISSUE THREAD

**Issue by dsm23** [material-components/material-components-web-components#2379]
It looks to me that I'm unable to apply a type attribute to the mwc-button

**Comment by asyncLiz** [comment]
Components do not support form association, so a `type="submit"` or `type="reset"` attribute will not do anything. You can track support for the button type attribute in https://github.com/material-components/material-components-web-components/issues/205 and general form support in https://github.com/material-components/material-components-web-components/issues/289.
