### ISSUE TITLE
@material/mwc-button^0.3.6 doesn't work due to bad dependency

### ISSUE THREAD

**Issue by Yuen92** [material-components/material-components-web-components#245]
In order to use mwc-button we must install the module from the public npm registry (https://www.npmjs.com/package/@material/mwc-button) using : 
`npm i @material/mwc-button`
See reference : https://github.com/material-components/material-components-web-components/tree/master/packages/button

When we use the mwc-button component the properties doesn't work (like raised). It's due to the mdc-button version 0.40.0.

It's seems @frankiefu fix it in the last commit : https://github.com/material-components/material-components-web-components/commit/9d51cc2224a1d0820944114ed3c54350ceba05f0

@frankiefu or other people can publish a new version of the component in the public npm repo?

**Note :** 
Today the workaround we have is to : 
`npm i @material/mwc-button`
then update the dependency from "@material/button": "^0.40.0" to "@material/button": "^0.44.0".
Then `npm i` in the `@material/mwc-button` directory to install the good version.

Thanks

**Comment by frankiefu** [comment]
@azakus @sorvell  Let's try do a release this week.

**Comment by frankiefu** [comment]
@Yuen92 `@material/mwc-button` 0.4.0 is released.

**Comment by Yuen92** [comment]
@frankiefu : Thanks all work well :+1:
