### ISSUE TITLE
Question: Soy support

### ISSUE THREAD

**Issue by sgammon** [material-components/material-components-web-components#2453]
Hey MWC authors,

firstly, we are in love with MWC. it works phenomenally well! thank you for your hard work on this framework. while browsing the code, i caught these annotations:

```
  /**
   * @soyTemplate
   * @soyAttributes buttonAttributes: #button
   * @soyClasses buttonClasses: #button
   **/
```

what do these do? is there a way somewhere to use soy with lit or MWC?

**Comment by dfreedm** [comment]
Great question!

We're using MWC internally at Google inside of frameworks that use Soy templating, and the tooling to make that work requires some annotations to better generate template parameters.

The syntax, types, and usage of these annotations isn't finalized, and may be removed entirely if the associated tooling no longer needs it.

**Comment by sgammon** [comment]
@dfreedm thank you! we happen to be big adopters of Soy as well, and we were stunned to come across these. we are building from Bazel, using `rules_closure` but haven't been able to bridge that into Lit entirely smoothly.

do you know if there are plans to someday release some of that tooling? we would love to implement our Lit elements in Soy! we use it on the backend via [micronaut](https://micronaut-projects.github.io/micronaut-views/1.3.2/guide/index.html#soy) (which we wrote), and on the frontend via idom, but our use of that lib is [pretty outdated](https://github.com/sgammon/incremental-dom/tree/iteriani-patch-1), which is driving our search for more modern component frameworks (hence, MWC!).
