### ISSUE TITLE
updateComplete breaks with lit-element@2.5.1

### ISSUE THREAD

**Issue by djlauk** [material-components/material-components-web-components#2454]
**Describe the bug**

Trying to await `Textfield.updateComplete` fails in a project using lit-element@2.5.1. There is a recursion and the call stack size gets exceeded. This is an excerpt from the _bottom_ of the JS console log showing the call stack

```
mwc-textfield-base.js:438 Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at HTMLElement.getUpdateComplete (mwc-textfield-base.js:438)
    at HTMLElement._getUpdateComplete (updating-element.js:618)
    at HTMLElement._getUpdateComplete (mwc-textfield-base.js:428)
    at HTMLElement.getUpdateComplete (mwc-textfield-base.js:439)
    at HTMLElement._getUpdateComplete (updating-element.js:618)
    at HTMLElement._getUpdateComplete (mwc-textfield-base.js:428)
    at HTMLElement.getUpdateComplete (mwc-textfield-base.js:439)
    at HTMLElement._getUpdateComplete (updating-element.js:618)
    at HTMLElement._getUpdateComplete (mwc-textfield-base.js:428)
    at HTMLElement.getUpdateComplete (mwc-textfield-base.js:439)
```

**To Reproduce**
1. Create a blank npm project and `npm install @material/mwc-textfield@0.21.0 lit-element@2.5.1`
2. Create an element that uses `<mwc-textfield>` and its `updateComplete` promise, e.g.

```ts
import {
  LitElement,
  customElement,
  html,
  query,
} from 'lit-element'
import '@material/mwc-textfield'
import type { TextField } from '@material/mwc-textfield'

@customElement('example-element')
export class ExampleElement extends LitElement {
  @query('#query')
  private __query!: TextField;

  firstUpdated() {
    this.__query.updateComplete.then(() => this.__query.focus());
  }

  render() {
    return html`<mwc-textfield id="query" label="Search stuff" helper="This field should focus on page load"></mwc-textfield>`;
  }
}
```

**Expected behavior**

The `updateComplete` promise should resolve (as documented by Lit).

**Screenshots**

n/a

**Browser Version (please complete the following information):**

n/a

**Additional context**

I ran into this problem after boldly updating all the dependencies in my project with npm-check-updates (see also #2435).

If I `npm install lit-element@2.4.0` into my project, the error goes away.

**Comment by dfreedm** [comment]
Thanks for the report, I'll take a look

**Comment by djlauk** [comment]
Thanks for looking into it. I can confirm that the JSBin reproduction works for me, too.
It may really be related to deduplication in the build system of our product, i.e. our rollup config looks like this (reduced to crucial parts):

```js
// rollup.config.js
import resolve from '@rollup/plugin-node-resolve'
// ...
export default {
	// ...
	plugins: [
		// ...
		resolve({
			dedupe: ['lit-html', 'lit-html/directives/unsafe-html', 'lit-element'],
		}),
		// ...
	],
}
```

Running `npm ls lit-element` shows both 2.4.0 for the mwc packages, and 2.5.1 for others. How can I check, that the deduplication is really what is happening and causing this? (I am not too good at understanding JS build tools. Sorry.)

**Comment by dfreedm** [comment]
Thanks for the followup! I think we're pretty close to being compatible with Lit 1 and 2, so this should be fixed soon.

**Comment by e111077** [comment]
this is fixed in our library now without the need for a workaround
