### ISSUE TITLE
mwc-top-app-bar missing style/css

### ISSUE THREAD

**Issue by DominicWrege** [material-components/material-components-web-components#251]
1. clone the repo
2. cd packages/top-app-bar
2. run tsc

**error**: 

> $ tsc
> src/mwc-top-app-bar.ts:22:21 - error TS2307: Cannot find module './mwc-top-app-bar-css.js'.
>22 import {style} from './mwc-top-app-bar-css.js';
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~

Please provide the missing mwc-top-app-bar-css.js file.

**Comment by frankiefu** [comment]
@DominicWrege Please follow the [instructions for setting up project development](https://github.com/material-components/material-components-web-components#contributing-guide) in the README.
