### ISSUE TITLE
WHAT about the lifecycle and the future of Material MWC ??

### ISSUE THREAD

**Issue by CICCIOSGAMINO** [material-components/material-components-web-components#2515]
I don't get what is actually the roadmap about Material MWC ?? ... I'm not longer confident to use this design layout at thte base of my WebApp ! It's logn time we're waiting the 1.0.0 release or news about ....

**Comment by allan-chen** [comment]
Thanks for reaching out and for providing feedback - I will communicate this to the team. #2441 has more details about what's on the horizon for our roadmap, and while there isn't too much detail right now we hope that there will be updates to share soon (and they will likely be posted in that thread). Apologies and thanks in advance for your patience.
