### ISSUE TITLE
using/extending the components from polymer, using WCT

### ISSUE THREAD

**Issue by sebs** [material-components/material-components-web-components#26]
Hi 

There is a restriction in polymer, whereas all import paths are to be relative. Thing is: the @polymer folder does not exists and I am not sure, if there is any "standardized" mechanism to lookup modules
beyond specifying a correct location

**Comment by azakus** [comment]
Using the latest `wct` with the flags `--npm --module-resolution=node`, you should be able to load modules with 
```js
<script type="module">
  import "@material/mwc-icon"
</script>
```

**Comment by sebs** [comment]
Thank you ;)
