### ISSUE TITLE
Should publish package-lock.json

### ISSUE THREAD

**Issue by RyanAfrish7** [material-components/material-components-web-components#262]
Each npm package on build should generate its own package.lock.json before publishing. That will make sure on consumption of such a package, it picks up the right version of dependencies.

**Comment by web-padawan** [comment]
No, it shouldn't.

> One key detail about package-lock.json is that it cannot be published, and it will be ignored if found in any place other than the toplevel package.

See https://docs.npmjs.com/files/package-lock.json

**Comment by RyanAfrish7** [comment]
@web-padawan That's a surprise for me. Always assumed it makes sure the same version of the files will be installed. Now understood that's shrinkwrap. 😄
