### ISSUE TITLE
[mwc-radio] Radio buttons with the same name are not grouped with lit-html "Array.map"

### ISSUE THREAD

**Issue by Laincito** [material-components/material-components-web-components#273]
Example: 

    render() {
        return html`
            ${this.arrayRadioButtons.map(i=>html`
                <mwc-radio name="sameNameOfGroup" value="${i.value}"></mwc-radio>
            `)}
    `;

When the page is rendered if you click on more than one button, all are marked, when only the last one should be.

**Comment by eskan** [comment]
i confirm this issue

**Comment by eskan** [comment]
https://github.com/material-components/material-components-web-components/pull/279

**Comment by Laincito** [comment]
Thanks, your commit solves the issue.

**Comment by eskan** [comment]
Hi @Laincito , 
may be you should let this issue open until the PR is merged
