### ISSUE TITLE
Add Documentation how to style these new Components in Polymer

### ISSUE THREAD

**Issue by chwzr** [material-components/material-components-web-components#28]
I am currently very confused how to style these components, since there is no real documentation about styling.

Which css variables are provided? 
Also how to use and import the css mvc-color variables ?

**Comment by doplumi** [comment]
This is exacerbated by the fact that the `-css.js` files shipped with the components are minified.

**Comment by aomarks** [comment]
We're in the process of adding READMEs to all components, which will include a table of all relevant custom properties (see https://github.com/material-components/material-components-web-components/tree/master/packages/snackbar for example). We're tracking this at #348, so closing this one.
