### ISSUE TITLE
`mdcFoundation` should be initialised before `firstUpdated`

### ISSUE THREAD

**Issue by elyobo** [material-components/material-components-web-components#308]
Delaying `mdcFoundation` instantiation until `firstUpdated` (see [base-element](https://github.com/material-components/material-components-web-components/blob/master/packages/base/src/base-element.ts#L71)) means that any other methods which rely on the foundation (e.g. [opening a snackbar](https://github.com/material-components/material-components-web-components/blob/master/packages/snackbar/src/mwc-snackbar-base.ts#L100))  will fail.

Is there a reason it's deferred instead of simply running in the constructor?

**Comment by Westbrook** [comment]
Being `LitElement` renders async waiting for `firstUpdated` (which is triggered via code paths initiated in the `constructor`) is the way to ensure component DOM is available when `mdcFoundation` is run against the element. If the element didn't wait and then tried to open a snackbar before `firstUpdated` it wouldn't really be there to open. 

You can see the code path from `constructor` to `initialize` to `_requestUpdate` to `_requestUpdate` to `_enqueueUpdate` to `performUpdate` to `firstUpdated` in https://github.com/Polymer/lit-element/blob/master/src/lib/updating-element.ts to better understand the piping here.

**Comment by elyobo** [comment]
Thanks for the explanation and pointer to the relevant code; odd that the initialisation is async when DOM manipulation is sync.

Perhaps attempts to perform actions before a component is ready should queue actions and then handle them on `firstUpdate` when it's safe to do so instead?  I'm not familiar with the code at all yet, so not sure whether that makes practical sense or where it should go (e.g. instantiate mdc foundation in constructor instead and have it handle queueing, then flush the queue on `firstUpdate` maybe?)

**Comment by elyobo** [comment]
Thanks @azakus!
