### ISSUE TITLE
mwc-button: import of element fails with exception:

### ISSUE THREAD

**Issue by ergo** [material-components/material-components-web-components#31]
When I import the element into my webpack 4 bundled application like this:

    import '@material/mwc-button/mwc-button.js';

I end up with `ReferenceError: regeneratorRuntime is not defined` error, this happens in both Firefox and Chrome.

Version tested: 0.1.1

**Comment by kevinpschaaf** [comment]
The MWC element set uses `async` functions in source, and thus WebPack's babel transform of async functions will require the [regeneratorRuntime](https://www.npmjs.com/package/regenerator-runtime) polyfill to be loaded/provided by the application for that transform to work.  Here's some webpack-specific info on the topic: https://codingitwrong.com/2018/02/05/await-off-my-shoulders.html

Note that the polymer CLI will add this to build output automatically when needed; ymmv with other tools.
