### ISSUE TITLE
implement mwc-select

### ISSUE THREAD

**Issue by e111077** [material-components/material-components-web-components#315]

**Comment by shirleyhsliu81** [comment]
Hi There,

Do you have an ETA for mwc-select component? Our project is waiting for this critical component.

Many Thanks,
Shirley

**Comment by e111077** [comment]
Hello, we were out for holidays but are back today. No exact timeline. You can see progress on the mwc-select branch which has quite a lot of progress.

We have put mwc-select as P0 and the dependencies as P1. Here's a quick timeline with no dates on how we plan to attack this:

* Implement mwc-select with no custom element for dependencies which include:
  * mwc-menu
  * mwc-list
  * mwc-menu-surface
* Implement deps elements with mwc-select-specific APIs (enough to get select out the door)
* Release this version of elements
* Upgrade dependency elements to be used in more-general use cases

After select we put all effort into our theming refactor and that should push us much closer to our 1.0 release

**Comment by nicolejadeyee** [comment]
underlying elements are ready for release except for menu.
meeting with bonnie about select and MDC foundation details to work out the last kinks.
