### ISSUE TITLE
Docs: missing/incorrect docs make it difficult to use

### ISSUE THREAD

**Issue by samuelli** [material-components/material-components-web-components#325]
Examples of incorrectness:
 * `import {Switch} from "@material/mwc-tab-bar"`

Examples of not very useful:
 * `<mwc-tab-bar>sentiment_very_satisfied</mwc-tab-bar>` should show usage with tabs

Examples of undocumented quirks:
 * Use of `icon` property does not work without importing `mwc-icon` separately.

Examples of missing docs:
 * Events - digging through typings/code is not particularly feasible. For example, even after looking at the relevant code, it's difficult to find the event name. See https://github.com/material-components/material-components-web-components/blob/master/packages/tab-bar/src/mwc-tab-bar-base.ts#L148 which is defined as a string constant

**Comment by aomarks** [comment]
We'll track the effort to add detailed READMEs to all components at https://github.com/material-components/material-components-web-components/issues/348
