### ISSUE TITLE
<mwc-button outlined> doesn't match spec

### ISSUE THREAD

**Issue by samuelli** [material-components/material-components-web-components#332]
From the demo page: 

![image](https://user-images.githubusercontent.com/787668/62230122-fe452280-b375-11e9-9ff3-a36b812f2180.png)

From the spec page (https://material.io/design/components/buttons.html#usage):
![image](https://user-images.githubusercontent.com/787668/62230144-0ac97b00-b376-11e9-988e-65a378cdf683.png)

Note the border width

**Comment by azakus** [comment]
Seems fine now?
<img width="128" alt="Screen Shot 2019-08-28 at 4 03 46 PM" src="https://user-images.githubusercontent.com/46725/63898340-74f13200-c9ad-11e9-98d2-d9fe6f54e9ae.png">

**Comment by aomarks** [comment]
We're moving our demos to glitch, and it looks fine there: https://mwc-demos.glitch.me/demos/button.html, so pretty sure this was just our demo site being out of date (which we should take down).
