### ISSUE TITLE
There is no index.js

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [material-components/material-components-web-components#34]
From README.md:

> Import the element definition into your HTML page:
> 
> ```<script type="module" src="@material/mwc-icon/index.js"></script>```

But there is no `index.js` file. Looks like it should be `mwc-icon.js`.

This applies to all packages.

**Comment by hyperpress** [comment]
True. sorry about the confusion. The filename should be the actual .js filename for the component. The Readme and docs need to be updated. If someone wants to assign that to me. I'll take care of it. In the meantime, use:

`<script type="module" src="@material/mwc-icon/mwc-icon.js"></script>`
