### ISSUE TITLE
<mwc-icon-button> should support SVG and images

### ISSUE THREAD

**Issue by aomarks** [material-components/material-components-web-components#343]
The MDC icon button supports specifying your icon as a ligature, an `<svg>`, or an `<img>`: https://github.com/material-components/material-components-web/tree/master/packages/mdc-icon-button#icon-button-toggle-with-svg

`<mwc-icon-button>` currently only supports the Material Icons ligature style. I imagine SVGs would be the most common way users will want to provide custom icons.

Also, is it currently possible to set a font other than Material Icons, if users want to implement their own ligatures in a custom font?

**Comment by fernandopasik** [comment]
should this one be implemented with `<slot></slot>`?

**Comment by fernandopasik** [comment]
This one might be duplicate of #156

**Comment by azakus** [comment]
Duplicate of #156
