### ISSUE TITLE
Setting scrollTarget on <mwc-top-app-bar> inside <mwc-drawer> makes it collapse

### ISSUE THREAD

**Issue by CaptainCodeman** [material-components/material-components-web-components#346]
Trying to create a very basic app layout using <mwc-drawer> with the content containing <mwc-top-app-bar>. If the `scrollTarget` property of the TopAppBar element is set then a `position: absolute` style is applied to it which causes the bar to collapse (because it's no longer in the flex layout of the drawer?)

This is masked if the content contains enough lorum-ipsum text to fill the screen but that can't be relied on to be the case.

Example - uncomment the text OR comment out the scrollTarget assignment to show correct layout:
https://jsbin.com/woragirixo/edit?html,output

Expected output:
<img width="769" alt="Screen Shot 2019-08-05 at 5 30 10 PM" src="https://user-images.githubusercontent.com/304910/62501177-c8090800-b7a6-11e9-9143-00fa5c3269cb.png">

Actual results:
<img width="769" alt="Screen Shot 2019-08-05 at 5 30 00 PM" src="https://user-images.githubusercontent.com/304910/62501185-cd665280-b7a6-11e9-94cb-62ed9bd9faca.png">

**Comment by CaptainCodeman** [comment]
The base material web has the same issue so it's probably not a problem with the mwc components themselves directly.

**Comment by CaptainCodeman** [comment]
This might already be fixed by #285

**Comment by asyncLiz** [comment]
Closing since this was fixed in https://github.com/material-components/material-components-web-components/pull/588
