### ISSUE TITLE
mwc-icon fails on Firefox 60 with dom.webcomponents.shadowdom.enabled set.

### ISSUE THREAD

**Issue by coreyfarrell** [material-components/material-components-web-components#36]
When `dom.webcomponents.shadowdom.enabled` is enabled `mwc-icon` does not render any graphics, it simply displays the ID as text.  If the shadowdom option is disabled and the polyfill is .  I'm unsure if this is an issue with Firefox or with `mwc-icon`, since this seems to be the only element with issues I figure it's best to start by posting here.

**Comment by sbesh91** [comment]
The Firefox team is hard at work completing their implementation of shadow dom v1.  They had originally shipped a shadow dom v0 implementation behind that same flag, but it was never given a full release.  This link will take you to the bug that is tracking the implementation of shadow dom v1 in Firefox.  (https://bugzilla.mozilla.org/show_bug.cgi?id=1205323)  This is also another great resource to track the implementation of other features that the Firefox team is working on.  (https://platform-status.mozilla.org/)

**Comment by coreyfarrell** [comment]
Thanks for the information, closing this out since there is nothing to do here.
