### ISSUE TITLE
Use postinstall instead of custom script

### ISSUE THREAD

**Issue by TroyTae** [material-components/material-components-web-components#381]
If we declare postinstall, npm executes it after npm install automatically.
(https://docs.npmjs.com/misc/scripts)
So what about to using postinstall instead of custom script?
Thank you :)

**Comment by jsilvermist** [comment]
Does `postinstall` execute on internal `npm install` though? I see it does on package install of the app itself, but I only see local `npm install` mentioned for `prepublish` and `prepare`.

**Comment by TroyTae** [comment]
@jsilvermist 
`install, postinstall: Run AFTER the package is installed.`
In the document, install and postinstall are described like this!

**Comment by aomarks** [comment]
I tried out the PR, and it did indeed run the `postinstall` script from both `npm install` and `npm ci`.
