### ISSUE TITLE
mwc-textfield input chinese error on ios

### ISSUE THREAD

**Issue by yang-zzhong** [material-components/material-components-web-components#383]
I use mwc-textfield on my project recently. But it not work fine on IOS, include safari and chrome.
When inputing chinese use Pinyin Input Method, mwc-textfield will hold the pinyin.
input sequence is
```
 b -> u -> q -> u -> 不去
```
the value in textfield is
```
bbubuqbuqu不去
```

**Comment by e111077** [comment]
cannot reproduce with Simulator (iphone XR) on a mac. Can you please produce a repro case?

**Comment by yang-zzhong** [comment]
The device is iphone se with IOS 12.3.1
The Link is [We Boo Sign In](https://iiiboo.cn/signin)
Iphone Pinyin Input Method

**Comment by e111077** [comment]
I was able to reproduce your issue on that site, but unfortunately it is not one of our Textfields. The author of @authentic/mwc-textfield seems to have implemented their own version. We will soon release our @material/mwc-textfield in the next release. I was unable to reproduce the behavior on that version of mwc-textfield.

**Comment by yang-zzhong** [comment]
ok thx
