### ISSUE TITLE
Support both leading and trailing icon

### ISSUE THREAD

**Issue by TroyTae** [material-components/material-components-web-components#388]
**I'm submitting a:**

- [ ] bug report
- [x] feature request

Sometimes I need to use both leadingIcon and trailingIcon.
Now I cannot find the document, but I remember single icon is a "recommendation" not "specification".
How about making this possible?

**Comment by aomarks** [comment]
Thanks for the PR. It looks like the Material spec is pretty clear that two icons in the same button is against the spec. See https://material.io/design/components/buttons.html#contained-button, and scroll down to *Don’t use two icons in the same button.*

I think we're going to try and stick very closely to the Material spec, so I'm not sure we'll be able to accept this PR for now.

I am curious to understand your use case though, would you be able to share an example screenshot of where you think a button in your app works better with two icons?

**Comment by TroyTae** [comment]
@aomarks 
Oh thank you for finding doc!
Of course this isn't often used, sometimes designer use like this:
![image](https://user-images.githubusercontent.com/20078201/63312744-610a5800-c33d-11e9-8a9f-13281f4dd423.png)
I guess they want to emphasize the button 🤔

**Comment by TroyTae** [comment]
I rollback my code except defining constants :)
