### ISSUE TITLE
Basic Snackbar Example doesn't show on Material Design Components for Web

### ISSUE THREAD

**Issue by afunworm** [material-components/material-components-web-components#397]
The basic example of snackbar for Material Design Components for Web doesn't work. It produces the error:

    `TypeError: snackbar.show is not a function`

I have tried using jQuery to make sure the DOM loaded properly. I have tried changing back and forth the javascript initialisation methods, but none seems to work.

You can find the code here: https://jsbin.com/mejefeq/edit?html,console,output

I have read the docs over and overs again, but none of it mentioned anything about this.

**Comment by aomarks** [comment]
I think in your example you need to do this instead:

```js
snackbar.labelText = 'Test';
snackbar.open();
```

See https://github.com/material-components/material-components-web/tree/master/packages/mdc-snackbar which documents the `labelText` property and `open` method.

However, please also note that this repo is for the *Material Web Components*. These are Web Components (see https://developer.mozilla.org/en-US/docs/Web/Web_Components) that implement Material design. It looks like you're actually using the *Material Components Web* library (yes, the names are very similar and confusing, sorry about that). The Material Web Components *use* the Material Components Web library, but issues you encounter when using Material Components Web *directly* should be filed at https://github.com/material-components/material-components-web/issues.
