### ISSUE TITLE
Make tests green

### ISSUE THREAD

**Issue by azakus** [material-components/material-components-web-components#398]
Travis was disabled for a week because of a badly formated `.travis.yml` file, and we need to get tests back to green.

**Comment by e111077** [comment]
Multiple issue here:

* Tests failing
* Lint causing errors and warnings
* Some tests exist for packages that don't

**Comment by e111077** [comment]
can I steal this one. Working on infra I accidentally completed this

**Comment by azakus** [comment]
Oh please do!

**Comment by e111077** [comment]
Depends on #415 and #398
