### ISSUE TITLE
Select demo - Uncaught (in promise) TypeError: Cannot read property 'addEventListener' of null

### ISSUE THREAD

**Issue by amitmerin** [material-components/material-components-web-components#4]
After installing and running the project, all demos work properly except the select demo:
Chrome 65
Mac OS 10.11.4
http://127.0.0.1:8000/demos/select.html
![screen shot 2018-04-26 at 4 46 12 pm](https://user-images.githubusercontent.com/13625738/39331044-76174146-4971-11e8-8d55-6729cec61249.png)
![screen shot 2018-04-26 at 4 46 23 pm](https://user-images.githubusercontent.com/13625738/39331052-7c8fbc42-4971-11e8-8471-33fcfec57173.png)

**Comment by sorvell** [comment]
Yes, this MWC element is based on an older version of the MDC select that was removed in favor of using the native `<select>` element (which works better on mobile). We need to update the MWC version of the element to work with this new version.

**Comment by DominicWrege** [comment]
@sorvell could you please to that :)

**Comment by chalin** [comment]
Any update on this?

**Comment by YodaNinja** [comment]
Any update on when this will be fixed, and the availability of all mwc-xxxxx components in npm registry?

**Comment by andythsu** [comment]
I'm still getting the error.
any updates on how to fix the problem? or a workaround?

**Comment by azakus** [comment]
Closing because this component was removed, and will be reimplemented.
