### ISSUE TITLE
Remove need to manually edit karma config

### ISSUE THREAD

**Issue by azakus** [material-components/material-components-web-components#400]
Somehow, do not require a whitelist in the karma config for loading modules.

**Comment by abraham** [comment]
Are you talking about this?

    {pattern: 'test/unit/mwc-{button,checkbox,fab,formfield,icon,icon-button,linear-progress,radio,ripple,switch,tabs}.test.js', watched: false}

If so I would think that this approach would work:

    {pattern: 'test/unit/mwc-*.test.js', watched: false}

**Comment by azakus** [comment]
That's probably enough. Though I bet we need to clean out the test folder.

**Comment by azakus** [comment]
This is obsolete. Fixed with #414
