### ISSUE TITLE
Use constants for CSS classes where appropriate

### ISSUE THREAD

**Issue by dfreedm** [material-components/material-components-web-components#403]
We should try to use the css classes exposed from MDC as constants so that we can automatically keep up with changes on the MDC side.

This may not make sense in cases where classes are not dynamic, as the cost of making the binding is not free.

**Comment by TroyTae** [comment]
Let me know you this:
https://github.com/material-components/material-components-web/pull/4668#issuecomment-488670269

So I create constant file like this:
https://github.com/material-components/material-components-web-components/pull/385/files#diff-0a3281ad29c3d464ce0312155a945f15R18

And If there are some constants are existed, I used inheritance:
https://github.com/TroyTae/material-components-web-react/blob/release/packages/drawer/constants.ts

If you need this work, can I steal this?

**Comment by TroyTae** [comment]
@azakus 
Let me know you this:
material-components/material-components-web#4668 (comment)

So I create constant file like this:
https://github.com/material-components/material-components-web-components/pull/385/files#diff-0a3281ad29c3d464ce0312155a945f15R18

And If there are some constants, I used inheritance:
https://github.com/TroyTae/material-components-web-react/blob/release/packages/drawer/constants.ts

If you need this work, can I steal this?

**Comment by dfreedm** [comment]
This is incompatible with #892
