### ISSUE TITLE
Why each MWC component is bringing its own version of lit-html? 

### ISSUE THREAD

**Issue by phani1kumar** [material-components/material-components-web-components#41]
I've added mwc-button to my project. It bring along with it (mwc-base, mwc-icon, mwc-ripple, ripple, base). Each of these are bringing their own version of lit-html. 

This is kind of redundant and unnecessarily causing more round trips to the server!

Of course, when using HTTP2, we can push more resources, but even then we are sending same files from different URLs multiple times. 

How can I avoid this?

**Comment by phani1kumar** [comment]
Looks like polymer build is creating these duplicates! not sure how to avoid this

**Comment by phani1kumar** [comment]
@bicknellr `npm ls lit-html` gives me -- (empty) as the response. I tried from both node_modules directory and outside.

@mkay581 Yes, I am using Yarn

**Comment by azakus** [comment]
All the dependencies should be sharing a version of lit-html and LitElement.
We've refactored the components to depend on `mwc-base` to ensure this.

If you still have multiple versions of lit-html or LitElement, you should check your project's dependencies for an incompatible version.
