### ISSUE TITLE
Add back TopAppBar centerTitle

### ISSUE THREAD

**Issue by azakus** [material-components/material-components-web-components#413]
While not explicity in the spec, it _does_ seem useful, and there is _an_ example of it in the Material example apps: 

![](https://material.io/components/assets/1XduqwetWetIIabvb9dFFlbqCxEvkbyks/appbartop-rally-ahero.png)

**Comment by azakus** [comment]
Better example: https://material.io/design/platform-guidance/cross-platform-adaptation.html#cross-platform-guidelines

**Comment by jsilvermist** [comment]
I like the idea of a pop-up-like window with a center title and back button or an X, like in the first example image.
