### ISSUE TITLE
Replace demo site with glitch

### ISSUE THREAD

**Issue by aomarks** [material-components/material-components-web-components#433]
The demo site is out of date (https://material-components.github.io/material-components-web-components/demos/) and the deploy script is currently broken.

We decided to replace the demo site with a glitch. This means we don't need to run any site of our own, and means that users can easily fork the demo to play around with the elements.

- [x] Set up the glitch site
- [x] Update the repo banner URL
- [ ] Update the top-level README to link to the main glitch page
- [ ] Update the individual READMEs to link to the specific glitch page
- [ ] Take down the old demo site (edit GitHub settings, and delete the gh-pages branch)
- [ ] Delete the demo site deployment code (NPM scripts etc.)

**Comment by e111077** [comment]
glitch is up:
source:
https://glitch.com/~mwc-demos
demos:
https://mwc-demos.glitch.me

Just need a PR to update the README

**Comment by aomarks** [comment]
Note (via @CaptainCodeman, thanks) that Glitch only supports 4000 requests per hour per glitch: https://glitch.com/help/restrictions/ -- and it looks like we may have hit this when we sent around the demos link in the Polymer slack today. It's also extremely slow even when it's working, in my experience. I guess we should consider whether this is acceptable for our main demos site.

Perhaps we should keep the github.io site after all, but include "fork" buttons there that will create a new glitch for users to play around with?

**Comment by djlauk** [comment]
[open-wc's code examples](https://open-wc.org/developing/code-examples.html) are hosted on [StackBlitz](https://stackblitz.com/). Maybe that would be worth a look?

According to [StackBlitz's announcement post](https://medium.com/stackblitz-blog/stackblitz-online-vs-code-ide-for-angular-react-7d09348497f4) there are "no bandwidth limitations" and "your apps never go to sleep".

For easy tinkering it also features forking, and for versioned maintanence of the reference code it supports importing from / linking to GitHub (as far as I understand).

I am not versed in these online tools, but I think that might be a fit. (I may also be completely wrong.)

**Comment by e111077** [comment]
I want to follow up with Material team as they have quite a lot of effort already invested into glitch as well as signing up for a beta organization.

**Comment by dfreedm** [comment]
@e111077 Any updates on this?

**Comment by e111077** [comment]
I guess this can be closed, but we haven't merged with Material mostly because we're not 1.0 yet

**Comment by e111077** [comment]
merged with material org and getting special resources due to their partnership with Glitch
