### ISSUE TITLE
Problem rendering mwc-textarea

### ISSUE THREAD

**Issue by MarcusGV** [material-components/material-components-web-components#443]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

**I'm submitting a:**

- [x] bug report
- [ ] feature request

**What OS are you using?**

Windows 10 x64

**What browser(s) is this bug affecting:**

Chrome

**Current behavior:**

When I add this web component I got the error in the image.

**Expected behavior:**

**Steps to reproduce:**

I just install it and use it like in the code below in a litelement file, the problem is in the import line: 
import '@material/mwc-textarea/mwc-textarea'; 
![Sin título](https://user-images.githubusercontent.com/39317911/63953595-40ca4f80-ca47-11e9-81b6-ac9e0e303bcd.jpg)

**Related code:**

```js
// insert any relevant code here or add a include a codepen
render() {
    return html`
    <p>Form2</p>
        <mwc-textfield id="nombre" label="Nombre"></mwc-textfield>
        <mwc-textarea label="My Textarea" helper="Helper Text"></mwc-textarea>
        <mwc-button raised label="raised" icon="code" @click=${this.probando}></mwc-button>
    `;
  }

```

**Other information:**

**Comment by aomarks** [comment]
This error happens when the same custom element name (in this case `mwc-notched-outline`) is being registered more than once. This often happens when NPM has installed two different versions of the same custom element package, and both are being imported.

I tried a quick repro by freshly installing the latest version (0.7.1) of those 3 elements and importing them, and I did not see the same error.

Can you run `npm ls @material/mwc-notched-outline` and share the output? This should show how you came to get two different versions of `mwc-notched-outline`. Your `package.json` could also be useful to share. Also, how are you building or serving your project (e.g. Rollup)?

**Comment by MarcusGV** [comment]
Thanks a lot for answering, this is the output in the image:
![Output](https://user-images.githubusercontent.com/39317911/63965401-ad047d80-ca5e-11e9-9481-ac86e4dd9849.jpg)

Im using PWA Starter Kit : npm run start

This is my package.json:
{
  "name": "pwa-starter-kit",
  "version": "0.9.0",
  "contributors": [
    "The Polymer Authors"
  ],
  "license": "BSD-3-Clause",
  "repository": "Polymer/pwa-starter-kit",
  "scripts": {
    "start": "polymer serve",
    "build": "polymer build --auto-base-path && gulp prpl-server",
    "build:static": "polymer build",
    "serve": "prpl-server --root server/build",
    "serve:static": "polymer serve --port 5000 build/es5-bundled",
    "test": "npm run test:unit && npm run test:integration",
    "test:integration": "mocha test/integration --timeout=10000",
    "test:unit": "polymer test --module-resolution=node --npm",
    "test:sauce": "polymer test --module-resolution=node --npm -s 'windows 10/microsoftedge@17' -s 'macos 10.13/safari@11'",
    "test:regenerate_screenshots": "mocha test/integration/screenshots-baseline/regenerate.js --timeout=15000"
  },
  "dependencies": {
    "@material/mwc-button": "^0.6.0",
    "@material/mwc-icon": "^0.7.1",
    "@material/mwc-textarea": "^0.7.1",
    "@material/mwc-textfield": "^0.7.0",
    "@material/textfield": "^3.1.0",
    "@polymer/app-layout": "^3.0.0",
    "@polymer/polymer": "^3.1.0",
    "@webcomponents/webcomponentsjs": "^2.2.4",
    "axios": "^0.19.0",
    "dile-input": "^1.4.1",
    "dile-modal": "^1.4.0",
    "dile-pages": "^1.1.2",
    "dile-rounded-button": "^1.1.0",
    "dile-tabs": "^2.0.6",
    "firebase": "^6.3.5",
    "lit-element": "^2.0.1",
    "pwa-helpers": "^0.9.0",
    "redux": "^4.0.0",
    "redux-thunk": "^2.3.0",
    "reselect": "^4.0.0",
    "rxfire": "^3.6.10",
    "rxjs": "^6.5.2",
    "social-icon": "^1.2.0",
    "xmldom": "^0.1.27",
    "xmlhttprequest": "^1.8.0"
  },
  "devDependencies": {
    "@polymer/test-fixture": "^4.0.2",
    "axe-core": "^3.0.0",
    "chai": "^4.1.2",
    "del": "^3.0.0",
    "gulp": "^4.0.0",
    "gulp-rename": "^1.3.0",
    "gulp-replace": "^1.0.0",
    "mocha": "^5.2.0",
    "pixelmatch": "^4.0.2",
    "polymer-cli": "^1.9.3",
    "polyserve": "^0.27.0",
    "prpl-server": "^1.4.0",
    "puppeteer": "^1.5.0",
    "wct-mocha": "^1.0.0"
  }
}

**Comment by aomarks** [comment]
It looks like NPM gave you two versions of `@material/mwc-notched-outline` (`0.7.0` and `0.7.1`), even though `0.7.1` should be the only one you need. Sometimes NPM doesn't aggressively de-duplicate dependencies when a previous version already exists (e.g. maybe you installed `mwc-textfield`, and then a little later `mwc-textarea`, and in the meantime we published a new version).

If you re-install from scratch, I expect you will only get one version:
`rm -rf node_modules/ package-lock.json && npm install`

Alternatively, you can upgrade your version of `@material/mwc-textfield` like this:
`npm install --save @material/mwc-textfield@latest`

**Comment by MarcusGV** [comment]
Thanks a lot, I did: 

npm install --save @material/mwc-textfield@latest 
and 
npm install --save @material/mwc-textarea@latest

And It works, I cant wait for the production version of all of this components they are great!

**Comment by aomarks** [comment]
Great, glad it worked! Closing as resolved.
