### ISSUE TITLE
mwc-textfield label rendering incorrectly when value is preset.

### ISSUE THREAD

**Issue by aarondrabeck** [material-components/material-components-web-components#444]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

**I'm submitting a:**

- [ X] bug report
- [ ] feature request

**What OS are you using?**
Windows 10

**What browser(s) is this bug affecting:**
All (Chrome 76)

**Current behavior:**
Label doesn't render correctly when value is preset.

![image](https://user-images.githubusercontent.com/9825025/63954924-27bea000-ca41-11e9-8336-42b7fb5d82b2.png)

```
<mwc-textfield       
          label="Name"
          value="test"
          outlined
          required
          validationMessage="Name is required"
        >
```

Label also doesn't render correctly when present with binding.  

`value="${this.newSlideShowName || ''}"`

![image](https://user-images.githubusercontent.com/9825025/63955030-4cb31300-ca41-11e9-8f13-4fa916644cde.png)

**Comment by e111077** [comment]
Hello, I can't seem to reproduce the issue. Can you please make a live repro?

Here is what I've got so far:
https://glitch.com/~mwc-showcase
code: https://glitch.com/edit/#!/mwc-showcase
live app: https://mwc-showcase.glitch.me

**Comment by aarondrabeck** [comment]
Interesting!  Well this took me a minute to figure out.  

It turns out, I am hiding the container that the input is in until I get an API call back with some data I wish to edit.  I then bind that data to input's value and un-hide the container with the input in it.  This causes the drawing error.  I was able to reproduce with a setTimeout here https://glitch.com/~solar-booth.  

I imagine the input is doing some calculations when its hidden with 0 width.  

Although this is slightly an edge case, I would think others will run into the same issue if they are dealing with loading data from a remote source and do not wish to show empty inputs as the load occurs.

**Comment by e111077** [comment]
Hmm this looks like it might also be an issue in @material/textfield. Shooting from the hip: I might have to end up providing a forceLayout function or upstream the issue.

I'll have to take a closer look after the holiday

**Comment by e111077** [comment]
Missed it this week, but it's still on my radar
