### ISSUE TITLE
Document mwc-tab 

### ISSUE THREAD

**Issue by AndreasGalster** [material-components/material-components-web-components#447]
I've been trying to use mwc-tab, which seems to be published and the code looks functional but this sample here does nothing. Probably good to update the documentation.

```
import { LitElement, html, css } from 'lit-element';
import {TabBar} from "@material/mwc-tab-bar";
import {Tab} from "@material/mwc-tab";

class MyElement extends LitElement {

  static get properties() {
    return {
      'name': String,
    };
  }


  render() {
    return html`
        <mwc-tab-bar>
        <mwc-tab label='Introduction'>ONE</mwc-tab>
        <mwc-tab label='Responvie media queries'>Responsive Media Queries</mwc-tab>
        <mwc-tab label='Flex Grid'>Flex Grid</mwc-tab>
        </mwc-tab-bar>
    `;
  }

}
customElements.define('my-element', MyElement);
```

Am I doing something wrong with using mwc-tabs?

Here's a stackblitz. There's a lot more stuff in there but should be able to see it. Imports and usage of the tabs are on the top of index.js

https://stackblitz.com/edit/svelte-lqgzqu?file=index.js

**Comment by Westbrook** [comment]
@AndreasGalster when you `import {Element} from 'element';` you won't be importing the _side effect_ of registering the custom element. Check out this reproduction: https://stackblitz.com/edit/yvo7ph?file=my-element.js where the only difference is:

```
import { LitElement, html, css } from 'lit-element';
import "@material/mwc-tab-bar";
import "@material/mwc-tab";
```

**Comment by AndreasGalster** [comment]
Gotcha, thanks that solved it :)!

**Comment by aomarks** [comment]
See https://github.com/material-components/material-components-web-components/issues/348 to track adding documentation to all components (including mwc-tab).
