### ISSUE TITLE
utils.js is outdated

### ISSUE THREAD

**Issue by masaoliou** [material-components/material-components-web-components#451]
**I'm submitting a:**
[X ] bug report

After `npm install @authentic/mwc-dialog`, file` ~/node_modules/@authentic/mwc-ripple/node_modules/@material/ripple/utils.js` exists. It appears to be outdated and thus has the same issue as [#1121](https://github.com/material-components/material-components-web/issues/1121).

**Comment by aomarks** [comment]
@authentic/mwc-dialog is not published by the maintainers of this repo. It looks like a fork published by a contributor. See https://www.npmjs.com/package/@authentic/mwc-dialog for author information of that package, and https://github.com/material-components/material-components-web-components/issues/295 to track this project's implementation of the dialog component.
