### ISSUE TITLE
mwc-textfield/textarea: provide mechanism to style unfocused elements

### ISSUE THREAD

**Issue by qqiao** [material-components/material-components-web-components#452]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

**I'm submitting a:**

- [ ] bug report
- [x] feature request

**What OS are you using?**

Any

**Current behavior:**

There is currently limited ways to apply styling to the textfields. For example. --mdc-theme-primary is applied to the outline and the label but only if the element is in focus, there's no documented way to style the outline of the element when it's not in focus. There's even fewer ways to style a textfield that's not outlined

**Expected behavior:**

Mechanisms provided for textfields/textareas to be styled to match the overall page theme.

**Comment by e111077** [comment]
updated list with idle and hover, please comment for missing features for reopen
