### ISSUE TITLE
Add fullwidth to mwc-button

### ISSUE THREAD

**Issue by AndreasGalster** [material-components/material-components-web-components#457]
**I'm submitting a:**
- [ ] bug report
- [x] feature request

**Current behavior:**
mwc-button needs width set to width: 100% to occupy the entire space

**Expected behavior:**
mwc-textfield has a fullwidth property to handle this behavior, does it make sense to add something like this to mwc-button?

**Comparison mwc-button vs mwc-textfield:**

```
      <style>
        mwc-button {
          width: 100%;
        }
      </style>

      <mwc-textfield fullwidth label="Standard"></mwc-textfield>
      <mwc-button label="Sign up via Email"></mwc-button>
```

**Comment by azakus** [comment]
Is this `fullwidth` property something you'd need in a dialog or constrained form?

**Comment by AndreasGalster** [comment]
Certainly very common in dialogs/forms, yes. 

Another use case might be e. g. on a login form or any form that requires full-width expansion (basically any form on mobile).

So I guess the question is rather if it makes sense to do it via property or CSS. I think fullwidth property is the quick fix that works for most cases but sometimes a developer might want to do responsive custom CSS styles instead.
