### ISSUE TITLE
How to handle events for the textfield ...

### ISSUE THREAD

**Issue by pitus** [material-components/material-components-web-components#48]
I'm trying to get the mwc-textfield working based on git repository (as it's not yet available in npm)
I can't find any documentation about event handling anywhere.
The code uses foundation (is there any documentation as to how that works in case any of us would like to build our own similar components?)
I've added on-input="${_onInput}"  which fires the handler properly, supplying e as event, but ... the only way I found to access the actual updated value of the internal input is as e.target._component.value or e.target._input.value - either one uses protected property so I don't think this is the intended syntax.
How will it work, eventually (once it's finished & made available as npm) ?
I see, I can also use e.composedPath()[0].value - which is better as it doesn't access any protected properties - found it here: https://www.polymer-project.org/3.0/docs/devguide/events

**Comment by pitus** [comment]
What I would expect from textfield is that it processes its own events that update the value property based on the input.value and then fires its own events which then have access to that textfield.value property - currently, e.target.value has the old value when on-input fires so I can't just get it while processing event.

**Comment by eskan** [comment]
https://github.com/material-components/material-components-web-components/pull/46

**Comment by azakus** [comment]
We'll address this with #293
