### ISSUE TITLE
Sync with MDC breaking changes branch

### ISSUE THREAD

**Issue by azakus** [material-components/material-components-web-components#480]
MDC is actively making breaking changes in the `develop` branch.
We should sync to the `develop` branch to try and get into the same release cadence as MDC, so there are no surprises when MDC v4 launches.

**Comment by aomarks** [comment]
Changes at https://github.com/material-components/material-components-web/blob/v4.0.0-canary.e851d4f40.0/CHANGELOG.md#breaking-changes

**Comment by e111077** [comment]
We still need to investigate as to why the newest canary branch still fails to build
