### ISSUE TITLE
Update mwc-fab to MDC Web 4

### ISSUE THREAD

**Issue by aomarks** [material-components/material-components-web-components#484]
We need to get MWC depending on MDC Web 4.0.0 canary.

The breaking changes are listed here: https://github.com/material-components/material-components-web/blob/v4.0.0-canary.e851d4f40.0/CHANGELOG.md#breaking-changes. Ripples for button, radio and fab now require an additional node.

The `canary` branch already exists with these new deps, and mwc-button has already been updated there (https://github.com/material-components/material-components-web-components/pull/481).

However, adding the new ripple node to mwc-fab causes the ripple to be much too large. Some additional changes seem to be needed.

**Comment by azakus** [comment]
Related to #480
