### ISSUE TITLE
How to handle Property change notifications in general within LitElement...

### ISSUE THREAD

**Issue by pitus** [material-components/material-components-web-components#49]
This is more of a generic question regarding all/any Lit element / component ...
How would we handle **property-change notification** when using an mwc component, for example **mwc-checkbox** has an `indeterminate` property, which might get changed by some source/means, I'm using that control and would like to 'know' when that property value has changed so that I can react to it.

I don't see any `on-indeterminate-property-change` syntax being implemented anywhere, so how can I handle such a change in any property value of any component?

This would be even more important for other custom components with no two-way binding being available in Lit elements - so we have to handle all such change notifications ourselves, but how exactly? Can someone provide an example or point to documentation on this subject?

See also #46 where I've mentioned that `on-change` doesn't get fired on any **mwc-XXX** components such as **mwc-textfield** or **mwc-checkbox** while other events such as `on-click` or `on-input` do get fired.

**Comment by eskan** [comment]
@pitus you don't do anything wrong about on-input on-change, on-input is a composed event, so it can bubble throw shadow dom : 
https://developer.mozilla.org/en-US/docs/Web/API/Event/composed
on-change isn't composed.
These elements (mwc) are in a very early stage so i guess this kind of events should be fired "again" with a adapted composed value. Let see what maintainers say about that.

**Comment by pitus** [comment]
@eskan - I can't figure out how to do my own custom `this.dispatchEvent( new CustomEvent( 'selected', { bubbles: true, detail: { selected: this.selected } } ) );` so that it's `composed` ? I can't find any documentation or examples of that and I can't figure out how to fire an event from my Select component to its ancestor letting it know of a selection - the above doesn't fire, adding `notify` to the property doesn't fire `on-selected-changed` either as it would in Polymer. I'm completely confused by all the LitElement functionality, event handling and so frustrated, I'm about to give up on it altogether :(
Can you help a bit to get started?

**Comment by eskan** [comment]
don't give up !!! :D 
if you want a composed event you need to add composed :true
https://dom.spec.whatwg.org/#event
` new CustomEvent( 'selected', { bubbles: true, composed: true, detail: { selected: this.selected } } )`
if you want to listen to this event you should use "on-selected" instead of "on-selected-changed", on-[eventName]
In that case i'm not sure a composed event is necessary you should listen for event on you element,<my-checkbox on-selected="...">
i use composed event for more global event like user-logout

You should keep in mind that lit-element isn't "complicated" it's just web with less magic ;) so you need to find your way to build native application. To me a very a good start is Monica Talk @IO2018 and the PWA Starter Kit.
Cheers,

**Comment by merlinnot** [comment]
I’ve been debugging this component a few days ago and it does not dispatch any custom events, you basically get only mouse/keyboard events.

I can recommend using https://developers.google.com/web/tools/chrome-devtools/console/command-line-reference#monitoreventsobject_events to make it easier to look up all of the dispatched events. You might find something useful in your scenario.

**Comment by pitus** [comment]
@eskan - thanks for the composed hint, it finally works :) Too bad I couldn't find any specification / documentation of that anywhere (perhaps I'm just too tired and too frustrated trying to get something working - coming from a knockout.js and a bit of time spent with Polymer 2.x I just found this way too much 'going back to basics' where I have to do almost everything myself, manually ... yet, I thought that the whole purpose of LitElement and WebComponents was to simplify my work as a programmer by eliminating all redundancy,.. I'm yet to be convinced that this is the right way to go, but at least, thanks to your help, I got past this event issue. Still, can't see any events being fired by mwc components such as textfield or select...

**Comment by azakus** [comment]
It looks like this specific issue has been solved for a long time, so I'll close the issue.

However, I have opened #616 to document the "philosophy" of how we want events to work in MWC.
