### ISSUE TITLE
Font Customization via CSS Variable

### ISSUE THREAD

**Issue by mbleigh** [material-components/material-components-web-components#495]
**I'm submitting a:**

- [ ] bug report
- [x] feature request

It would be great to be able to customize things like font-family across all components via a CSS variable e.g. `--mdc-theme-font-family`. Right now I'm unsure how to customize fonts at all, which is leading me away from using MWC.

**Comment by contis2908** [comment]
Besides the font-family especially the font-size should be adjustable as well.

**Comment by asyncLiz** [comment]
Looks like we also have an upstream issue for this request (https://github.com/material-components/material-components-web/issues/5003)

**Comment by asyncLiz** [comment]
https://github.com/material-components/material-components-web-components/pull/866 will fix this!

**Comment by e111077** [comment]
^ along with material-components/material-components-web#5618

**Comment by asyncLiz** [comment]
Fixed in #866 and material-components/material-components-web#5618
