### ISSUE TITLE
tsc errors

### ISSUE THREAD

**Issue by masaoliou** [material-components/material-components-web-components#496]
**I'm submitting a:**
- [x] bug report

**What OS are you using?**
Debian buster

**Which sources are giving these bugs?**
`git clone https://github.com/material-components/material-components-web-components.git mwc-alpha`

**Current behavior:**
Command `cd mwc-alpha && npm run build`

yields several error messages as in the attachment.
Files producing errors are:

- packages/button/src/mwc-button-base.ts
- packages/dialog/src/mwc-dialog-base.ts
- packages/dialog/src/mwc-dialog-css.ts
- packages/dialog/src/mwc-dialog.ts
- packages/textfield/src/mwc-textfield-base.ts

**Expected behavior:**
Command `npm run build` does not show error.

**Steps to reproduce:**
 Error message coming from `button` can be manually reproduced with these commands:

```shell
cd mwc-alpha/packages/button
tsc 2>&1 >/tmp/log
```

messages in file `/tmp/log`:

    src/mwc-button-base.ts(50,16): error TS2339: Property 'handleFocus' does not exist on type 'RippleSurface'.
    src/mwc-button-base.ts(62,16): error TS2339: Property 'handleBlur' does not exist on type 'RippleSurface'.
[log.zip](https://github.com/material-components/material-components-web-components/files/3645760/log.zip)

**Comment by aomarks** [comment]
Did you run `npm install` first?

**Comment by aomarks** [comment]
Closing, I'm guessing that you forgot to run `npm install`. Please re-open if you still encounter a problem.
