### ISSUE TITLE
[Language feature] mwc-snackbar.open(labelText)

### ISSUE THREAD

**Issue by vdegenne** [material-components/material-components-web-components#519]
This is just a small request. Is it possible to pass the `labelText` inside the `open` method of the snackbar ?

```javascript
this.shadowRoot.querySelector('#snackbar').labelText = 'my message'
this.shadowRoot.querySelector('#snackbar').open()
```
to
```javascript
this.shadowRoot.querySelector('#snackbar').open('my message')
```

I know this is only one line spare but because it's 2 lines long it's usually wrapped inside a function which becomes at least 4 lines long and the need to write a function every new project.

**Comment by dfreedm** [comment]
I don't think we want to implement this. We prefer a declarative approach, and functions that are side effect free. Bindings to the `labelText` might interfere with `open(string)` usage, and not providing that parameter is more obvious.
