### ISSUE TITLE
Explore theming systems

### ISSUE THREAD

**Issue by dfreedm** [material-components/material-components-web-components#526]
Placeholder bug to explore more complicating theming scenarios than setting a few CSS Custom Properties.

Maybe something with `::part`, or a system to inject Constructed Stylesheets that only allow certain properties to be included per component?

**Comment by lkraav** [comment]
@web-padawan maybe you have thoughts here, wrt extensive https://github.com/vaadin/vaadin-themable-mixin experience?

**Comment by web-padawan** [comment]
I think it's already being discussed here https://github.com/Polymer/lit-element/issues/835
