### ISSUE TITLE
Switch has a slot, other inputs don't

### ISSUE THREAD

**Issue by bramkragten** [material-components/material-components-web-components#528]
`mwc-switch` has a slot, but other inputs like `mwc-radio` and `mwc-checkbox` do not and require the use of `mwc-formfield` to give it a label.

Further more, the slot of `mwc-switch` is not styled at all and not wrapped in a `<label>`, like it should according to `mdc-switch`:
```html
<div class="mdc-switch">
  <div class="mdc-switch__track"></div>
  <div class="mdc-switch__thumb-underlay">
    <div class="mdc-switch__thumb">
        <input type="checkbox" id="basic-switch" class="mdc-switch__native-control" role="switch">
    </div>
  </div>
</div>
<label for="basic-switch">off/on</label>
```

I think this should be aligned, either `mwc-radio` and `mwc-checkbox` should also get a slot, ideally using the styling of `mwc-formfield`, or the slot in `mwc-switch` should be removed.

Ideally I would like to see slots on all of them, as it makes using the elements a lot easier.

**Comment by azakus** [comment]
Oh, that does seem weird!

**Comment by asyncLiz** [comment]
Per #999 mwc-switch should not have a slot and we need to remove it.
