### ISSUE TITLE
[mwc-textfield] Custom Prefix or Suffix Elements (similar to Polymer's paper-input)

### ISSUE THREAD

**Issue by manustays** [material-components/material-components-web-components#541]
**Feature Request:**
Similar to Polymer's **paper-input**, there should be option to add any child element inside mwc-textfield as **prefix** or **suffix**.

_Can it be currently done?_ Are there _any plans to implement_ similar functionality in the future?

**Current behavior:**
* We can only add a prefix icon or a suffix icon in the mwc-textfield
* Event listener cannot be added to these icons
* These icons cannot be styled
* More than one icon (as either prefix or suffix) cannot be added
* Custom element or tag (say, a span with an icon and text) cannot be added

**Sample code:**
```html
<mwc-textfield label="OTP">
        <span suffix onclick="someaction"><mwc-icon>reload</mwc-icon> Resend OTP</span>
</mwc-textfield>
```

**Comment by ZufengW** [comment]
Something I want to do is make the prefix/suffix icon a clickable button. My current hacky workaround is to have an `mwc-textfield` and an `mwc-icon-button` and put the button on top of the textfield exactly where the textfield's icon is. It looks legit and has the right click and tab behaviour, but there are actually two icons.

![image](https://user-images.githubusercontent.com/15045948/66528409-7cc6f900-eb4b-11e9-9740-abaf7349d66f.png)

My other issues relate to more styling options for `mwc-textfield` but those seem to be covered by other issues. #544 #460

**Comment by asyncLiz** [comment]
Waiting on https://github.com/material-components/material-components-web/issues/1892 to be added upstream and then we'll add it to MWC.
