### ISSUE TITLE
mwc-button uses outdated CSS class for stroked/outlined versions

### ISSUE THREAD

**Issue by suburbanworrier** [material-components/material-components-web-components#55]
Underlying mdc-button has been updated with new CSS class and mwc-button needs to follow suit.

Very trivial fix required in packages/button/mwc-button.js

line 68:      ``` 'mdc-button--stroked': stroked,```
line 68:      ``` 'mdc-button--outlined': stroked,```

I've got a forked repo with the fix so PR would be simple from here.

**Comment by suburbanworrier** [comment]
Upstream change
https://github.com/material-components/material-components-web/pull/2632

**Comment by suburbanworrier** [comment]
PR submitted
https://github.com/material-components/material-components-web-components/pull/56

**Comment by frankiefu** [comment]
Fixed by https://github.com/material-components/material-components-web-components/commit/dda468342f29d431b6ea557ec9d2554cf276fdc5#diff-5a214fb1e9ee378db676acce7195368f
