### ISSUE TITLE
Additional CSS custom properties for tab and tab-bar

### ISSUE THREAD

**Issue by johnthad** [material-components/material-components-web-components#550]
**I'm submitting a:**
- [ ] bug report
- [X] feature request

**What OS are you using?**
macOS 10.14.x

**What browser(s) is this bug affecting:**
all

**Current behavior:**
From https://unpkg.com/@material/mwc-tab-bar@0.9.1/mwc-tab-bar-css.js it appears that the only custom properties for tabs are `—mdc-tab-height` and `--mdc-tab-stacked-height`

**Expected behavior:**
I would like to see more options for customizing tabs in my app. Granted, these ideas may not be comply with material design, but they are items that interest me or folks here:

`--mdc-tab-inactive-background-color` for tabs _not_ at `activeIndex` (Currently at each `click` I'm toggling a class that sets `background-color`)
`--mdc-tab-font-variant` and possibly other `font-*` ("Can't you make that `small-caps`?")
`--mdc-tab-button-radius` for the upper corners of the tab buttons
.etc.

**Comment by aomarks** [comment]
We also have a request for adding a horizontal padding CSS custom property.

**Comment by e111077** [comment]
also unselected text

**Comment by e111077** [comment]
For font customization we will have to defer that to Polymer/lit-element#835
