### ISSUE TITLE
Make named slot in <mwc-icon-button> the default

### ISSUE THREAD

**Issue by johnthad** [material-components/material-components-web-components#557]
**I'm submitting a:**

- [ ] bug report
- [x] feature request

**What OS are you using?**
macOS 10.14.6

**What browser(s) is this bug affecting:**
All

**Current behavior:**
Currently the slot for using an SVG image is a named slot (`slot="icon"`).

**Expected behavior:**
This is the only slot, so it could be the default.

**Other information:**
We have a library of SVGs that I add with `lit-html`, as in `${logoutIcon}`. Adding a slot attribute to each SVG is a bother, and might confuse their use in other situations where the slot might be a different name. Since the SVG is a named slot, I have wrap each in a span, like `<mwc-icon-button><span slot="icon">${logoutIcon}</span></mwc-icon-button>`

**Comment by azakus** [comment]
This will a breaking change, but it seems to make sense!
