### ISSUE TITLE
Publish Roadmap for Remaining Elements

### ISSUE THREAD

**Issue by mhamrah** [material-components/material-components-web-components#59]
Hey everyone, really looking forward to this project. I'm wondering if there's a roadmap for remaining elements, or some other tracking doc? Specifically curious about structural elements, like the [layout grid](https://github.com/material-components/material-components-web/tree/master/packages/mdc-layout-grid#html-structure).

Thanks,

Mike

**Comment by pe-wu** [comment]
Hi! I would like to express my appreciation for this whole port project and for the roadmap idea too!

My 0.02$: it would be great to see here toolbar and drawer components!

**Comment by phidias51** [comment]
Any news on when a bottom sheet component will be available? https://material.io/design/components/sheets-bottom.html

**Comment by hastebrot** [comment]
Great idea!

[material-components](https://github.com/material-components/material-components/blob/develop/ROADMAP.md) and [material-components-web](https://github.com/material-components/material-components-web/blob/master/ROADMAP.md) have a regularly updated roadmap.

With `lit-html` and `LitElement` getting more stable we really need a `ROADMAP.md` for this repository.
