### ISSUE TITLE
How to disable Ripple on various components.

### ISSUE THREAD

**Issue by tylercrocker** [material-components/material-components-web-components#60]
I'm super excited for the new Polymer 3 stuff, and just starting to work through the changes I'll need to make to my custom stuff to be able to use it all!

One thing I'm immediately confused with is disabling Ripple effects. Our designer hates them, and is constantly making me find ways to turn them off for any Material things we use, but with these components they seem completely baked in? Am I just not seeing something? I started trying to write a  wrapper around mwc-button to just override the method that binds it, but that didn't seem to work.

I have to take off right now, but I can add in more details later if anyone has any ideas?

Thanks!

P.S. I also was working with mwc-checkbox and just wanted to be able to define a clickable label. This doesn't appear to be immediately possible, and you can't set text anywhere... is there no way to do this without writing a wrapper around the element to handle creating js events?

I'm going to play with this a bit more, but so far what I feel like my solution has to be is writing my own components that are all wrappers around the MWC versions and adding any base functionality that I need. Is that the right approach to be taking?

**Comment by eskan** [comment]
hi,
for button you can override button class and its _ripple.
for checkbox label take a look to formfield : 
https://material-components.github.io/material-components-web-components/demos/formfield.html
regards,

**Comment by tylercrocker** [comment]
@eskan thanks for the quick response! Using the mwc-formfield definitely works, but I just realized that MOST of the mwc- components aren't actually available on NPM yet? (I tested by copying its code manually into its appropriate folder in my project).

I've tried overriding various things in Button by doing stuff like this:

```
import {html} from '@polymer/lit-element/lit-element.js';
import {Button} from '@material/mwc-button/mwc-button.js';
class SuccessButton extends Button {
  async ready() {
    super.ready();
    this._ripple = '';
  }

  _renderStyle(){
    this._ripple = '';
    return html`${super._renderStyle()}<style>.mdc-button{background-color: red;}</style>`;
  }
}
customElements.define('success-button', SuccessButton);
```

The "background-color: red;" but sticks (though it gets overridden, but it's at least hitting it), but nothing I do around the this._ripple property ever affects the button. It always ends up with the ripple effect regardless of where I try to override that. I've tried defining ready() without "async" before it as well as a bunch of other stuff. Any insight?

Honestly though, it's looking like I just can't use any of this yet until it's actually published to NPM though? Is there a timeline for when various components in this repo will be published to NPM?

**Comment by eskan** [comment]
@tylercrocker 
try with this._ripple.destroy();

**Comment by eskan** [comment]
And yes many works need to be done on those elements. Here you shouldn't need to override button to disable ripple, it will need a new attribute like "no-ripple" or other to disable it ... it needs to be discuss. Also i think these components will be used massively (as paper-elements replacement), so i guess maintainers works on how to build docs/website/contribution which is a big big task !!

**Comment by tylercrocker** [comment]
@eskan Yup, thanks! I guess after watching the Google IO video I was just thinking things were further along with these new components is all. I'll definitely be checking back to see how things progress! Thanks for the prompt feedback, it was very informative.
