### ISSUE TITLE
style not rendered in shadow-root for mwc-dialog

### ISSUE THREAD

**Issue by ranjeet-choudhary** [material-components/material-components-web-components#61]
![image](https://user-images.githubusercontent.com/13473684/41087474-6e224ed6-6a5a-11e8-8280-35829639dde4.png)
tried to use mwc-dialog by npm install from repo everything works except the css part. getting [object Object] at place of style. not sure if its lit-html issue

looks similar to this issue https://github.com/material-components/material-components-web-components/issues/33

**Comment by galanovnick** [comment]
It doesn't work in my project too, but it does work on the MWCW demo page (when running locally).

**Comment by suburbanworrier** [comment]
I think it would be useful to add a description of your project/environment over on Issue #33 which @azakus has already self-assigned.

It's noted there that the component works just fine in certain example use cases.

**Comment by ranjeet-choudhary** [comment]
Im trying to use this in https://github.com/Polymer/pwa-starter-kit

**Comment by galanovnick** [comment]
@ranjeet-choudhary, see my assumption here https://github.com/material-components/material-components-web-components/issues/33#issuecomment-395757559

**Comment by azakus** [comment]
we'll address this in #295
