### ISSUE TITLE
Ensure change events are forwarded out of mwc elements

### ISSUE THREAD

**Issue by sorvell** [material-components/material-components-web-components#63]
Currently mwc elements rely on native events bubbling out of the shadowRoot for some cases. However, the <input>'s `change` event is not `composed: true` and therefore cannot be seen outside the shadowRoot.

This applies to at least `mwc-textfield` and `mwc-switch` and likely a bunch of other elements.

**Comment by eskan** [comment]
i've started to update textfield : 
https://github.com/material-components/material-components-web-components/pull/46/files#diff-2124d0afbaf441f586c7cd05cebc31d6R134

**Comment by eskan** [comment]
@sorvell i saw that you had a Formable class, but no element is based on it. It should be a good place to add :
- value propety 
- value-changed event
- change event
also we'll need an iron-form (more light) substitute, it could be the base class to detect formable component.
If it's the plan let me know i will update some PRs
Regards,

**Comment by enrico-mezzato-qlik** [comment]
Hi @sorvell, do you have any estimate about when all material web components will have support for custom events (forwarded from the wrapped material component)?

In particular I am referring to the implementation of this good practice:
https://github.com/webcomponents/gold-standard/wiki/Property-Change-Events

This is useful, if not required, for using these components with Polymer 3 and Redux.

Cheers
