### ISSUE TITLE
mwc-textfield valid

### ISSUE THREAD

**Issue by odinr** [material-components/material-components-web-components#65]
```
// Master (and other branches)
get valid() {
    return this._component && this._component.isValid();
  }

  set valid(value) {
    this.componentReady().then((component) => {
      component.setValid(value);
    });
  }

// FIX
get valid() {
    return this._component && this._component.valid;
  }

  set valid(value) {
    this.componentReady().then((component) => {
      component.valid = value;
    });
  }

// since 
class MDCTextField extends MDCComponent {
...
/**
   * @return {boolean} valid True if the Text Field is valid.
   */
  get valid() {
    return this.foundation_.isValid();
  }

  /**
   * @param {boolean} valid Sets the Text Field valid or invalid.
   */
  set valid(valid) {
    this.foundation_.setValid(valid);
  }
...
}

**Comment by azakus** [comment]
Are you saying that there is a bug with the `valid()` function on some component?
More information would be helpful.

**Comment by RuarriS** [comment]
New to contributing, so pardon the formatting and missing info.

For mwc-textfield v0.1.2: 

`mwc-textfield.valid` results in: 
> Uncaught TypeError: this._component.isValid is not a function

`mwc-textfield.valid = true` results in:
> Uncaught (in promise) TypeError: component.setValid is not a function

@odinr 's proposed fix works.

**Comment by kfranqueiro** [comment]
It looks like the code in this repository is expecting the MDC Web Text Field component to have isValid and setValid methods, but the MDC Web component has a `valid` getter and setter.

The _foundation_ in MDC Web has `isValid` and `setValid` methods, but it looks like this wrapper isn't wrapping the foundation directly?

**Comment by azakus** [comment]
Closing for #293
