### ISSUE TITLE
[mwc-icon] request support icon fonts without ligatures

### ISSUE THREAD

**Issue by reno1979** [material-components/material-components-web-components#658]
**I'm submitting a:**
- [ ] bug report
- [*] feature request

**Current behavior:**
Using the default material icons font, the generated code is like this 
`<i class="material-icons">face</i>`

**Expected behavior:**
Some icon fonts do not have ligatures and thus do not render correctly. 
It would be nice if a boolean flag could be given to support a sort of fallback: 
`<i class="material-icons">&#xE87C;</i>`

**Comment by aomarks** [comment]
Can you clarify with an exact repro? If you slot in some text that is not a ligature for the configured font, then it will render as text, right?

**Comment by reno1979** [comment]
That is correct. 

I currently only have a value like &#xE87C;  (and stored these values inside CSS variables, like 

`:root{
--icon-face: &#xE87C;
}`

Our icon font does not have ligature support (made with fontforge) and the icons are used like this: 
(not actual used code)

`i::after{
    content: attr(data-icon); 
};`
`<i data-icon="&#xE87C;"></i>`

or 
`i.face::after{
    content: var(--icon-face);
}`

`<i class="face"></i>`

**Comment by reno1979** [comment]
I'm trying to wrap the mwc-button inside an other web component (gwc-button)

See: https://github.com/reno1979/gwc

**Comment by e111077** [comment]
Hello, the best answer here is to not use `mwc-icon` but rather update all of our elements that have icons to support slotted icons. We are in the process of currently doing this in `mwc-button`. Please file issues for any other elements where you run into this issue so that we can work to update them to support slotted icons.

See: #765
