### ISSUE TITLE
[mwc-textfield] outlined causes setCustomValidity test to fail

### ISSUE THREAD

**Issue by dgoogles** [material-components/material-components-web-components#660]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

**I'm submitting a:**

- [ x] bug report
- [ ] feature request

**What OS are you using?**
OSX 10.14.6

**What browser(s) is this bug affecting:**
Chrome/Firefox

**Current behavior:**
If you use an outlined textfield with an initial value the component will crash.

**Expected behavior:**
You should be able to use an outlined textfield with an initial value and not have it crash.

**Steps to reproduce:**
Update the test suite for mdc-textfield so the basic fragment appears like this:
```js
const basic = html`
  <mwc-textfield outlined .value="anything"></mwc-textfield>
`;
```

**Other information:**
You'll see this error:
this.mdcFoundation is undefined
      _checkValidity@http://localhost:9876node_modules/@material/mwc-textfield/mwc-textfield-base.js:301:7
      get validity@http://localhost:9876node_modules/@material/mwc-textfield/mwc-textfield-base.js:99:10
      @http://localhost:9876test/lib/packages/textfield/src/test/mwc-textfield.test.js:115:24

This is because firstUpdated awaits the child outlined component which causes a delay in mdcFoundation being created. So by the time updated is called, mdcFoundation is undefined, but the change in value calls this.mdcFoundation.setValue. You should at least check if mdcFoundation is defined in updated and better yet, if its not, delay setting the value until after updateComplete.

**Comment by dgoogles** [comment]
Actually upon further review, the error is with the checkValidity test and not related to setting value. I'm not sure this is an actionable bug anymore. Indeed, you can't call textfield.setCustomValidity before firstUpdated completes, but this could be addressed by the user awaiting updateComplete before calling it. Feel free to close this, I'll fix the title.

**Comment by e111077** [comment]
Thanks for the heads up! I think this is still actionable to add a test and docs.

**Comment by govis** [comment]
Also noticed that manually calling <code>setCustomValidity</code> with a non-empty message does not appear to put the component into an error state (red label, message, out/underline)

**Comment by e111077** [comment]
That is intentional as it is how the native `input` functions. On native input (and with `mwc-textfield`) you must call `reportValidity()` to activate the visual error state.
