### ISSUE TITLE
[mwc-button] Improvement suggestion

### ISSUE THREAD

**Issue by motss** [material-components/material-components-web-components#663]
## Issue
https://github.com/material-components/material-components-web-components/blob/395c02244bf15c2658cb110eb405ff2e4c0477fc/packages/button/src/mwc-button-base.ts#L76-L88

Since the element relies on the value of `this.icon` at L86 and L88, we can instead render `mdcButtonIcon` only when `this.icon` is defined. This seems minor but it's worth considering to improve when a large number of `mwc-button` elements are to render on the screen.

## Proposal

```ts
const mdcButtonIcon = this.icon ?
    html`<span class="material-icons mdc-button__icon">${this.icon}</span>` :
    ''; // Perhaps `nothing` here. 
...
return html`
    ...
    <div class="mdc-button__ripple"></div> 
    ${!this.trailingIcon ? mdcButtonIcon : ''} 
    <span class="mdc-button__label">${this.label}</span> 
    ${this.trailingIcon ? mdcButtonIcon : ''} 
`
```

**Comment by e111077** [comment]
Related #765
