### ISSUE TITLE
Version 1.0?

### ISSUE THREAD

**Issue by lucsoft** [material-components/material-components-web-components#666]
When do we have Version 1.0?

**I'm submitting a:**

- [ ] bug report
- [ ] feature request

**What OS are you using?**

**What browser(s) is this bug affecting:**

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```js
// insert any relevant code here or add a include a codepen
```

**Other information:**

**Comment by aomarks** [comment]
We don't have an ETA for a 1.0 label yet, sorry. You can expect various breaking changes, and probably a change to the component names (e.g. `mat-button` or `material-button`), before we decide to label 1.0.

**Comment by lucsoft** [comment]
some updates? @aomarks

**Comment by aomarks** [comment]
> some updates? @aomarks

Hi @lucsoft. I'm not working on this project at the moment, and I'm not up to date with the timeline for the prefix change and other major changes. Maybe @dfreedm , @e111077 , or @asyncLiz can comment?

**Comment by e111077** [comment]
Heya, we've yet to implement our design token standard which should be a large indication of nearing 1.0. We do expect to have some of our elements done by around Q4, but we don't have a set in stone timeline for the stamped 1.0 release.

Though rest assured that most of our components such as checkbox are being battle tested across google products that see millions of daily active users
