### ISSUE TITLE
Why the plain keyframe in the head tag?

### ISSUE THREAD

**Issue by abdonrd** [material-components/material-components-web-components#669]
I'm not sure if it is a bug; Why the plain keyframe in the head tag?

<img width="1238" alt="Screenshot 2019-11-30 at 23 25 17" src="https://user-images.githubusercontent.com/1007051/69906767-c522ca80-13c8-11ea-917d-9df797075d74.png">

**Comment by abdonrd** [comment]
It appears if you use [GoogleChrome/Rendertron](https://github.com/GoogleChrome/rendertron):

https://render-tron.appspot.com/render/https://mwc-demos.glitch.me/demos/button.html

<img width="673" alt="Screenshot 2019-12-01 at 11 17 38" src="https://user-images.githubusercontent.com/1007051/69912628-39428a00-142c-11ea-8b37-5c6905f013e3.png">

**Comment by e111077** [comment]
This is inserted by `mdc-ripple` as its default behavior is to style all light dom. Will have to address this after the merger:

Polymer/internal#390

**Comment by abdonrd** [comment]
@e111077 but why no inside a `<style>` tag?

**Comment by e111077** [comment]
Oh I misunderstood! Now that's funky!

**Comment by abdonrd** [comment]
Around this I think:

https://github.com/material-components/material-components-web-components/blob/ee1ee52569458c6117051187bdbd9abea20a5420/packages/ripple/src/ripple-directive.ts#L54-L61

**Comment by abdonrd** [comment]
@e111077 #681
