### ISSUE TITLE
[Feature Request] mwc-dialog prevent closing on scrim click

### ISSUE THREAD

**Issue by vdegenne** [material-components/material-components-web-components#689]
**I'm submitting a:**

- [ ] bug report
- [x] feature request

**Current behavior:**
Clicking the scrim (outside the dialog) will close the dialog.

**Expected behavior:**
A way to prevent this.

There are some situations in an app where you need the user to take a decisive action.
For instance let's say you need the user to accept some conditions, there are 2 choices "accept" or "dismiss".
In a normal context clicking out a dialog means "cancel", in a decisive action where you can't cancel the action the "cancel" action is interpreted as "dismiss". In this instance if the conditions are dismissed we want the user to be redirected to the referer. If the user unintentionally or not clicks outside the dialog (dismiss) he will get redirected, that's ambiguous and can confuse him. There are some cases where we want to make sure the user reads and interacts with the dialog and the buttons before proceeding further. I request a way to prevent the dialog to close on scrim click.

**Idea:**

```html
<mwc-dialog preventScrimAction>
  ...
</mwc-dialog>
```

**Current workaround:**

```typescript
dialog.addEventListener('closing', (e: CustomEvent) => {
  if (e.detail.action === 'close') {
    dialog.open = true
  }
})
```

**Comment by holgerengels** [comment]
I'd prefer veto callbacks for all dialog actions.

**Comment by vdegenne** [comment]
@holgerengels The problem with this workaround is it will reopen the dialog if the action was `close` and on some tested devices it creates an unwanted blinking effect.

**Comment by govis** [comment]
I just set <code>scrimClickAction=""</code> and it seems to work
