### ISSUE TITLE
mwc-button dense attribute not working

### ISSUE THREAD

**Issue by reno1979** [material-components/material-components-web-components#690]
- [X] bug report
- [ ] feature request

**What OS are you using?**
Windows 10 

**What browser(s) is this bug affecting:**
Chrome 78

**Current behavior:**
Buttons are the same:
```
<mwc-button unelevated="" label="dense original" dense=""></mwc-button>
<mwc-button unelevated="" label=" original"></mwc-button>
```

**Expected behavior:**
The dense button should become dense
(the class values changes but they have no effect)

**Other information:**
V 0.11.1

**Comment by allan-chen** [comment]
MDC removed the `mdc-button--dense` class in favor of `mdc-button-density` mixin. Sending out a PR applying that mixin soon.
