### ISSUE TITLE
<mwc-switch> does not update its `checked` property

### ISSUE THREAD

**Issue by rictic** [material-components/material-components-web-components#70]
As a user of `<mwc-switch>`, when I read `switchElem.checked` I'd expect it to mirror the state of its wrapped input, so that `switchElem.checked === switchElem.shadowRoot.querySelector('input').checked`.

Currently `checked` is set in the constructor but never updated.

**Comment by azakus** [comment]
I think this should work with the 0.3.x version, but I'll double check.

**Comment by azakus** [comment]
`checked` property updates with 0.3.1
