### ISSUE TITLE
MWC-tabs do not even show up in IE 11

### ISSUE THREAD

**Issue by isochronous** [material-components/material-components-web-components#700]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

**I'm submitting a:**

- [x] bug report
- [ ] feature request

**What OS are you using?**

Windows 10 Professional, build 18362

**What browser(s) is this bug affecting:**

Internet Explorer 11 

**Current behavior:**
When opening the tabs demo in IE11, the tabs do not even appear on the page

**Expected behavior:**
Tabs should show up, be clickable, have indicators, the whole nine yards

**Steps to reproduce:**

Open the MWC-tabs demo in IE11

**Other information:**
It's my understanding that the MWC components are supposed to at least be functional in IE11. The tabs are far from functional.  If you're not actually supporting IE11, then nevermind.

**Comment by e111077** [comment]
Hmm seems like the polyfills are not loading correctly

**Comment by e111077** [comment]
fixed on master, but unfortunately will not show up on the glitch demos until release. You can run them locally though.

Again, our elements are still in alpha so IE will not be 100% there until release
