### ISSUE TITLE
Remove -webkit-tap-highlight-color when custom highlight

### ISSUE THREAD

**Issue by abdonrd** [material-components/material-components-web-components#709]
**I'm submitting a:**

- [ ] bug report
- [x] feature request

**Current behavior:**

In components like `<mwc-tab>`, there is a blue highlight when tap:

<img width="661" alt="Screenshot 2019-12-18 at 11 39 00" src="https://user-images.githubusercontent.com/1007051/71079207-1da8e480-218b-11ea-86c4-681f79b9564f.png">

As this kind of component already have a custom highlight (the grey background), I think we should add the tipical:

```
-webkit-tap-highlight-color: transparent;
```

**Expected behavior:**

Don't see double tap highlight.

**Comment by dfreedm** [comment]
I want to look at the accessibility ramifications of this first, but if that seems fine I want to push this up in to MDC as well.
