### ISSUE TITLE
not all 0.1.2 release elements are available in npm

### ISSUE THREAD

**Issue by ranjeet-choudhary** [material-components/material-components-web-components#72]
Recent release 0.1.2 https://github.com/material-components/material-components-web-components/commit/8021304a412cb41bc874b04aee578aa907435b53
has many elements which are not available in npm. Are these not in sync?

**Comment by TimvdLippe** [comment]
Please see the disclaimer on the top of the README at https://github.com/material-components/material-components-web-components#material-web-components They will be published to NPM once we are satisfied with the working versions.
