### ISSUE TITLE
Glitch demo site error: "This project has received too many requests, please try again later."

### ISSUE THREAD

**Issue by stephantabor** [material-components/material-components-web-components#742]
** PLEASE READ THIS BEFORE COMMENTING ON THIS ISSUE **

**I'm submitting a:**

- [x] bug report
- [ ] feature request

**What OS are you using?**

Mac OS 10.14.5 

**What browser(s) is this bug affecting:**

Chrome 79

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36

**Current behavior:**

the demo site does not work

**Expected behavior:**

the demo site works

**Steps to reproduce:**

go to the glitch demo site linked at the top of this repo

**Comment by aomarks** [comment]
cc @e111077

**Comment by e111077** [comment]
we might have to consider bundling and serving with es dev server...

**Comment by guillermo** [comment]
Same here

**Comment by e111077** [comment]
Fixed on their side
