### ISSUE TITLE
top-app-bar broken in Firefox

### ISSUE THREAD

**Issue by sujato** [material-components/material-components-web-components#782]
**I'm submitting a:**

- [x] bug report
- [ ] feature request

**What OS are you using?**
Ubuntu 19.10

**What browser(s) is this bug affecting:**
Firefox 66

**Current behavior:**
Top-app-bar doesn't display properly. Firefox on the left, Chrome on the right.

![Screenshot from 2020-01-16 10-13-05](https://user-images.githubusercontent.com/6112010/72479601-0a03a300-3849-11ea-8060-c892dd3451f4.png)

https://mwc-demos.glitch.me/demos/top-app-bar.html

**Expected behavior:**
Works as per Chrome.

**Comment by Lodin** [comment]
The latest Firefox (72.0.1) does not seem to have this bug.

![image](https://user-images.githubusercontent.com/8037479/72628064-a370a900-395e-11ea-95ed-d2c6d40afa41.png)

**Comment by sujato** [comment]
Oh yes, me too. I've upgraded FF and it's fine. I guess we should close this.
