### ISSUE TITLE
TS code could not be runing on other HTTP server

### ISSUE THREAD

**Issue by hzmnet** [material-components/material-components-web-components#786]
** PLEASE READ THIS BEFORE FILING AN ISSUE **
I have an HTTP server using Polymer any MCW. but some of the codes are TS. our Http could not load it. is there any pure JS version?

**I'm submitting a:**

- [* ] bug report
- [* ] feature request

**Comment by aomarks** [comment]
If you install an MWC component from NPM as described in the READMEs, you will find .js files (see https://unpkg.com/browse/@material/mwc-button@0.13.0/).
