### ISSUE TITLE
[Feature Request] mwc-snackbar timeoutMs infinite.

### ISSUE THREAD

**Issue by vdegenne** [material-components/material-components-web-components#799]
**I'm submitting a:**

- [ ] bug report
- [x] feature request

Currently the snackbar only proposes an interval of time during which it will be displayed on the screen.  
I am sure it is something you took into consideration when you designed the component but as an end-user I don't understand the motivation behind not giving an easy customizable way to relax the duration or to make it infinite (for instance by setting the attribute `timeoutMs` to "0").  

To provide a simple use-case : The user adds an information in a list (e.g. a new word in an education application he added to his personal dictionary), the last word he added is something that you would want to stick on the screen. That's where the snackbar can come handy as it usually has a high precedence on the UI. Now the snackbar can have a closing button so when the user feels that information is no longer important he can manually close the snackbar himself.  
It's also a good thing to have the certainty that the user will see one particular information in your application and that the information will not be lost by his inattention.

So please if that's not a feature request could you please explain in few words the object for the time constraint here ?

I am posting this message because that is my second application where I need to make the snackbar to be sticky and as a showcase I had made this chrome extension that required the snackbar to wait for the user to close it by himself (https://github.com/vdegenne/baidu-hanyu-lookup-snackbar). At this time this was the pattern I was implementing :

```html
    <mwc-snackbar
        @MDCSnackbar:closing=${(e: CustomEvent) => {
          if (e.detail.reason === 'dismiss') {
            this.snackbar.open();
          }
        }}>

      <mwc-button slot="action">action 1</mwc-button>
      <mwc-icon-button slot="dismiss" icon="close"
          @click=${(e: MouseEvent) => {
            e.stopPropagation();
            this.snackbar.close('interacted');
          }}>
      </mwc-icon-button>

    </mwc-snackbar>
```

**Comment by govis** [comment]
+1 to have an option to keep the snackbar open until manually dismissed

**Comment by jsilvermist** [comment]
Also ran into this when trying to migrate from Polymer components which did have this option.

**Comment by asyncLiz** [comment]
Setting `timeoutMs` to -1 will allow for an infinite default. We need to update our documentation for snackbar.
