### ISSUE TITLE
Styling request: switch track styling

### ISSUE THREAD

**Issue by motiejunas** [material-components/material-components-web-components#800]
There is a need to override `mdc-switch__track` style for `mwc-switch` as track is not visible on dark backgrounds.

**Comment by isochronous** [comment]
+1. We're trying to get away from PolymerElements and move towards more modern solutions, but the switch just appears like a white circle against a black background, totally losing its "this is a movable object" look due to the invisibility of the track.

**Comment by e111077** [comment]
Thanks for the input on how this affects you. Unfortunately, this issue is still prioritized below other issues that we have deemed more pressing. Though feedback like this is appreciated and helps us more-accurately assign priority

**Comment by asyncLiz** [comment]
Leaving re-opened until we merge in the upstream changes that are necessary for this.

**Comment by asyncLiz** [comment]
Fixed now that #1046 is merged
