### ISSUE TITLE
mwc-ripple: Changing the value of active to false doesn't remove the ripple

### ISSUE THREAD

**Issue by beauwest** [material-components/material-components-web-components#805]
**I'm submitting a:**

- [x] bug report
- [ ] feature request

**What OS are you using?**
Mac OSX

**What browser(s) is this bug affecting:**
Google Chrome: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36

**Current behavior:**
If you set `.active` to true, the ripple is activated and rendered. Setting it back to false results in nothing happening. The ripple remains.

**Expected behavior:**
If I set `.active` to false, I would expect the ripple to be removed.

**Steps to reproduce:**
In the Chrome console
```
$0.active = true; // Results in the ripple being activated and rendered
$0.active = false; // Nothing happens
```

**Related code:**
None

**Other information:**
None

**Comment by dfreedm** [comment]
`active` property was removed with #936
