### ISSUE TITLE
mwc-icon - some icons cause strange spacing

### ISSUE THREAD

**Issue by 43081j** [material-components/material-components-web-components#826]
👋  as mentioned to @e111077 recently, mwc-icon looks to have an odd spacing thing going on in at least Chrome 80 onwards.

Go here:
https://mwc-demos.glitch.me/demos/icon.html

Open dev tools, change one of the icons to `settings_application`.

This is what i see:
![image](https://user-images.githubusercontent.com/5677153/73607741-f4fd7280-45b1-11ea-8f4a-5c427bcf7298.png)

To sort this on our end recently, i've added a width/overflow for now.

FYI it looks like its related to icon name's length somehow.

**Comment by e111077** [comment]
hmm this also seems to be an issue on Safari and FF

**Comment by e111077** [comment]
Oh It seems as if you're looking for `settings` not `settings_application`

**Comment by e111077** [comment]
Err you may actually looking for `settings_applications` not `settings_application`

**Comment by 43081j** [comment]
`settings_application` seems to be its own icon though? its different to `settings_applications` and hasthe funky spacing. how else do you get that icon?

**Comment by e111077** [comment]
Heya, sorry but it doesn't appear without the s in the catalog:

https://material.io/resources/icons/?search=Settings_application&style=baseline

The whitespace is the un-transformed text

**Comment by e111077** [comment]
(note you can only filter in desktop mode in the sidebar)

**Comment by 43081j** [comment]
aha i get it now!

it renders `settings` (which is a thing), and `_applications` then causes the space 🤦‍♂ 

good to know for when getting an icon wrong though. crazy spacing = you probably typo'd it.
