### ISSUE TITLE
mwc-textfield: cannot set background colour for outlined textfield

### ISSUE THREAD

**Issue by dejan9393** [material-components/material-components-web-components#827]
As the title states, we cannot override the default `transparent` background for an `outlined` `mwc-textfield`.

The `--mdc-text-field-fill-color` (see #544) only works for non outlined textfields

**Comment by asyncLiz** [comment]
Can you give an example use case of when you'd want to use a colored background? Outlined textfields are supposed to show the background behind them according to spec.

**Comment by asyncLiz** [comment]
Closing this for now due to inactivity. Outlined textfields should always be transparent per design spec.

Feel free to comment with your use case and we'll bring it up with our design team!
