### ISSUE TITLE
mwc-menu quick mode closed event called indefinitely

### ISSUE THREAD

**Issue by 200Puls** [material-components/material-components-web-components#839]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

**I'm submitting a:**

- [x] bug report
- [ ] feature request

**What OS are you using?**
Ubuntu Linux 64 

**What browser(s) is this bug affecting:**
Chrome / Chrome Headless

**Current behavior:**
I am trying to create a unit test with the menu. As soon as I enable the quick mode the element does not stop producing 'closed' events.

I'm using the open-wc setup with karma and mocha. This happens in regular chrome in debug mode and in chrome headless.

**Expected behavior:**
A close event should only be fired once when the menu is closed.

**Steps to reproduce:**

**Related code:**
My elements template is defined as follows:
```js
return html`
    <mwc-menu ?open="${this._menuOpen}" id="menu" @closed="${this._menuClosed}" ?quick="${this._quickAnimation}" @selected="${this._onLanguageChanged}" corner="BOTTOM_END" >
        ${this.items.map(
		item => html`
			<mwc-list-item>item</mwc-list-item>
			`
			)}
  		</mwc-menu>
	<mwc-icon-button icon="language" @click="${this._toggleMenu}"></mwc-icon-button>
`;
```

An the test:
```js
import { html, fixture, expect, assert, aTimeout } from '@open-wc/testing';
import '../element-selection.js';

describe('menu test', function() {
	it('opens a menu', async function() {
		const element = await fixture(html`
			<element-selection></element-selection>
		`);
                // switch to false to fix race condition
		element._quickAnimation = true;
		element._menuOpen = true;

		await aTimeout(3000);
	});
});
		`;
```
**Other information:**
I havent been able to reprosuce the issue in normal production when the element is integrated in the application.

**Comment by e111077** [comment]
I am unable to reproduce the issue:

https://stackblitz.com/edit/mwc-example-839?file=index.ts

My guess is that you have a change loop happening somewhere?

Can you provide a repro?

**Comment by 200Puls** [comment]
Hi, it seems to be related to timing somehow.

This shows the problem when opening and closing the menu: 
https://stackblitz.com/edit/mwc-example-839-bq8p5m?file=index.html

**Comment by e111077** [comment]
this seems like an issue that is better filed in

https://github.com/material-components/material-components-web

It seems as if the `open` and `close` function runs in an animation frame regardless of quick open or not:

https://github.com/material-components/material-components-web/blob/master/packages/mdc-menu-surface/foundation.ts#L171

For a workaround for mwc, I suggest awaiting `@open` or waiting for a RAF.
