### ISSUE TITLE
Fix sass dependency build

### ISSUE THREAD

**Issue by asyncLiz** [material-components/material-components-web-components#850]
See https://github.com/material-components/material-components-web-components/pull/849

**Comment by dfreedm** [comment]
Looks like the sass importer we are using isn't liking the `_index.scss` files added in https://github.com/material-components/material-components-web/pull/5539

**Comment by dfreedm** [comment]
Confirmed, inserting a fallback for `_index.scss` in `node-sass-import` works as expected. I'll fork the package and see if there's a good way to upstream my hack.
