### ISSUE TITLE
mwc-textfield: I cannot input Japanese properly on mobile

### ISSUE THREAD

**Issue by bboyrabi** [material-components/material-components-web-components#853]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

**I'm submitting a:**

- [ x ] bug report
- [ ] feature request

**What OS are you using?**
iOS 13.3 / iPhone 8

**What browser(s) is this bug affecting:**
Mozilla/5.0 (iPhone; CPU iPhone OS 13_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.4 Mobile/15E148 Safari/604.1

**Current behavior:**
I cannot input Japanese properly on mobile

**Expected behavior:**
Input and convert characters correctly by flick input

**Steps to reproduce:**
![ダウンロード](https://user-images.githubusercontent.com/9665307/74090255-873ed280-4aec-11ea-93b8-883a45d64677.gif)

**Comment by asyncLiz** [comment]
Thanks for the issue! Does the problem present itself when you try to input Japanese in the text field at https://material-components.github.io/material-components-web-catalog/#/component/text-field?

**Comment by bboyrabi** [comment]
There is no problem on that page.

Also, similar problem occurs on Safari on macOS.
version: macOS Cataline version 10.15.3

And, [mwc-textarea](https://github.com/material-components/material-components-web-components/tree/master/packages/textarea) does not have this problem.

**Comment by bboyrabi** [comment]
This problem has been fixed in v0.1.14.
