### ISSUE TITLE
mwc-textfield caret position bug in safari

### ISSUE THREAD

**Issue by mindon** [material-components/material-components-web-components#854]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

**I'm submitting a:**

- [x] bug report
- [ ] feature request

**What OS are you using?**

macOS 10.15.3 (19D76)

**What browser(s) is this bug affecting:**

Safari 13.0.5 (15608.5.11)
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Safari/605.1.15

**Current behavior:**

in a rendered <mwc-textfield>, input something, and focus cursor inside and input another character, the caret position goes to the end

**Expected behavior:**

caret position should be after the input character, not the end

**Steps to reproduce:**

STEP 1: visit https://mwc-demos.glitch.me/demos/textfield.html in Safari browser
STEP 2: input anything in first textfield, focus in before last character, input a new letter

**Related code:**

```js
// insert any relevant code here or add a include a codepen
```

**Other information:**

**Comment by e111077** [comment]
oof this is a gross one. Sorry this exists

**Comment by e111077** [comment]
It seems to be caused by setting

`<input .value=${this.value}>`

which is updated on `@input`
