### ISSUE TITLE
mwc-snackbar events prefixed with 'MDCSnackbar'

### ISSUE THREAD

**Issue by 200Puls** [material-components/material-components-web-components#860]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

**I'm submitting a:**

- [x] bug report
- [ ] feature request

**What OS are you using?**
Ubuntu 64

**What browser(s) is this bug affecting:**

Chrome

**Current behavior:**

The events fired by mwc-scnackbar are prefixed with 'MDCSnackbar':
MDCSnackbar:closed instead of closed

**Expected behavior:**

As the documentation states it should be possible to listen to close events on the snackbar.

**Steps to reproduce:**

**Related code:**

```js
<mwc-snackbar
   id="snackbar"
   labelText="Test"
   timeoutMs="${this.duration}"
  @MDCSnackbar:closed="${this._closed}">
</mwc-snackbar>
```

**Other information:**

**Comment by asyncLiz** [comment]
Thanks for the issue! This is working as intended, the correct event is `MDCSnackbar:closed` [according to the documentation](https://github.com/material-components/material-components-web-components/tree/master/packages/snackbar#events).

**Comment by 200Puls** [comment]
Hi @asyncLiz,

thanks for you answer. I see that the documentation is indeed correct. I think what confused me is that every componente is a bit different in that regard. 

Menu and dialog do not have the mdc prefix while snackbar and drawer do. I think it would definitely help to have a standard naming here.
