### ISSUE TITLE
mwc-ripple not able to style border-radius of .mdc-ripple-surface

### ISSUE THREAD

**Issue by BrunnerLivio** [material-components/material-components-web-components#863]
**I'm submitting a:**

- [ ] bug report
- [x] feature request

**Current behavior:**

Currently, there is no way, without JavaScript `element.shadowRoot`, to modify the border radius of `mwc-ripple > .mdc-ripple-surface`.

**Expected behavior:**

Considerable options:

1. Expose `.mdc-ripple-sufrace` with the [parts API](https://github.com/fergald/docs/blob/master/explainers/css-shadow-parts-1.md)
2. Add a CSS variable which modifies the `border-radius`.

**Other:**
This is a mandate when using rounded elements, which use `mwc-ripple` as child element.
The ripple effect does ignore the `border-radius` of its parent.

**Comment by dfreedm** [comment]
Can you provide a scenario where you need to set the border-radius on the ripple?
Unbounded ripples are already circular, and the ripple should be bounded by the containing element by default.

**Comment by BrunnerLivio** [comment]
> and the ripple should be bounded by the containing element by default.

Are you sure? In the following Codepen you can see that the Ripple is not bounded by the border radius of the containing element:

https://codepen.io/BrunnerLivio/full/NWqNjbw 

Uses mwc-ripple@0.13.0

**Comment by e111077** [comment]
Since the actual rippling is happening on the element's `::before` and `::after` I've always worked around this via `overflow: hidden`

**Comment by BrunnerLivio** [comment]
@e111077 I do not want to use `overflow: hidden` since the element which uses the `mwc-ripple` can have a dynamic width/height, depending on the content.

**Comment by e111077** [comment]
As long as the display of the parent is of some type of `block`, it should still automatically resize in most cases as long as height or width is not explicitly defined.

Does this still not fit your use case?

**Comment by BrunnerLivio** [comment]
@e111077 7 years of experience CSS and I still don't know about this these fundamentals :P

Thank you, this works for me!

**Comment by e111077** [comment]
No worries we're all learners every day. Regardless, we eventually hope to get a better ripple api your direction
