### ISSUE TITLE
we need a dropdown interface to extend some element!

### ISSUE THREAD

**Issue by hzmnet** [material-components/material-components-web-components#868]
we need a dropdown interface to extend some element!

such like components of combobox,picker,menu,select

**Comment by hzmnet** [comment]
i found a <mwc-menu-surface> could instead of iron-dropdown. but it seems not professor design for the dropdown

**Comment by e111077** [comment]
Hello, the element that you are looking for is indeed `mwc-menu-surface`, but it is not a component that we want to support for external usage (hence why it is not documented). Feel free to use it, but beware that it might break.

Also, we do not want to support it as it is not a component that is explicitly defined by the material spec.
