### ISSUE TITLE
css variable --mdc-select-ink-color not affecting mwc-select 

### ISSUE THREAD

**Issue by WeftDigital** [material-components/material-components-web-components#869]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

**I'm submitting a:**

- [ x] bug report
- [ ] feature request

**What OS are you using?**
Chrome on OSX

**Current behavior:**

The CSS variable `--mdc-select-ink-color` is supposed to control the text color of the selected value in mwc-select, but it doesn't.

**Steps to reproduce:**
https://jsbin.com/jifipinini/edit?html,console,output

**Comment by e111077** [comment]
nice catch
