### ISSUE TITLE
Self-host support for mwc-icon

### ISSUE THREAD

**Issue by kkimdev** [material-components/material-components-web-components#90]
mwc-icon's source is hard coded to `https://fonts.googleapis.com/icon?family=Material+Icons`

https://github.com/material-components/material-components-web-components/blob/286d4733ce1e3b450f5e4fa94b547eb442a1a054/packages/icon/mwc-icon-font.js#L21

- Users should be able to self-host it.  
- I think that self-hosting should be the default.  Users wouldn't expect their UI library to depend on other third party resources when they install and reference packages from NPM repository locally.  They would have just used CDN hosted versions if they didn't mind depending on third party resources.

**Comment by Lattyware** [comment]
This might be a natural result of this, but just to explicitly state it - it would also be nice to be able to completely avoid loading this font in other components in cases where you are using a different set of icons (e.g: in the select component).
