### ISSUE TITLE
mwc-menu expose anchor margin

### ISSUE THREAD

**Issue by dgoogles** [material-components/material-components-web-components#912]
There is currently no way to specify the anchor margin which makes it difficult to adjust where a menu appears relative to an anchor. For instance, I usually want to move the anchor by about 10 pixels from the bottom of the anchor so it's not directly against it.

If a property could be added for anchorMargin that takes an object like : {top, right, bottom, left} or something similar, that would help.

The x,y properties do end up setting margin for top left, but seems like they are designed for absolutely positioned menus.

**Comment by asyncLiz** [comment]
We currently do not have any specs describing a margin distance between an anchor and its menu, so we likely won't be implementing something into the component.

However, it's fairly trivial to do this yourself. You can add padding to a container element around your anchor and use that as the anchor instead. See https://stackblitz.com/edit/typescript-wsrfng for an example.

**Comment by dgoogles** [comment]
@asyncLiz, what do you mean you do not have any specs? Its already a feature of mdc-menu-surface you just need to expose it in the web component: https://github.com/material-components/material-components-web/blob/781434a92f4dddc9b2d39853e1f5792e89e7b45b/packages/mdc-menu-surface/foundation.ts#L137

Also your given example doesn't work if you only want the padding to affect the menu. If you simply add padding to the anchor any items in the page (siblings) will also be affected by that padding which I wouldn't want. For instance imagine a button in a header where if you added bottom padding it would affect its centering etc.

Please reconsider as its already implemented and just needs to be exposed.

**Comment by asyncLiz** [comment]
There is a difference between internal behavior and behavior described in the menu spec at https://material.io/components/menus/.

According to spec, the menu should be flush against the bottom edge of its anchor.

We want to avoid increasing the API surface of our components where it is not needed. It's very easy to get carried away with making lots of options configurable, and then we're stuck supporting non-spec variations.

Instead, we want to encourage users to extend these components and add their own Material-inspired, but not spec compliant, functionality.

**Comment by dgoogles** [comment]
I'd be fine with that, except why is it exposed in the mdc layer, then? 

The main reason for my request is that we used to get menu functionality by using the mdc-menu component which allowed us to set this. Now that there is a web component we'd like to transition to mwc-menu so we no longer have to wrap mdc-menu, but we can't because this property is no longer configurable. 

If we wanted to implement this functionality ourself we would have to extend both mwc-menu and mwc-menu-surface and then completely copy the mwc-menu render function to use our custom implementation.

**Comment by asyncLiz** [comment]
I'll reopen this and put it in our backlog for now to investigate further with design.

**Comment by e111077** [comment]
Hello, this is currently possible with `absolute` on menu. Simply add an `anchor` to it as well. e.g.

```
<mwc-button label="this is my anchor"></mwc-button>
<mwc-menu
    absolute
    .anchor=${this.buttonElement}
    x="20"
    y="0">
  <mwc-list-item>...</mwc-list-item>
  ...
</mwc-menu>
```

In the above example, menu is +20 pixels margined from the button. Just make sure that **BOTH** `x` and `y` are defined, and the `mwc-menu`'s `position:absolute` is relative to body and not an intermediate ancestor.

Unfortunately, there seems to be a bug setting these values when `corner="BOTTOM_*"`.

**Comment by e111077** [comment]
Closing this issue, but will file another to investigate why bottom corners are failing

**Comment by dgoogles** [comment]
What if I don't want to position it absolutely but I do want the margin?

**Comment by e111077** [comment]
Sorry, I was shooting from the hip earlier without access to the code.

It is fully supported by simply setting `x` and `y`. You may actually be running into #949. You simply have to set those values and add and `anchor` and it should work the margins for you given the corner. There should be a PR coming very soon
