### ISSUE TITLE
textfield: Cursor is rendered outside of the field

### ISSUE THREAD

**Issue by dflorey** [material-components/material-components-web-components#922]
When setting the textfield to "fullwidth" the cursor is rendered on the left outside of the field.
Should there be no padding just like in the regular textfield?
It looks broken when having a fullwidth textareas and a fullwidth textfields below each other.
The text should align.

https://mwc-demos.glitch.me/demos/textfield.html

Changing the style...
.mdc-text-field--fullwidth:not(.mdc-text-field--textarea) .mdc-text-field__input {
    padding: 0px;
}
...to...
.mdc-text-field--fullwidth:not(.mdc-text-field--textarea) .mdc-text-field__input {
    padding: 16px;
}
fixes the alignment for me.

**Comment by asyncLiz** [comment]
Yes, fullwidth filled text fields should not have left or right padding.

Whether or not the filled variant of text area should have padding or not when fullwidth is a spec question we'll need to get guidance on.

**Comment by asyncLiz** [comment]
[b/150381769](http://b/150381769) for reference.

**Comment by asyncLiz** [comment]
Fixed in https://github.com/material-components/material-components-web-components/pull/1469, which removes the fullwidth variant
