### ISSUE TITLE
version of mwc-tab published on npm does not tally with released commits

### ISSUE THREAD

**Issue by christophe-g** [material-components/material-components-web-components#923]
Not sure what is happening here but the version I get with `npm i @material/mwc-tab` does not seem to be in sync with commits listed here: https://github.com/material-components/material-components-web-components/compare/v0.13.0...master

For instance changes under https://github.com/material-components/material-components-web-components/commit/85c6a4239d2c76e1f536b578611657a011a5c856  are not effective in the distributed files (e.g. `mwc-tab-css.js` still uses deprecated `--mdc-tab-text-transform`, supposedly new `--mdc-typography-button-text-transform` has no effect).

**Comment by asyncLiz** [comment]
The typography variables have not been released yet. Are all the features you're missing part of the [Unreleased](https://github.com/material-components/material-components-web-components/blob/master/CHANGELOG.md#unreleased) section of the changelog?

**Comment by christophe-g** [comment]
Ooups, sorry you are right. 

Misinterpreted the following, thinking the 70 commits were part of v0.13.0 ...
![image](https://user-images.githubusercontent.com/1168053/75487100-12a1da00-59ae-11ea-96b7-7ef92db096eb.png)
