### ISSUE TITLE
mwc-menu - dock to the right edge of the container

### ISSUE THREAD

**Issue by govis** [material-components/material-components-web-components#938]
It appears that by default mwc-menu/mwc-menu-surface docks itself to the top left corner of the container. How can we simply change it to the top right corner (when it's on the right-most side of the page) - is it possible without setting an anchor? 

But even setting an anchor and corner property to TOP_END doesn't seem to achieve the desired effect.

![image](https://user-images.githubusercontent.com/971651/75589372-94464600-5a48-11ea-85bb-f8d7aeb89003.png)

It would also be useful if menu could measure itself and adjust its position when it sticks out beyond viewport boundaries.

**Comment by govis** [comment]
Changing <code>.mdc-menu-surface</code> style from
`transform-origin: left top;
right: 0;
top: 0;` to 
`transform-origin: right left;
left: 0;
top: 0;`
makes the menu to right-aligned.
We should not have to inherit and override 2 components for this though.

**Comment by asyncLiz** [comment]
We'll be adding support for this feature built-in. It's also related to an upstream issue: https://github.com/material-components/material-components-web/issues/4775

**Comment by lummie** [comment]
Any idea when this fix will make it into a release?

**Comment by e111077** [comment]
cc: @dfreedm

**Comment by govis** [comment]
Still does not seem to work in v0.17.2. <code>mdcFoundation.flipCornerHorizontally()</code> is being called when I set <code>menuCorner="END"</code>, but the menu position remains unchanged. Is there a working demo of it?

**Comment by e111077** [comment]
Here is a working sample:

https://glitch.com/edit/#!/pool-sumptuous-pan?path=unbundled.html%3A87%3A52
