### ISSUE TITLE
Investigate adding .js at the end of imports

### ISSUE THREAD

**Issue by asyncLiz** [material-components/material-components-web-components#939]
## Initiative / goal
We should set up a linter/copybara rule that automatically adds `.js` at the end of imports (see #926)

### Scope

See above

## Acceptance criteria and must have scope

Linter runs and blocks PRs and copybara script (if needed)

**Comment by e111077** [comment]
Can we close this as a will not implement as we found this was the thing causing issues with unpkg?

**Comment by asyncLiz** [comment]
I think that's appropriate
