### ISSUE TITLE
Publish mwc-drawer

### ISSUE THREAD

**Issue by azakus** [material-components/material-components-web-components#94]

**Comment by mercmobily** [comment]
Thanks for creating this. I (and many others!) look forward to it!

**Comment by jhnsntmthy** [comment]
any movement on this @azakus ?

**Comment by rainerlopez** [comment]
Thanks for creating this.[2]
Any news or timeline? I'm starting a new project so it would be nice to know what to expect.

**Comment by mercmobily** [comment]
The issue https://github.com/Polymer/pwa-starter-kit/issues/220 is marked as "Critical" and it dependes on this one (as well as #98). Does it mean that *this* is now also critical...?

**Comment by azakus** [comment]
Published in v0.6.0
