### ISSUE TITLE
mwc-textfield fullwidth attribute breaks layout for icon

### ISSUE THREAD

**Issue by djlauk** [material-components/material-components-web-components#941]
**Describe the bug**
When I add the `fullwidth` attribute to an mwc-textfield that has an icon, the value is written on top of the icon.

**To Reproduce**
1. Create an HTML page containing the following snippet:
```html
<mwc-textfield label="Test" value="Hello, World" icon="event" fullwidth></mwc-textfield>
<mwc-textfield label="Test" value="Hello, World" icon="event"></mwc-textfield>

<script type="module">
  import '@material/mwc-textfield';
  import '@material/mwc-icon/mwc-icon-font';
</script>
```
2. Serve the HTML page through a (development) server that supports rewriting bare module specifiers
3. View the HTML page

**Expected behavior**
The value of the fullwidth textfield is displayed next to the icon with the appropriate distance, just like for the textfield that is not expanded to full width.

**Screenshots**
![image](https://user-images.githubusercontent.com/3351287/75628262-85da6480-5bd7-11ea-859c-41eff2a033ba.png)

**Browser Version (please complete the following information):**
 - OS: macOS 10.15.3 (Catalina)
 - Browser: Chrome
 - Version: 80.0.3987.122

**Additional context**
Nothing.

**Comment by asyncLiz** [comment]
We're investigating internally if fullwidth is even a variant we need to support for textfields. It does not have spec guidance for the stylistic changes it makes.

In the meantime, I'd suggest not using `fullwidth` and add `width: 100%` to the textfield or use flexbox instead.

[b/150381769](http://b/150381769) for tracking.

**Comment by djlauk** [comment]
Thanks. `width:100%;` works perfectly fine for my use case.

I just thought that this is an odd phenomenon that should not go unreported as the documentation does not indicate it as an invalid use case. (The docs do state, that label and helper will not be shown, but nothing about icons.)

One more thing I noticed when trying that workaround, is: A textfield with `width:100%;` and one with `fullwidth` attribute look different (different padding). Don't know if that's intended. Just FYI.

**Comment by asyncLiz** [comment]
The padding difference is intentional by code, but we're not sure if it's supposed to be there per design. If it's not, we'll remove `fullwidth` styles and encourage `width: 100%` or flexbox instead.

**Comment by asyncLiz** [comment]
Fixed in https://github.com/material-components/material-components-web-components/pull/1469, which removes the fullwidth variant
