### ISSUE TITLE
Add `readOnly` property to textfield and textarea

### ISSUE THREAD

**Issue by asyncLiz** [material-components/material-components-web-components#942]
**Is your feature request related to a problem? Please describe.**
There is no way to set `readonly` on a textfield or textarea.

**Describe the solution you'd like**
Add a property `readOnly` property that sets `readOnly` on the `<input>` and `<textarea>` elements.

**Describe alternatives you've considered**
N/A

**Additional context**
The spec describes read-only fields as "styled the same as a regular text field and is clearly labeled as read-only". The screenshot is incorrect per design, there are no stylistic changes to the field.

**Comment by motss** [comment]
Cool. I was about to ask about this but you beat me to it. Thanks.
