### ISSUE TITLE
The displayed value of a Select is not updated when the selected item is updated 

### ISSUE THREAD

**Issue by prodisoftdev** [material-components/material-components-web-components#954]
**I'm submitting a:**

- [x] bug report
- [ ] feature request

**What browser(s) is this bug affecting:**
All

**Current behavior:**
The selected value is not updated when the selected item is changed dynamically.

**Expected behavior:**
The displayed value for select is updated when the selected item is updated

**Steps to reproduce:**
https://stackblitz.com/edit/typescript-bbg8nm

**Comment by dfreedm** [comment]
@e111077 is this fixed with #951 ?

**Comment by e111077** [comment]
Generally fixed by another PR on canary (can't find it right now). Though there seems to be a bug with the first change this example has surfaced

**Comment by prodisoftdev** [comment]
I updated the component to the latest build ("0.14.0-canary.edd465cd.0") and it seems to be ok:
https://stackblitz.com/edit/typescript-qk2qr5?file=package.json
