### ISSUE TITLE
Add "empty" named slot for when mwc-list has no children

### ISSUE THREAD

**Issue by ForestKatsch** [material-components/material-components-web-components#956]
**Is your feature request related to a problem? Please describe.**
A common UI pattern is to display a message or advice if a list is empty (ex. "No results found"/"Type to search".) At the moment, this must be done manually`.

**Describe the solution you'd like**
A named slot in `mwc-list` that's only visible if the default slot is empty (which can be detected with [`HTMLSlotElement.assignedNodes`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSlotElement/assignedNodes)

**Describe alternatives you've considered**
Handling this logic with an if-statement for each list.

**Additional context**

**Comment by e111077** [comment]
I like this idea! Have a talk with design tomorrow so I'll bring this up then for consideration

**Comment by e111077** [comment]
spoke with design and this is a yes. unfortunately we don't have any designer mocks, but we have an official example I'm going to follow closely
