### ISSUE TITLE
TS1086 error in mwc-formfield, mwc-checkbox and mwc-radio component

### ISSUE THREAD

**Issue by shirleyhsliu81** [material-components/material-components-web-components#978]
**Describe the bug**
I have got the following errors when importing mwc-formfield, mwc-checkbox and mwc-radio component (version 0.13.0) into my Angular test app. But when I imported them into my React app there are no such issues.

ERROR in node_modules/@material/mwc-checkbox/mwc-checkbox-base.d.ts(29,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@material/mwc-formfield/mwc-formfield-base.d.ts(29,19): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@material/mwc-radio/mwc-radio-base.d.ts(29,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@material/mwc-radio/mwc-radio-base.d.ts(49,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@material/mwc-radio/mwc-radio-base.d.ts(60,9): error TS1086: An accessor cannot be declared in an ambient context.

**To Reproduce**
0. Create an Angular test app. Here is the package.json file in my test app.

{
  "name": "my-test-angular",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~7.2.0",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
    "@material/mwc-checkbox": "^0.13.0",
    "@material/mwc-formfield": "^0.13.0",
    "core-js": "^2.5.4",
    "rxjs": "~6.3.3",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.13.0",
    "@angular/cli": "~7.3.8",
    "@angular/compiler-cli": "~7.2.0",
    "@angular/language-service": "~7.2.0",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.2.2"
  }
}

1. import the mwc components (e.g. app.module.ts) to the Angular test app
import '@material/mwc-checkbox';
import '@material/mwc-radio';
import '@material/mwc-formfield';

2. render the components in html (app.component.html)
<mwc-formfield label="Annual leave">
      <mwc-checkbox></mwc-checkbox>
    </mwc-formfield>

    <mwc-formfield label="Latte">
      <mwc-radio name="coffee" checked></mwc-radio>
    </mwc-formfield>

3. run "npm start"
4. You will see the errors in the terminal window

**Expected behavior**
Run "npm start", the Angular test app should show the checkbox, radio button with labels.

**Screenshots**
<img width="1034" alt="Screen Shot 2020-03-09 at 11 14 06 pm" src="https://user-images.githubusercontent.com/58677163/76212859-81f4b500-625d-11ea-8904-162951da1dce.png">

<img width="1658" alt="Screen Shot 2020-03-09 at 11 41 09 pm" src="https://user-images.githubusercontent.com/58677163/76214063-16601700-6260-11ea-9eda-116dd8b4fbe3.png">

**Browser Version (please complete the following information):**
 - OS: iOS v10.14.6
 - Browser: Chrome
 - Version: 80.0.3987.132

**Additional context**

**Comment by e111077** [comment]
This looks like it's because we are using TS 3.7 while Angular is tied to TS3.5.

@aomarks can you confirm that we are using 3.5 internally? Do you think we should tie it down to 3.5?

**Comment by e111077** [comment]
related: microsoft/TypeScript#33939

**Comment by e111077** [comment]
Additionally, @shirleyhsliu81, can you check if you can update your typescript build to 3.7 without breakage?

**Comment by shirleyhsliu81** [comment]
Hi Elliott,

Many thanks for your prompt reply.

Yes, it is working find after upgrading typescript to 3.7.

Cheers,
Shirley

**Comment by e111077** [comment]
Great! Thanks for the response. Going to close this as we don't want to necessarily pin our TS for angular if it can be updated
