### ISSUE TITLE
Implement mwc-top-app-bar and mwc-bottom-app-bar

### ISSUE THREAD

**Issue by azakus** [material-components/material-components-web-components#98]

**Comment by mercmobily** [comment]
Thanks for creating this. I (and many others!) look forward to it!

**Comment by mercmobily** [comment]
The issue https://github.com/Polymer/pwa-starter-kit/issues/220 is marked as "Critical" and it dependes on this one (as well as #94). Does it mean that *this* is now also critical...?

**Comment by azakus** [comment]
top-app-bar shipped in v0.6.0

Creating separate issue for bottom-app-bar

**Comment by mercmobily** [comment]
Can you please provide a link to the other issue?

**Comment by azakus** [comment]
Oh my apologies, that is #298
